### ISSUE TITLE
Write externally usable versions of annotation lookup scripts [sf#10]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#10]
@dosumis 
**Reported by djs93 on 2013-08-02 11:02 UTC**
FlyBase uses a variety of scripts internally for querying ontology linked information in FB chado.  This can be extremely useful for tracking down usage and meaning of terms in the ontology where these terms have no definition.  In order that DAO editors external to FB can use these scripts, we need versions that can be pointed at the public FB chado.  May be sufficient to just hack the config file that sets up a dbh.

**Comment by mmc46** [comment]
**Updated by djs93 on 2013-08-02 11:02 UTC**
- **request type**: New_term_request --> coding_issue

**Comment by Clare72** [comment]
@dosumis is this still on someone's todo list or should it be closed?

**Comment by dosumis** [comment]
I'd just close it.
