### ISSUE TITLE
Adding lineage information for hemibrain antennal lobe olfactory neurons

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#1009]
The antennal lobe local and projection neurons typed in the hemibrain dataset (Scheffer 2020, https://doi.org/10.7554/eLife.57443) include lineage information. This is a set of neurons that was typed in detail, by comparing to FAFB data. Table 6 in the appendix of the paper lists the type names. 
All the lineages described are named the same as in Bates 2020 (https://doi.org/10.1016/j.cub.2020.06.042). Some of the newly named ones in that paper likely correspond to primary neurons, though we can't be absolutely sure yet.

So could the lineage info be added?

Examples: 
The appendix gives the naming recipe for the different types of neurons (uni- and multiglomerular and local), where `[cell cluster ID]` is the lineage

For uniglomerular neurons, the general recipe is 
```
[glomerulus ID] _ [cell cluster ID] Projection Neuron
```
The only change is that for neuroblast/lineages with 1 in the name, like ALad1, ALv1, etc, the 1 is dropped.

D_adPN > neuroblast ALad1
DM4_vPN > lineage ALv1

VP4+VL1_l2PN > lineage ALv2
lLN1 > lineage ALl1
vLN24 > lineage ALv1

**Comment by Clare72** [comment]
Lineage detail from Bates et al. (2020) and Marin et al. (2020) has been added to AL PNs and should be in the latest release (2020-12-02).

The different hemilineages of ALl1 have also been added.

Is there still something missing?

**Comment by mmc46** [comment]
(Maybe this should be in the VFB issues - let me know and I'll move it)

Looking in VFB v2a, the hemibrain neurons don't show the lineage classification nor any relationships for developmental lineage. This could be done based on their type names.

**Comment by Clare72** [comment]
I think maybe this is an issue about typing individuals rather than additions to the ontology?
@admclachlan is working on adding lineage to hemibrain individuals based on their primary neurite tracts - see https://github.com/VirtualFlyBrain/Management/issues/265

But yes, this is a VFB issue rather than FBbt, so closing this ticket.
