### ISSUE TITLE
correction: typo in definition of FBbt:00040055 'labial sensory center'

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#101]
Typo in bold.

"Region of the gnathal ganglion of the adult brain containing terminals of peripheral axons from the posterior branch of the maxillary-labial nerve, **from of a** subset of gustatory receptor neurons of labellum sensilla. Three distinct subregions can be identified: a posterior zone (LS1), a ventral protrusion on the posterior side of LS1 (LS2) and an anterior medial zone (LS3)."

**Comment by temjones** [comment]
Changed "**from of a**" to "**from a**" in the definitions of FBbt:00040055 (labial sensory center), FBbt:00040056 (posterior maxillary sensory center), and FBbt:00040057 (anterior maxillary sensory center).
