### ISSUE TITLE
Subclasses for hemibrain antennal lobe local and projection neurons

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#1011]
Somewhat related to #1009, the typing of antennal lobe local and projection neurons was detailed, and I think it would be worth adding subclasses for the types.

For the projection neurons, the types were decided by comparing FAFB and hemibrain data, so it is not just one dataset. We could identify the same morphologies in the 2 datasets.
For example: currently, individual `M_l2PNm14_R - 1723506321 [VFB_jrchk0w4]` is classified only as `adult multiglomerular antennal lobe projection neuron`

For local neurons, we relied mainly on the hemibrain set to define the typing, as not many LNs are traced in FAFB. But there was also information used from the literature and light level data. There are defined types for the lLN2T/P/R/S/F (corresponding to the previously identified LN2L in Tanaka 2012) already, as defined in the hemibrain, but not for the rest.

Of the 196 LNs in the hemibrain we defined 74 types, so we could find common features that we think will be stereotypical. Of course when more data is available, some of these types might be broken down into subtypes, and there might be some adjustment (lumping some of the current ones together is more likely). But we think the majority will  remain.

Data from Scheffer 2020 https://doi.org/10.7554/eLife.57443

**Comment by Clare72** [comment]
There are more lineage-specific terms in the latest FBbt release, so M_l2PNm14_R can now be mapped to ' adult multiglomerular antennal lobe projection neuron l2PN'.

I don't think I can make a term for l2PNm14 as I don't think there is a definition for it(?)

lLN2T/P/R/S/F subtypes (as defined in Scheffer et al., 2020) are in the latest release (and type mapping in VFB will be updated soon).

>Of the 196 LNs in the hemibrain we defined 74 types, so we could find common features that we think will be stereotypical.

When this work is published (can be preprint), I can add the types and their descriptions (common features) to the ontology.

**Comment by mmc46** [comment]
> I don't think I can make a term for l2PNm14 as I don't think there is a definition for it(?)

There aren't any textual descriptions, but the types (beyond being a l2 mPN taking the mALT tract) are defined by the morphology and connectivity of its neurons. 
Similarly to antennal lobe local neurons: the defined types are already in neuprint, and our work won't provide a textual definition for each one. 
But for both cases above, we can point to specific and detailed images of neurons for each type.
