### ISSUE TITLE
Embryonic fat body precursor terms

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#1015]
We have 'embryonic fat body', 'fat body promordium' and 'fat body/gonad primordium'

'embryonic fat body' did not previously have a definition
'fat body primordium' is described as being the primordium after the gonadal sheath primordium splits from it in stage 14, but gonadal primordia are only in PS10-12 according to FBrf0101991 and this ref also refers to segmentally repeated clusters of cells as primordia before precursors join into a contiguous fat body structure (and before stage 14).

We should probably merge 'embryonic fat body' and 'fat body primordium' and perhaps broaden the definition to cover fat body precursors at any stage of embryonic development.

I think perhaps 'fat body/gonad primordium' might refer to the 'bipotential lateral mesoderm primordia' of FBrf0102832, which can develop into either fat or gonad precursors (but is not the only source of fat precursors), rather than some kind of fused primordial entity. According to FBrf0101991, fate is chosen by around stage 10 (expression of srp in fat precursors). So this definition needs modifying.

**Comment by gouttegd** [comment]
# Current state in FBbt

We have 4 distinct terms referring to the fat body or the fat body precursors:

* `fat body/gonad primordium`,
* `fat body primordium`,
* `embryonic/larval fat body`,
* `embryonic fat body`.

The first three are connected by `develops_from` relationships: the `embryonic/larval fat body` *develops from* the `fat body primordium` which *develops from* the `fat body/gonad primordium`. The fourth term is not connected to any of the others.

# Proposed solution

1) Clarify the developmental stages the first three terms refer to, when it's not already done:
* `fat body/gonad primordium` covers stages 10 to 14 (from the expression of the early markers of fat cell precursors to the separation of the somatic gonadal precursors);
* `fat body primordium` covers stages 15-16, when the different primordia fuse to form a continuous layer in which cells are still differentiating;
* `embryonic/larval fat body` covers stage 17 and onward (throughout the larval stages), when all cells are terminally differentiated and are true fat cells and no longer precursor fat cells.

2) Merge `embryonic fat body` with `fat body primordium`. The current definition of `embryonic fat body` ("*developing* fat body of the embryo") matches the intended meaning of `fat body primordium`.

**Comment by SianGramates** [comment]
Hi Damien,

Thanks for untangling that. I like your solution; the staging should
definitely be included in the term definitions.

Cheers,
Sian
