### ISSUE TITLE
Typo in zone B Jon def

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#102]
zone B Johnston organ neuron
ID: FBbt_00100009

Definition: Johnston's organ neuron that innervates zone B of the antennal mechanosensory and motor center (AMMC). The cell bodies of zone B Johnston organ neurons are distributed as a ring in the middle layer of cells within the Johnston's organ (Kamikouchi et al., 2006). These neurons plays a role in hearing and are activated when stimulated with courtship song pulses (between 19-952Hz, 90dB). They **_are is_** phasically activated, with stronger activation by low-frequency vibrations. They are required for the detection of the courtship song (Kamikouchi et al., 2009).

**Comment by temjones** [comment]
I have corrected this ahead of the next FBbt release on 2017-09-14.
