### ISSUE TITLE
New Term Request: ventral abdominal lateral (vAL) and ventral abdominal medial (vAM) interneurons

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1033]
For new term requests, please provide the following information:

## Preferred term label

ventral abdominal lateral and ventral abdominal medial interneurons (female?)

## Synonyms

vAL and vAM interneurons

## Textual definition

FBrf023727

**Comment by Clare72** [comment]
FBrf0237271
