### ISSUE TITLE
New Term Request: CCHa2 and CCHa2-r expressing neurons

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1040]
For new term requests, please provide the following information:

## Preferred term label

CCHamide-2 and CCHamide-2 receptor

## Synonyms

CCHa2 and CCHa2-R

## Textual definition

CCHa1-expressing neurons

FBrf0241737

**Comment by Clare72** [comment]
Terms have not historically been made for '<neuropeptide> receptor neuron' and am not sure how useful these types of terms would be.

I think the receptors tend to be found in more cells and more different receptors are found in each cell compared to neurotransmitters/neuropeptides.

I will make the missing '<neuropeptide> neuron' terms.
