### ISSUE TITLE
Symbols for grouping classes

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#1049]
Just noticed that 'mushroom body output neuron' has no symbol.  Would be good to add 'MBON'.  Ditto other grouping classes where we can add something in line with HemiBrain neuron symbols.

**Comment by dosumis** [comment]
Ditto Kenyon Cell

**Comment by Clare72** [comment]
Added grouping terms to symbols mapping file mostly based on Scheffer et al. (2020) appendix 1 - table 6:
https://github.com/FlyBase/flybase-ontology-scripts/commit/54969ddbaa4ec573fcd2f3fe5521d32e958bdfbe
