### ISSUE TITLE
New anatomy term for a fruitless expressing neuronal cluster

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#106]
FBrf0210397 identifies and describes a fruitless cluster similar to pC1 (FBbt:00110621 & FBbt:00110507) and pC2 (FBbt:00110611& FBbt:00110487) with sex specific differences that they call pC3.

This paper has been cited 100+ times, although I'm not sure how many refer to pC3. The recentish paper FBrf0234085 from the same lab does.

**Comment by Clare72** [comment]
Hmm, the pC clusters seem to be characterised by expression of DOUBLESEX, not fruitless. To me, it looks like pC1 and pC2 are not the same thing as the fruitless-expressing neurons that they are listed as exact synonyms for.
FBrf0210397 shows some colocalisation, but this is far from 100%
I think the dsx neurons should have their own classes - there are at least four papers using this set of  terms now (pC, aDN, SN, TN, etc).
