### ISSUE TITLE
Obsoletion of 'fascicle'

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#1068]
'ipsilateral tract':
>A tract of the central nervous system that does not cross the midline.

'fascicle' (child of 'ipsilateral tract'):
>A slender neuron projection bundle that doesn't cross the midline.

The only real difference between these seems to be width, but it isn't specified how narrow a 'fascicle' should be, making this term a bit useless.
Ito et al. (2014) - FBrf0224194 also uses 'fascicle' to refer to what we call an 'ipsilateral tract'.

The existing 'fascicle' term should be obsoleted (with existing 'ipsilateral tract' term as suggested replacement), but I would like to rename our 'ipsilateral tract' to 'fascicle' for consistency with Ito et al. (2014), so I will rename 'fascicle' to 'slender fascicle' prior to obsoletion to allow re-use of the label.

**Comment by SianGramates** [comment]
Please include fascicle as a synonym (I run across it in the literature, where it's not always obvious that the term I'm looking for is in fact ipsilateral tract). Are you also renaming all the children of fascicle? There's a lot of them, which use 'fascicle' as part of their names (which I'd think is an argument for not renaming the term at all).

**Comment by Clare72** [comment]
So after this is finished we will have 'ipsilateral tract' renamed to 'fascicle' (keeping synonym) and the old term for 'fascicle' (meaning a narrower 'ipsilateral tract') will be made obsolete (and renamed to 'slender fascicle' to allow reuse of 'fascicle' name). There will no longer be a subtype corresponding to the old 'fascicle', everything will be under the new 'fascicle'.

**Comment by SianGramates** [comment]
Aha! I'd interpreted that in exactly the opposite manner. I approve this plan.
