### ISSUE TITLE
vPNs GABAergic inhibitory

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#108]
According to this paper, ventral lineage AL projection neurons are GABAergic.  It would be good to reflect this in the ontology (if the data looks clean enough to assert this for all).

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3838762/

**Comment by Clare72** [comment]
It is most, but not all:

"Consistent with a previous report (Okada et al., 2009), we found that the vast majority of Mz699+ ventral PNs were GABAergic based on GABA staining (Figure 1F; 87.6±2.5% GABA-positive, from 8 antennal lobes with an average of 55 cells per lobe)"

**Comment by Clare72** [comment]
Closing this, as it cannot be asserted for all cells.
