### ISSUE TITLE
Review the 'embryonic/larval hypodermal muscle' hierarchy

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1088]
All late embryonic/larval somatic muscles (FBbt:000464) are under a single term 'embryonic/larval hypodermal muscle' (FBbt:0000465).

There are two possible concerns with that term:

* “Hypodermal” seems infrequently used to refer to those muscles – entire reviews dedicated to embryonic myogenesis make no mention of it (e.g. Abmayr et al., 1995 [FBrf0081131]; Beckett & Baylies, 2006 [FBrf0193321]). “Body wall muscles” seems preferred. There is already a 'body wall' synonym on FBbt:0000465 itself, but not on the terms below in the hierarchy.
* As discussed in commit eea2e9e, hypodermal/body wall muscles seem to represent the entirety of the larval somatic musculature, so 'embryonic/larval hypodermal muscle' may be redundant with 'embryonic/larval somatic muscle'.

Possible actions to consider:

* Rename FBbt:00000465 to 'embryonic/larval body wall muscle', and all the terms below it accordingly.
* Keep the current name, but add a 'body wall' synonym to the terms below it (least intrusive option).
* Merge FBbt:00000464 and FBbt:00000465.

**Comment by gouttegd** [comment]
All somatic muscles of the late embryo (stage 17) and the larva are collectively referred to by the term '[embryonic/larval somatic muscle](https://flybase.org/cgi-bin/cvreport.pl?id=FBbt:00058297)' (FBbt:00058297) (synonym: 'embryonic/larval skeletal muscle'). They also almost all (save one, see below) fall under the term '[embryonic/larval hypodermal muscle](https://flybase.org/cgi-bin/cvreport.pl?id=FBbt:00058298)' (FBbt:00058298) (synonym: 'embryonic/larval body wall muscle').

There are many reasons to believe that the embryonic/larval “somatic” (or “skeletal”) and “hypodermal” (or “body wall”) muscles represent in fact the exact same set of muscles.

* Bate 1993 (FBrf0064793) uses the expression “body wall muscles“ only twice, and when he does it is clearly to refer to all the larval somatic muscles. He never uses “hypodermal muscles”, but he does describes the “larval somatic muscles” as “muscles forming on the inner surface of the epidermis” (i.e. hypodermal).
* Several other authors mention in passing that the larval hypodermal (body wall) muscles are actually the entirety of the larval somatic musculature:
  * Sawin _et al._ 1994 (FBrf0076757) say that the “musculature of the _Drosophila_ larva consists of hypodermal muscles”;
  * Schulman _et al._ 2015 (FBrf0228644) say that the “larval musculature […] consists of a repeated pattern of hemisegments along the body wall, each of which is composed of 30 muscles”;
  * Dobi _et al._ 2015 (FBrf0228646) write “the fruit fly forms two discrete muscle systems throughout its life cycle; the larval body wall muscles are established during embryogenesis, while the adult musculature […]“.

The only larval somatic muscle in FBbt that is currently _not_ also a hypodermal muscle is the '[anterior spiracle retractor muscle](https://flybase.org/cgi-bin/cvreport.pl?id=FBbt:00058295)', and that may well be an oversight of our part, given that (1) the posterior spiracle retractor muscles are considered to be hypodermal, and (2) Heise 1938 describes the spiracle retractor muscles as “lying on the hypodermis” and “strongly fixed in the hypodermis”.

Overall, I found no evidence to support FBbt’s current assertion that hypodermal (body wall) muscles are a _subset_ of the larval somatic (skeletal) muscles. On the contrary, it seems that “somatic”, “skeletal”, “hypodermal”, and “body wall” all refer to the exact same set of muscles.

I therefore propose to

(1) merge 'embryonic/larval somatic muscle' and 'embryonic/larval hypodermal muscle', the two terms being redundant; using “somatic muscle” in the label of the merged term as it seems to be the preferred term in the literature (of course keeping “hypodermal“, “skeletal“, and “body wall“ as exact synonyms);
(2) likewise, merge `embryonic somatic muscle` and `embryonic hypodermal muscle`, for the same reasons (those terms refers to the same muscles, but in early embryos, prior to stage 16).

**Comment by SianGramates** [comment]
This situation is kind of my fault. I'd asked the then-ontology curator to add 'body wall muscle (BWM)' as an exact synonym to embryonic/larval somatic muscle, as that's the term a lot of researchers doing NMJ research would look for.  He was adamant that 'body wall muscles' would exclude some of the muscles of the head, so added a term specifically for the body wall (non-head) muscles. 'Hypodermal muscle' was the ontology curator's term choice. (not that I've made/looked at a whole lot of BWM fillets or anything).

**Comment by Clare72** [comment]
Thanks for the explanation Sian. Unfortunately it seems that ontology editor did not add this clarification to the ontology, so it was unavailable to curators and subsequent ontology editors. Now we are in a situation where we have head muscles categorised as hypodermal muscles (I am not sure whether or not this is 'correct'), so the distinction between body wall and head has not been maintained.

**Comment by gouttegd** [comment]
Indeed, thanks for the history.

> He was adamant that 'body wall muscles' would exclude some of the muscles of the head

Upon re-reading [Schoofs (2010)](https://www.sciencedirect.com/science/article/pii/S0022191009003898), I believe that editor may actually be right…

Of all the somatic head muscles described in this paper, only the dorsal protractors are attached on one end to the head cuticle.

The other muscles are not connected to the body wall. The cibarial dilators are attached to one part of the craniopharyngeal skeleton (CPS) to another, and the mouth hook elevators/depressors are attached to the CPS on one end and the mouth hooks on the other end ([figure 1](https://www.sciencedirect.com/science/article/pii/S0022191009003898#aep-section-id25)). Therefore I don’t think they could be called “body wall“ or “hypodermal” muscles.

Statements that the body wall muscles represent the entirety of the larval somatic musculature may be the result of the fact that head muscles had not been thoroughly described prior to 2010.

> Now we are in a situation where we have head muscles categorised as hypodermal muscles (I am not sure whether or not this is 'correct')

From the above, I now think that it is not correct for all of them (it may be correct for the dorsal protractors only), and the proposed merge may not be warranted.

Instead, I believe we should:

1) Leave 'embryonic/larval hypodermal muscle' as it is (including the “body wall” exact synonym), with perhaps an improved definition that makes it clear they refer to the muscles that are attached on at least one end to the body wall.
2) Re-classify the somatic muscles of the head that are _not_ attached to the body wall as 'embryonic/larval somatic muscle' instead of 'embryonic/larval hypodermal muscle'.

Sorry for the noise.

**Comment by SianGramates** [comment]
Thanks Damien. And no need for apology; it looks like knowing the history (which appears to have never made it from my head to the actual definition) was necessary to clarity.
