### ISSUE TITLE
New Term Request: ALPN1-4, loPN, plpPN

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1098]
For new term requests, please provide the following information:

Descriptions in FBrf0246721

Can ALPN1-4 just be 'antennal lobe projection neuron' types?

loPN - lobula projection neuron?

plpPN - posterior lateral protocerebrum projection neuron?

## Synonyms

ALPN1-4, loPN, plpPN

## Textual definition

Given in paper?

**Comment by Clare72** [comment]
Based on supplement, LOPN is SLP448 - have edited this term. ALPNs also map to existing cell types, AL1,2&4 done, awaiting author response for ALPN3 mapping. PLPPN is a new term.
