### ISSUE TITLE
muscles/neurons/sense organs of leg

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#1099]
Kuan et al. (2020) leg X-ray paper

FBrf0247324 - https://www.nature.com/articles/s41593-020-0704-9

**Comment by Clare72** [comment]
@gouttegd this is finished now right? If so, please close.

**Comment by gouttegd** [comment]
Indeed, there was nothing more to extract beyond the muscles.
