### ISSUE TITLE
Add terms for LLPC neurons

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1103]
Recent papers mention some *lobula - lobula plate columnar neurons* (LLPC neurons). Notably Scheffer et al. (2020) (FBrf0246888) found 6 types of LLPC neurons (LLPC1, LPPC2[a-d], and LLPC3). But information about those neurons is sparse.

Currently the ontology defines a “generic” `lobula complex columnar neuron` class which is narrowly aliased to, among other things, `LLPC`, but while it has more precise classes for, e.g., LPLC neurons, there is such class for LLPC neurons.

VFB has some LLPC1 neurons (e.g., FlyEM-HB:1780362273), which are classified as `lobula complex columnar neuron`, possibly for lack of a more precise class.

**Comment by Clare72** [comment]
awaiting further publications describing these cell types
