### ISSUE TITLE
S Cell definition should be responsive to sugars and/or amino acids?

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#111]
S Cell definition is currently:'Gustatory receptor neuron responsive to sugars (Montell, 2009), and also amino acids (Dunipace, et al., 2001).'

FBrf0234535 (and work referenced therein) shows that not all S Cells detect amino acids and sugars, but may have specificity to one or the other or both, should 'and also' in the definition be replaced with 'and/or'?

**Comment by temjones** [comment]
This looks sensible. I have made this edit and added this paper as a reference.
