### ISSUE TITLE
merge 'pigment cell' and 'retinal pigment cell'

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#1129]
'pigment cell':
>Cell that contains pigments and it is found in or between ommatidia.

'retinal pigment cell':
>A cell of the retina containing screening pigments that functions to screen photoreceptors from light leaking from adjacent ommatidia.

These are clearly refering to the same cell type and should be merged.
In addition, Liu et al. (2015) - FBrf0227305 state that pigment cells are glia, and have metabolic interactions with the photoreceptors (see also FBrf0210316 - Edwards and Meinertzhagen, 2010). This information should be incorporated.

**Comment by SianGramates** [comment]
I think this is a good plan.
