### ISSUE TITLE
Update terms related to hemocytes

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1137]
Cattenoz et al. (2020) (FBrf0245988) performed scRNAseq analysis of embryonic and larval hemocytes.

They don't describe any new cell types that would warrant introducing new terms to FBbt, but we can still use that paper to:

* check and update our terms related to hemocytes;
* add some gene expression information with markers specific for each type of hemocytes (plasmatocytes, lamellocytes, crystal cells).

Among the issues to address when updating the existing term is the existence of the `embryonic hemocyte`, which may be redundant with `embryonic/larval hemocyte`.

**Comment by gouttegd** [comment]
Here's a summary of the main issues with our current terms describing hemocytes, and below the proposed plan to resolve those:

* Redundancy between `embryonic hemocyte` and `embryonic/larval hemocyte`;
* Similar redundancy between `embryonic hemolymph` and `embryonic/larval hemolymph`;
* Potential obsolete terms `podocyte` and `macrophage`;
* Complete absence of any term referring to adult hemocytes.

# Proposed actions

1. Merge `embryonic hemocyte` with `embryonic/larval hemocyte`. The rationale for that is two-fold. First, the two terms are redundant. Second, `embryonic hemocyte` was originally coined by Holz et al. (2003) (FBrf0162082) to refer to the hemocytes *originating* in the embryo, to distinguish them from the hemocytes originating from the lymph gland later during development; but we already have `head mesoderm derived embryonic hemocyte` for that very purpose, so even with that meaning `embryonic hemocyte` is redundant.

2. Merge `embryonic hemolymph` with `embryonic/larval hemolymph`. This should be uncontroversial as `embryonic hemolymph` has seemingly never been used in curated records.

3. Obsolete `podocyte`, merging it with `plasmatocyte`. The current reference associated with that term (Lanot et al., 2001 – FBrf0134542) does not support the idea that podocytes are distinct from plasmatocytes; recent and even not-so-recent reviews all seem to agree that there are only 3 types of hemocytes (plasmatocytes, crystal cells and lamellocytes) and never mention podocytes at all (e.g., Wood & Jacinto, 2007 – FBrf0202336; Honti et al., 2014 – FBrf0223115).

4. Obsolete `macrophage`, merging it with `plasmatocyte`. Recent and not-so-recent reviews use "macrophage" and "plasmatocyte" interchangeably (e.g. Gold & Brückner, 2015 – FBrf0232226; Wood & Martin, 2017 – FBrf0234752). Plasmatocytes have other functions besides being "the macrophages of *Drosophila*" but plasmatocytes with macrophage-like activity don't seem distinguishable from the bulk of plasmatocytes.

5. Rename `head mesoderm derived embryonic hemocyte` to `head mesoderm derived hemocyte`. This will better reflect the definition and the intended use of that term, which refers to hemocytes that *arise* in the head mesoderm during embryogenesis but exist beyond the embryonic stages.

6. Introduce terms for the missing compartments of free-circulating hemocytes and lymph gland-sequestered hemocytes. Those terms will be on par with the existing term `sessile hemocyte`, so that we have a term for all three compartments where larval hemocytes are known to be found.

7. Introduce terms for adult hemocytes and superclasses grouping both embryonic/larval and adult versions of each term. For example, the current term `plasmatocyte` will become `embryonic/larval plasmatocyte` (fitting its current definition, and the way it has been used in curation), and will be a subclass of a new generic term `plasmatocyte`, along with a sibling `adult plasmatocyte`. Likewise for `crystal cell`, but *not* for lamellocytes, because it is established that there are no lamellocytes in the adult.

**Comment by SianGramates** [comment]
IF you obsolete podocyte and macrophage, make sure to preserve them as synonyms to the surviving term; that makes it much easier to find the correct ontology term when an obsolete term is used in a paper (I've definitely seen and curated to 'macrophage')
