### ISSUE TITLE
Update eye disc compartments and cell types - Ariss et al. (2018)

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1147]
Ariss et al. (2018) (FBrf0240781) performed scRNAseq analysis of third-instal larval eye discs.

No newly discovered cell type to add, but potentially some refinements to our current description of the eye disc, such as:

* subdividing the `peripodial epithelium of eye disc` into _ventral_ and _dorsal_ peripodial epithelia;
* possible redundancy between `eye disc anterior to the morphogenetic furrow` and `eye disc anterior compartment` (and similarly for posterior equivalent terms);
* adding specific subclasses for otherwise pre-existing cell types referring to those cells in the eye disc (e.g., a subclass of `embryonic/larval PNS perineurial glial cell` for perineurial cells of the eye disc);
* adding gene expression information.

**Comment by gouttegd** [comment]
We have two couples of terms referring to anterior and posterior compartments of the eye disc:

* `eye disc anterior compartment` and `eye disc anterior to the morphogenetic furrow`;
* `eye disc posterior compartment` and `eye disc posterior to the morphogenetic furrow`.

In the same vein, we also a couple `anterior-posterior compartment boundary of the eye disc` and `morphogenetic furrow`.

I believe the terms in those couples are redundant since, in all studies involving the eye disc that I know of, the morphogenetic furrow _is_ the reference from which the anterior and posterior compartments are defined.

`anterior-posterior compartment boundary of the eye disc` has never been used in curation; `eye disc anterior compartment` and `eye disc posterior compartment` have been used in 20 records, and in the corresponding papers there is nothing suggesting the authors are defining the anterior and posterior compartments relatively to anything else than the morphogenetic furrow.

**I therefore propose to merge:**

* `eye disc anterior compartment` with `eye disc anterior to the morphogenetic furrow`;
* `eye disc posterior compartment` with `eye disc posterior to the morphogenetic furrow`;
* `anterior-posterior compartment boundary of the eye disc` with `morphogenetic furrow`.

In all cases, the "surviving" term would be the one that has been the most used (or used at all) in curation; the "losing" term would as usual subsist as a synonym.

**Comment by gm119** [comment]
Is the morphogenetic furrow really the same thing as the boundary between the anterior and posterior compartments ? I thought that the morphogenetic furrow 'sweeps' across the eye as a wave of differentiation, so its a boundary between differentiated vs undifferentiated cells that doesn't stay in the same place with respect to anterior vs posterior part of the disc over time. I think the GO definition of GO:0007458 (progression of morphogenetic furrow involved in compound eye morphogenesis) does suggest that:

The morphogenetic furrow is a dorsoventral indentation which sweeps anteriorly across the eye disc. Ommatidia begin to form along the furrow, resulting in a graded series of ommatidial development across the anterior/posterior axis of the disc. [ http://www.ncbi.nlm.nih.gov/pubmed/3076112 http://www.ncbi.nlm.nih.gov/pubmed/3937883 ]

I thought the setting up the anterior and posterior compartments was something different that is set up earlier and didn't really move over time within a tissue/segment but maybe I'm wrong and its different for discs vs embryos ?

**Comment by gouttegd** [comment]
> I thought that the morphogenetic furrow 'sweeps' across the eye as a wave of differentiation

Yes it does.

> I thought the setting up the anterior and posterior compartments was something different that is set up earlier and didn't really move over time.

That's the case for the A/P compartments in the wing and leg discs, but not in the eye disc. A/P compartments in the eye disc are defined more by the properties and behaviours of cells on each side of the morphogenetic furrow (undifferentiated, proliferating cells anteriorly vs differentiating, non-proliferating cells posteriorly):

> By contrast, the anterior and posterior domains of the eye are not restricted by cell lineage and the boundary between them is dynamic. [...] Two characteristics distinguish anterior from posterior in the eye disc: growth occurs in the anterior, with the exception of the second mitotic wave, and differentiation occurs in the posterior (Lee and Treisman, 2001 – FBrf0135725).

**Comment by gm119** [comment]
ooh, thanks for the link to the reference (learnt something new today !)

**Comment by SianGramates** [comment]
Those terms are not redundant; please don't do this.

**Comment by SianGramates** [comment]
I didn't account for the multiple issues in this ticket; I was specifically intending the A/P compartment & anterior/posterior to MF merge. I'm on board with the peripodial cell & perineurial glial cell issues.

**Comment by gouttegd** [comment]
> I was specifically intending the A/P compartment & anterior/posterior to MF merge.

No worries, that how I understood your comment.

**Comment by gouttegd** [comment]
Closing as what has been agreed on has been done.
