### ISSUE TITLE
Possible misuses of "S cell" and other similar generic-sounding terms

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1190]
The term `S cell` (FBbt: 00100041) refers strictly to gustatory receptor neurons (GRNs) _of the labellum_. However, there is at least one instance where that term has been used incorrectly to refer to GRNs elsewhere in the body: the [Gr43a](https://flybase.org/reports/FBgn0041243) gene has been annotated as being expressed in "S cell | subset of prothoracic tarsal segment 5", "S cell | subset of mesothoracic tarsal segment 5", "S cell | subset of adult labral sense organ"... The "real" generic (location-independent) term is `sugar-sensing neuron` (FBbt:00049614), it should have been used here instead of `S cell`.

We need to check whether that misuse is an isolated case or if it happened elsewhere. If it's an isolated case, then we may just ask the curators to fix the record for _Gr43a_. Otherwise, it may be better to fix the problem on FBbt side.

**Comment by gouttegd** [comment]
### `S cell`

Defined as a sugar-sensing neuron of the labellum. Used in 38 records. In 26 of them, it is incorrectly used to refer to sugar-sensing neurons elsewhere in the body (e.g. `S cell | subset of prothoracic leg taste bristle`, in [FBal0290235](https://flybase.org/reports/FBal0290235)).

### `W cell`

Defined as a water-sensing neuron of the labellum. Used in 6 records, all with the correct intended meaning.

-> Can be renamed to something like `water-sensing neuron of the labellum` (with `W cell` as a synonym).

### `L1 GRN`

Defined as a labellum GRN sensitive to low concentrations of salt. Used in 3 records, all with the correct intended meaning.

-> Could be renamed to something like `low salt-sensing neuron of the labellum`.

### `L2 GRN`

Defined as a labellum GRN sensitive to bitter compounds or high concentrations of salt. Used in 61 records. In 22 of them, it is incorrectly used to refer to high salt- or bitter-sensitive neurons elsewhere in the body (e.g. `L2 GRN | subset of prothoracic tarsal segment 5`, in [FBal0249513](https://flybase.org/reports/FBal0249513)).

**Comment by SianGramates** [comment]
I've done some quick checking, and S cell of (not labellum) is definitely attached to multiple GAL4 alleles. I'm wondering if, at some point, there was a definition that wasn't labellum specific (not that that would negate the need to fix the issue, but might explain what happened).

**Comment by gouttegd** [comment]
It's quite possible indeed.

Now one possible way to fix the issue would be to merge `S cell` with `sugar-sensing neuron` and to create a new specific term for the sugar-sensing neurons of the labellum (which would be unimaginatively named `sugar-sensing neuron of the labellum`). This way, most of the records currently using `S cell` shouldn't need updating – only those in which `S cell` was really used with the intention of referring to the labellar neurons would need to be updated to use the newly created term.

**Comment by SianGramates** [comment]
I think we may want to do a quick review of how authors have been using S cell, which may also be the source of confusion. It looks like at least some of the incorrect uses have correct terms that ought be attached instead, so I do think we should do those corrections.

**Comment by SianGramates** [comment]
S cell misuse affects curation for 6 references, with the bulk of the misuse in the first two papers listed here:
FBrf0225125
FBrf0227698 (also free text)

FBrf0229531
FBrf0234535 (also in free text)
FBrf0219961
FBrf0226011 (also some free text wonkiness)

check use of 
P{Gr64f-GAL4.9.7} as marker for S cell

**Comment by SianGramates** [comment]
L2 GRN was misused in these 5 references (mostly in the first 3 listed). 3 of these overlap with the S cell list.

FBrf0225125
FBrf0234535 (also in free text)
FBrf0235764 (also in free text)
FBrf0225921
FBrf0229531

**Comment by gouttegd** [comment]
Thanks a lot @SianGramates for the review of the affected references.

I suggest the following plan to fix the issue:

### For `S cell`

* Merge `S cell` with the "generic" parental term `sugar-sensing neuron`.
* Add a new term referring specifically to the labellar neurons, with an explicit name (`sugar-sensing neuron of the labellum`).

With this approach, records that are currently using `S cell` to refer to non-labellar sugar-sensing neurons would become correct (once the merge has been retrofitted). And records that are currently using `S cell` correctly to refer to labellar sugar-sensing neurons would still be nominally correct, though not as precise as the curator initially intended – these records may then later be updated to use the new labellar-specific term to restore the initial meaning.

### For `L2 GRN`

Similar approach, except that we don't have a parental term to merge `L2 GRN` into (`salt-sensing neuron` is too broad as it encompasses both neurons responsive to low salt concentrations and neurons responsive to high salt concentrations). So:

* Update `L2 GRN` definition to make it generic (not specific to labellar neurons); also probably rename it with a more explicit name like `high salt-sensing neuron`, keeping `L2 GRN as synonym`.
* Add a new child term referring specifically to labellar neurons (`high salt-sensing neuron of the labellum`).

Again, records that are currently using `L2 GRN` with a generic meaning would then be correct. Records that are using that term with its precise labellar-specific meaning would temporarily lose some precision, until they are updated to use the new specific term for labellar neurons.

### `W cell` and `L1 GRN`

Those terms are only used with their correct, labellar-specific meaning, so we can just rename them with more explicit names without affecting curation records.

**Comment by gouttegd** [comment]
Update: merging `S cell` with `sugar-sensing neuron` may not actually be a good idea. "S cell" is used to refer to sugar-sensing neurons in taste bristles, but there are sugar-sensing neurons that do _not_ belong to a taste bristle and should not be assimilated with S cells. Likewise for the other types of GRNs.

Therefore, instead of merging `S cell` with `sugar-sensing neuron`, I propose to keep those two terms distinct and to rename `S cell` to `sugar-sensing neuron of gustatory sensillum`, below which we can then add the more specific `sugar-sensing neuron of the labellum`. Besides being more correct, this would also have the advantage of not requiring any retrofit, since there's no obsoletion/merging involved. Records that currently use `S cell` in its generic meaning would be immediately correct, and those that use it in its labellar-specific meaning can be later updated to use the more precise term.

Overall and to summarise, the idea is then to have the following hierarchy:

* `gustatory receptor neuron`
  * `sugar-sensing neuron`
    * `sugar-sensing neuron of gustatory sensillum` (aka `S cell` as used in the literature);
      * `sugar-sensing neuron of the labellum`
  * `water-sensing neuron`
    * `water-sensing neuron of gustatory sensillum` (aka `W cell` as used in the literature)
      * `water-sensing neuron of the labellum`;
  * `salt-sensing neuron`
    * `salt-sensing neuron of gustatory sensillum`
      * `low salt-sensing neuron of gustatory sensillum` (aka `L1 GRN` as used in the literature);
        * `low salt-sensing neuron of the labellum`
      * `high salt-sensing neuron of gustatory sensillum` (aka `L2 GRN` as used in the literature);
        * `high salt-sensing neuron of the labellum`

**Comment by SianGramates** [comment]
I think the first step is to review the papers for which incorrect curation is attached, to determine whether the misuse was author or curator-based (e.g. how are people using these terms in the wild). Might also be good to scrutinize authorship...we probably don't want to rename terms if only one lab is misusing the term. I do note that while a fairly large number of alleles are affected, as detailed above, only a handful of publications (8 total) are affected.

**Comment by gouttegd** [comment]
Strikingly, none of the of papers you flagged (which all seem to come from different labs) ever uses `S cell` or `L2 GRN`. They use some variations of "sugar-sensing neurons", "sweet taste neurons", "sugar neurons", "high salt neurons" or "high-NaCl neurons".

As best as I can retrace the history of the "S cell", "W cell", "L1 GRN" and "L2 GRN" terms, they do seem to have been coined initially to refer to labellar neurons in the 1980s (e.g. Rodrigues and Siddiqui, 1981; FBrf0037073) or even earlier, but to have been later generalised to refer to similar neurons in any taste sensilla (e.g. Singh 1997, FBrf0100249; Pollack and Balakrishnan 1997, PMID9438252; Dunipace et al. 2001, FBrf0137203; or Meunier et al. 2003, FBrf0160792).

**Comment by SianGramates** [comment]
Good to know. So it sounds like the original curations may have been curator error, they are nonetheless following common usage drift. So it may be best to added anatomy-specific terms for S cells in anatomy-specific taste bristles.
