### ISSUE TITLE
term disambiguation: uniglomerular lAL PN

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#121]
FBrf0222962 states that Scer\GAL4[GH146.PB] drives expression in "uniglomerular lAL PNs and the majority of uniglomerular adPNs". (lAL = lateral antennal lobe, PN = projection neuron, adPN = anterodorsal projection neuron). 

I can't quite tell if "uniglomerular lAL PN" should be a synonym for "uniglomerular antennal lobe projection neuron" FBbt:00007383, a synonym to one of its children, or should be a new term (it's the 'lateral' that's confusing me). 

I think 'uniglomerular adPN' is 'adult uniglomerular antennal lobe projection neuron adPN' FBbt:00100368, so that should be (I think) a synonym.

**Comment by Clare72** [comment]
>I can't quite tell if "uniglomerular lAL PN" should be a synonym for "uniglomerular antennal lobe projection neuron" FBbt:00007383, a synonym to one of its children, or should be a new term (it's the 'lateral' that's confusing me).

Looks like this should be a new child term under "uniglomerular antennal lobe projection neuron" that will be a parent to all the lateral subclasses. There are similar classes to this for the adPNs and vPNs already - I will create one for the lPNs.

>I think 'uniglomerular adPN' is 'adult uniglomerular antennal lobe projection neuron adPN' FBbt:00100368, so that should be (I think) a synonym.

Yes, and I will add lAL synonym for lPN class too.
