### ISSUE TITLE
neuroblast FBbt:00005146 cross-ref to CL:0000031 neuroblast (sensu Vertebrata)

### ISSUE THREAD

**Issue by hattrill** [FlyBase/drosophila-anatomy-developmental-ontology#1212]
neuroblast FBbt:00005146 has a cross-ref to CL:0000031 'neuroblast (sensu Vertebrata)'.

Think that it should be mapped to neuroblast (sensu Nematoda and Protostomia) CL:0000338 instead.

**Comment by gouttegd** [comment]
That would be part of my work on the mappings between FBbt and CL, so I'll take care of it.

**Comment by hattrill** [comment]
Ace! I may have some GO re-homing question for you tomorrow!
