### ISSUE TITLE
Under-defined terms for larval sensory organ precursors 

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1224]
We have a bunch of terms under `sensory mother cell` that are completely lacking any definition and references:

* `lateral abdominal {bd1,ch,da,es}`
* `lateral thoracic {da,es}`
* `ventral abdominal {bd1,ch,da,es,td}`
* `ventral thoracic {ch1,da,es}`

The grouping terms for the clusters to which those cells belong, under `peripheral nervous system precursor cluster`, are lacking definition and references as well.

**Comment by gouttegd** [comment]
After investigation, here is the extent of the issue and the proposed resolution path.

# Terms under _sensory mother cell_

There are many terms under _sensory mother cell_ that are completely undefined, have unclear labels, and no associated references. They were seemingly intended to represent the embryonic precursors to the larval sense organs that are defined elsewhere in the ontology.

The main offenders are:

* _ventral abdominal bd1_
* _ventral abdominal ch_, and its subclasses _ventral abdominal ch{1..3}_
* _ventral abdominal da_, and its subclasses _ventral abdominal da{1..7}_
* _ventral abdominal es_, and its subclasses _ventral abdominal es{1..6}_
* _ventral abdominal td_, and its subclasses _ventral abdominal td{1,2}_
* similar terms for the lateral abdominal clusters of sense organs (e.g., _lateral abdominal bd1_, _lateral abdominal ch_ and subclasses, etc.)
* similar terms for the abdominal and lateral clusters of the thoracic segments (e.g., _ventral thoracic da_, _lateral thoracic es_, etc.)

The nomenclature used comes from several papers from the 1980s, especially Ghysen et al. (1986; FBrf0045361) and Bodmer & Jan (1987; FBrf0047289), that described the neurons innervating the larval sense organs:

* “es neurons”: neurons with long dendrites reaching the surface to innervate **E**xternal **S**ense organs;
* “ch neurons”: neurons with short dendrites that remain subepidermal and innervate **CH**ordotonal organs;
* multi-dendritic neurons, which are divided in 3 categories:
  * “da” neurons: neurons with elaborate **D**endritic **A**rborisations;
  * “bd” neurons: neurons with **B**ipolar **D**endrites;
  * “td” neurons: neurons with **T**rachea-associated **D**endrites.

Almost none of the “numbered” terms (“da1”, “ch3”, and so on) have been used in curation records. They seem to have been created pre-emptively under the assumption that for each differentiated larval sensory neuron (which are described elsewhere in the ontology), there must have been a corresponding unique precursor cell. But that assumption is not necessarily true: for example, Brewster and Bodmer (1995, FBrf0083795) reported that a subset of the multidendritic neurons seem to derive from the same precursor cells as the “es” neurons, and another subset seem to derive from the same precursor cells as the “ch” neurons.

Additionally, we already have three terms to represent the generic precursors for the main types of sensory neurons involved here:

* _chordotonal organ precursor cell_ (generic precursor for the “ch” neurons);
* _external sensory organ precursor cell_ (generic precursor for the “es” neurons);
* _multidendritic sensory organ precursor cell_ (generic precursor for the “da”/“bd”/“td” neurons).

(Unfortunately those are also undefined, but we can add proper definitions to them.)

I propose the following:

1) Obsolete almost all the “numbered” terms above, except the handful that have been used in curation (see last section below for what to do with those).

2) Re-classify the “unnumbered” terms to make them subclasses of the most appropriate generic precursor type and belonging to the appropriate sensory cluster.

For example, make _ventral abdominal ch_ a subclass of _chordotonal organ precursor cell_ that is part of _ventral abdominal cluster_. Likewise for all the similar terms. Of course, while doing so, we give them better names (making clear that they refer to _precursor cells_, not terminally differentiated neurons) as well as proper definitions.

This would involve creating three new subclasses of _multidendritic sensory organ precursor cell_, one for each subtypes of multidendritic sensory neurons, so that we can classify e.g. _ventral abdominal da_ and _ventral abdominal td_ accurately.


# Terms under _peripheral nervous system precursor cluster_

The term _peripheral nervous system precursor cluster_ is completely undefined. It has the following children, all also undefined:

* _dorsal abdominal cluster_
* _dorsal thoracic cluster_
* _lateral abdominal cluster_
* _lateral thoracic cluster_
* _ventral abdominal cluster_
* _ventral thoracic cluster_

These terms were likely intended to represent the embryonic precursors of what will later become the larval sensory clusters (which are properly defined elsewhere in the ontology).

They need proper definitions, and should also be renamed to make it apparent that they are embryonic precursors to the sensory clusters, and not the final sensory clusters themselves (something like _embryonic dorsal abdominal sensory cluster precursor_).

The real problem, however, lies with the terms further down in the hierarchy. For example, _dorsal abdominal cluster_ has the following descendants:

* _dorsal abdominal da_
  * _dorsal abdominal da1_
  * _dorsal abdominal da2_
  * _dorsal abdominal da3_
  * _dorsal abdominal da4_
  * _dorsal abdominal da5_
* _dorsal abdominal es_
  * _dorsal abdominal es1_
  * _dorsal abdominal es2_
  * _dorsal abdominal es3_
  * _dorsal abdominal es4_
  * _dorsal abdominal es5_
  * _dorsal abdominal ch1_

Again, all those terms are undefined, and here they are also probably mis-classified. _dorsal abdominal da1_ was likely intended to represent the da1 neuron itself (or rather its precursor), not a cluster – there is no such thing as a “da1 cluster”.

Since those terms should really have been under _sensory mother cell_ along with the terms mentioned in the previous section, I propose for them the same treatment, that is:

3) Obsolete all the “numbered” terms (excepted again the handful of those that have been used in curation).

4) Re-classify, rename, and define the “unnumbered” terms. For example, make _dorsal abdominal es_ a _external sensory organ precursor cell_ that is part of a _dorsal abdominal cluster_, and so on.


# Use in curation records

A handful of the “numbered” terms mentioned above have been used in curation records:

* _lateral abdominal bd1_
* _lateral thoracic td1_
* _lateral abdominal td1_

All three terms have been used to annotate FBti0001772, based on data from FBrf0047244.

* _dorsal thoracic bd1_

This has been used to annotate FBgn0004394 and FBgn0085424, based on data from FBrf0054628 (which mentions “bd cells of dorsal cluster of T2 and T3”).

So instead of obsoleting these terms (along with the other, unused “numbered” terms), I propose to simply rename, re-classify, and properly define them, similarly to what is proposed above for the “unnumbered” terms.

**Comment by Clare72** [comment]
>Therefore I propose that this term be merged with muscle cell of dorsal acute muscle 1.

This is not a good idea, since the curation is a one-off misuse of "dorsal abdominal da1" and the concepts that the two terms are intended to represent are not the same.
A disambiguation can be provided as a comment when you do the obsoletion and curation can be changed either by proforma or by bulk retrofit at the time of the FBbt update in FlyBase.

**Comment by gouttegd** [comment]
> A disambiguation can be provided as a comment when you do the obsoletion and curation can be changed […] by bulk retrofit at the time of the FBbt update in FlyBase.

That’s what I had in mind. Obsoleting the bogus term in FBbt and retrofitting the correct term in the record – similar to what happens when we merge terms.

Contrary to a real merge though, in this case the obsoleted term _dorsal abdominal da1_ would not carry a `replaced_by` annotation pointing to _muscle cell of dorsal acute muscle 1_, and that term would not carry a _dorsal abdominal da1_ synonym. So indeed calling that a “merge“ was misleading, sorry about that.
