### ISSUE TITLE
URGENT!! Gut tree structure is super-hard to use

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#124]
adult midgut region FBbt:00110888 has is_a relationship to gut section FBbt:00100315 which has is_a relationship to organ system subdivision FBbt:00007330

It has is_a children of the various adult midgut regions Rx

adult midgut region FBbt:00110888 has part_of relationship to adult gut FBbt:00007513, but NOT to adult midgut FBbt:00003138. It has NO part_of children.

There's a huge multi-lab high-throughput expression project that we'd really like to use valid FBbt terms. These users would be using both the adult midgut regions Rx terms, and terms such as enteroblast FBbt:00110205 (part_of adult midgut). 

We're concerned that if these users have to be, effectively, super-expert users of the Vocabularies tool to figure out that adult midgut region is not ontologically part_of adult midgut, and that they need to be a different relationship hierarchy (I find it highly non-intuitive that midgut regions aren't part-of the midgut!). Is there some way to make the adult midgut regions part_of the adult midgut?

**Comment by SianGramates** [comment]
Lynn points out that the is_a children of midgut constriction FBbt:00000457  and adult midgut constriction FBbt:00110913 have the same issue: they're not part_of midgut or adult midgut, respectively.

**Comment by dosumis** [comment]
Adult partonomy now looks good:

![image](https://user-images.githubusercontent.com/112839/39463754-89347016-4d11-11e8-8b70-2f2c8ecaa4b9.png)

![image](https://user-images.githubusercontent.com/112839/39463789-c788ae7c-4d11-11e8-95a8-76c83138fb20.png)

But generic & embryonic/larval gut terms are still a bit messy -  should be harmonised with adult as far as possible.

We should look at possibilities for using logical defs to align.

(It may be worth turning this into an epic and making subtickets to track fixing.)

**Comment by dosumis** [comment]
(Screenshots in previous post may be a little our of date - will fix).
