### ISSUE TITLE
New subtype of photoreceptor cell

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#125]
FBrf0235590 -  the authors show that Rh7, a previously uncharacterized rhodopsin, is expressed in a subset of period expressing pacemaker neurons (l-LNv & s-LNv Pdf neurons) where it functions in a light sensing pathway as well as a cluster of neurons in the vincinity of an existing set of pacemaker neurons (DN1).

Rh7 is absent from previously described photoreceptor cells. 

Should there be a subclass of central brain photoreceptor cells distinct from those in the eye/eyelet? 
Update the definitions of l-LNv & s-LNv Pdf neurons to include that they're also photoreceptor cells?

**Comment by Clare72** [comment]
With the LNv Pdf neurons, there are only three direct subclasses of photoreceptor cell - LNv Pdf, Bolwig organ (larva), and rhabdomeric (eye). I don't think it makes sense to give each one its own superclass.
I am updating info for the LNvs, but the other cluster are not positively identified as Cry -ve DN1 cells and aren't characterised in the paper, so I don't think I can include that info at this time.
