### ISSUE TITLE
Update definition: aDT-h neuron, aSG5/6 & new term for a new type of fru neuron

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#127]
From FBrf0224741

adult fruitless aDT-h neuron: authors show that in males projections from these neurons branch into the region proximal to the esophagus and dorsal to the tritocerebrum and continue to the superior medial protocerebrum.

adult fruitless aSG5 & aSG6 neurons: authors show that in males some of these arborize to the adult subesophageal zone with a collateral branching into a region, formerly known as the inferior lateral protocerebrum, encompassing part of the superior clamp and the superior lateral protocerebrum.

Authors also describe two new clusters of Fru neurons - mSG & pSG appear new and do not correspond to existing pSG1 or pSG2 populations (Fig 3).

**Comment by Clare72** [comment]
aDT-h (=aDT6) circuit info and staining is in FBrf0211884 (Yu et al., 2010 - ref 13 in FBrf0224741), so have added this to aDT-h class.

They authors don't seem too confident about which previously defined aSG class their aSG neurons belong to. I was thinking I might make a general aSG class including this info as part of the description, saying that it most likely describes aSG5/6:
>Most aSG>4-57 GFP cells bodies in the SOG had no detectable projections (Figure 4C, arrowheads), but a single aSG>4-57 neuron was seen, in two brains, with extensive arbors throughout the SOG with a collateral ramifying the inferior lateral protocerebrum (Supplemental Figure 1S, arrowhead, asterisks)

Or I could make a class for this single neuron (although I would not be sure what to call it) with a comment that it probably either belongs to aSG5 or 6.

mSG I can make a new class (no pre-existing mSG classes)
'pSG' is a bit more awkward as it should not appear to be a general class for all pSGs and they don't give it a number. They also don't specify that it is different from pSG-a,b,c,d,e, just that it is different from pSG1/2. Should I call it pSG3?

There is also lots of fru neuron circuitry info in FBrf0211884 that doesn't seem to be in the onlology (I think all the neurons are in). Shall I make a ticket to add this?
@dosumis @ah963

**Comment by ah963** [comment]
I have some notes somewhere on fru neuron clusters that I made when I was trying to work them all out. remind me to dig them out, pretty sure it's got a list of discrepancies in describing clusters between papers.

**Comment by Clare72** [comment]
Thanks! I think that would be useful.

**Comment by Clare72** [comment]
aDT-h updated
comment added to aSG5 about the branch to the inferior lateral protocerebrum (they imply that they think it is this one in the discussion)
mSG added
pSG added as pSG3
ticket made for FBrf0211884
