### ISSUE TITLE
"Peripheral glial cell"

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1274]
Two possible issues with the term `peripheral glial cell` (FBbt:00001327):

* Its label seems to suggest it refers to any glial cell of the peripheral nervous system, which is _not_ the case: its definition refers to a particular type of glial cells found in nerves. The term referring to any glial cell of the peripheral nervous system is `PNS glial cell` (FBbt:00001320), of which `peripheral glial cell` is a subclass. The label should be amended to more correctly indicate this is a specialised cell type and reduce the risk of this term being used where `PNS glial cell` should be used instead (as is likely to have happened in the annotations of the Fly Cell Atlas data).
* It may be related to `adult wrapping glial cell` (FBbt:00051074) and its embryonic/larval counterpart `embryonic/larval wrapping glial cell` (FBbt:00110171), which have similar (though not identical) definitions. Need to check the exact relations and differences between these terms and adjust the classification if appropriate.

**Comment by gouttegd** [comment]
It seems that the term `peripheral glial cell` is only ever used in the literature to refer to _embryonic_ peripheral glial cells, which are the cells that will later (starting from the larval stages) give rise to the three main subtypes of glial cells of the PNS (perineurial, subperineurial, and wrapping glial cells). The fact that the child terms of `peripheral glial cell` are all embryonic terms tends to confirm it. See Hilchen et al., 2008 (FBrf0204826); Hartenstein, 2011 (FBrf0214261); and especially Yildirim et al., 2019 (FBrf0241021).

Two possible actions here:

A) Rename `peripheral glial cell` to `embryonic peripheral glial cell`, to make it clear that the term refers to embryonic cells only and is _not_ a stage-neutral term for “glial cell of the PNS” (that’s `PNS glial cell`). Classify it under `embryonic/larval glial cell` and update the definition to explain they are the precursors to the larval and adult PNS glial cells.

B) Alternatively, we could make `peripheral glial cell` the stage-neutral form of `adult wrapping glial cell` and `embryonic/larval wrapping glial cell` (so maybe renaming it to `wrapping glial cell`). This fits the current textual definition of the term (which states that these cells ensheath the neurites and are not part of the perineurial and subperineurial layers). But then we would need to re-classify all the child terms `embryonic peripheral glial cell X`, which are _not_ wrapping glial cells; this would probably require a new term to group these.

Side issue: we also have the terms `exit glial cell` and `embryonic exit glial cell`. It seems that all exit glial cells are embryonic (which makes sense since they are a subtype of the peripheral glial cells), so those two terms can be merged.

**Comment by Clare72** [comment]
Many of these papers are about embryonic development, so it is the scope of the paper that restricts usage to the embryo. In Hartenstein (2011), 'peripheral glial cells' is used to refer to other stages (like our 'PNS glial cell' term). Also, there is one record where 'peripheral glial cell' is associated with 'larval stage' in curation. I don't think the ontology structure is sufficient evidence to restrict this to embryonic (as in suggestion A).

I would also be reluctant to go with (B) as this definition is really at odds with the way the term is used in the literature. I think perhaps the part of the definition saying "Glial cell in a nerve that is directly associated with its neurites and is not part of subperineurial layer that wraps the nerve" may be based on embryonic morphology, where the subperineurial layer doesn't exist yet(?) I also think it unlikely that all curation using 'peripheral glial cell' is for wrapping glia - so this path would require all the curation to be checked.

The safest thing to do is probably to obsolete this term and replace its usage with 'PNS glial cell', this seems to be the best match to usage in the literature and none of the existing annotations will become incorrect. Then new terms could be created with the definitions suggested in (A) and (B).

**Comment by Clare72** [comment]
From Hartenstein (2011):
>All three types of peripheral glial cells are large and low in number. Thus, a segmental nerve of the larval ventral nerve cord is accompanied by only 12 peripheral glial cells (von Hilchen et al.,2008). Numbers for adult nerves have not been established so far, but will most likely not exceed those in the larva.

**Comment by gouttegd** [comment]
> The safest thing to do is probably to obsolete this term and replace its usage with 'PNS glial cell', this seems to be the best match to usage in the literature and none of the existing annotations will become incorrect. Then new terms could be created with the definitions suggested in (A) and (B).

Got it.

Though I am not sure we actually need a new term to group all the `embryonic peripheral glial cell X`. Ten of these 12 cells (ePG 1 to 10) have now been assigned a precise subtype (perineurial, subperineurial, or wrapping) (von Hilchen et al., 2013 [FBrf0222452], Yildirim et al., 2019 [FBrf0241021]), so they can be classified under the corresponding `embryonic/larval PNS (perineurial|subperineurial|wrapping) glial cell`. That leaves only ePG 11 and 12 (whose subtype has not been determined), which can be classified under the generic `embryonic/larval PNS glial cell`.
