### ISSUE TITLE
"cardial cell" vs "adult heart muscle cell"

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1289]
We have the following two terms:

- `cardial cell` (FBbt:00007319), defined as a “contractile cell which forms the inner, contractile tube of the dorsal vessel”;
  - `embryonic/larval cardial cell` (FBbt:00007320), its embryonic/larval-specific form.

Their definitions make them appear like muscle cells, as does the `cardiomyocyte` synonym they carry, but those terms are not related to either `somatic muscle cell` or `visceral muscle cell`. They are also completely unrelated to the hierarchy of terms representing the heart muscles:

- `adult heart muscle cell` (FBbt:00003543)
- `embryonic/larval heart visceral muscle cell` (FBbt:00001036)

If “cardial cell” and “heart muscle cell” are not redundant, then the differences and relations between those terms need to be clarified.

**Comment by Clare72** [comment]
may be related to #17

**Comment by gouttegd** [comment]
`cardial cell` is presently defined in FBbt as a “contractile cell” and an exact synonym of “cardiomyocyte”. However:

* In FBrf0151925 (cited as reference for the “cardiomyocyte” synonym), “cardiac” (incidentally not “cardial”) is used more loosely to refer to all the cells of the inner layer of embryonic/larval tube, by opposition to cells of the outer layer which are the _pericardiac_ cells. With that meaning, the term encompasses not only the contractile cells but also the cells that form the ostia and the intracardial valves.
* More recent literature seems to follow that usage and to consider that, both in the larval and adult hearts, ostial cells and intracardial valve cells are specialised, non-contractile subtypes of cardiomyocytes, the term “contractile cardiomyocyte” being then used to refer specifically to the (largest) fraction of cardiomyocytes that do contract (e.g., FBrf0219200, FBrf0238157).

In addition, it is quite clear, based notably on FBrf0219200, that the `adult heart circular muscle cell`, currently defined in FBbt as “muscle cell of the circular muscle of the adult heart that makes up the wall of the heart”, are in fact the contractile cardiomyocytes referred above (and likewise for the `larval heart circular muscle cell`, in larvae).

Therefore I propose:

* Keep `cardial cell` (including its exact “cardiomyocyte” synonym), but enlarge its definition so that it refers to any cells making up the cardial tube and deriving from cardioblasts, whether they are contractile or not.
* Add as subclasses of `cardial cell`:
  * `contractile cardiomyocyte`,
  * `ostial cell`,
  * `intracardial valve cell`.
* Add `adult` and `embryonic/larval` variants of those terms.
  * For the adult form of `contractile cardiomyocyte`, no need for a new term, we just have to re-classify `adult heart circular muscle cell`.
  * Likewise for the larval form with `larval heart circular muscle cell`.
