### ISSUE TITLE
Problems with OBO release files

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#129]
The relations in the OBO release files are getting mangled - at least when converted to OWL.  See multiple part_of relationships here:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/26765505/32499733-4ef9a3f0-c3cb-11e7-86ec-3201481d6917.png">

Some of the incorrect ones are being used, e.g.: 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/26765505/32499796-782622b2-c3cb-11e7-9f92-5027c8c4ab11.png">

**Comment by dosumis** [comment]
Can't replicate this!  Not clear what files we were looking at.  Have tried with:

src/ontologies/fbbt-edit.obo
releases/fbbt-simple.owl
releases/fbbt-simple.obo

**Comment by dosumis** [comment]
We plan to switch to new release architecture soon (OBO standard, rather than the current bespoke system).  This should fix any remaining issues.
