### ISSUE TITLE
Add tracts to TAG from Powers 1948 as documented in the TAG meeting doc [sf#13]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#13]
@dosumis 
**Reported by djs93 on 2013-08-02 17:07 UTC**
A tracts to TAG from Powers 1948 as documented in the TAG meeting doc

**Comment by mmc46** [comment]
This is awaiting publication of a paper on TAG nomenclature.

**Comment by Clare72** [comment]
Not sure what 'TAG meeting doc' refers to, but Power (1948) tracts are in the ontology. Some nomenclature may be revised when final version of Court et al. (2020) is published (will have its own ticket).

Closing this for now.
