### ISSUE TITLE
embryonic/larval central nervous system 

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#130]
_From @dosumis on November 7, 2017 16:14_

should be part_of larval VNC

_Copied from original issue: geneontology/go-ontology#14520_

**Comment by dosumis** [comment]
Sorry - wrong tracker.  Will move.

**Comment by SianGramates** [comment]
Shouldn't it be in the opposite direction? i.e., larval VNC part_of embryonic/larval central nervous system?
