### ISSUE TITLE
'optic lobe tangential neuron' is not classified as an 'interneuron'

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1308]
`optic lobe tangential neuron` (`FBbt:00007579`) is textually defined as an “*interneuron* that is oriented perpendicular to the columns of adult optic lobe neuropils and has a major projection along the plane of a layer of optic lobe neuropil”, but is not classified as an `interneuron` (`FBbt:00005125`), either directly or indirectly.

Any reason why it should _not_ be classified as `interneuron`? Or is it a mere oversight?

**Comment by Clare72** [comment]
Yeah, should be 'interneuron' - I think there are a lot of cases like this where classification that needs to be asserted manually is missing, one reason that logical definitions are a good idea. I don't think thre is a good way to logically define 'interneuron', as it needs to exclude sensory neurons that are part of the CNS.

**Comment by gouttegd** [comment]
OK, I’ll fix that one and check if there are similar instances of unclassified interneurons.
