### ISSUE TITLE
New Term Request: Thermosensory neurons- Anterior Cold Cell, TPN1/2

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1353]
For new term requests, please provide the following information:

thermosensory and second-order thermosensory neurons from FBrf0246007

1:

## Preferred term label

Anterior Cold Cell

## Synonyms

ACc

## Textual definition

an unusual cell type that expresses the broad sensory co-receptor IR25a and that resides on the surface of the antennal nerve (note that the terminals of this cell type within the PAL are clearly visible after external ablation of the antenna, i.e., as a result of degeneration of antennal afferents; Figures 3G and 3H). The location of this cell is similar to that of the previously described “anterior cell” neurons [12], and we therefore refer to it as the anterior cold cell (ACc) (Figure 3H, inset; see Figure S2 for further characterization of this unusual sensory neuron).

Not too sure on how this relates to the anterior cells FBrf0205189 AC thermosensory neuron

2:

## Preferred term label

thermosensory projection neuron 1/2

## Synonyms

tpn-I/tpn-II

## Textual definition

we focused on two cold-activated TPN cell types previously described as fast and slow adapting (TPN-I and II in Figure 1A, identified by expression of the drivers VT19428 and R60H12, respectively)

previous description does not use these names and previous curation uses 'thermosensory projection neuron of transverse antennal lobe t5ALT tract' for R60H12 (TPN-II) and nothing specific for VT19428 (TPN-I).

May not be enough morphological info here. Could just use adult thermosensory projeciton neuron | subset.

**Comment by Clare72** [comment]
Pretty sure ACc is the 'non-aristal sensory neuron VP3' - FBbt:00049720 = 'VP3RNb' in Marin et al. (2020) supplement
Their sacculus chamber I neuron is almost certainly the Ir21a VP1l neuron - FBbt:00111336 (maybe you worked this out already)
TPN-I is VP3 t10ALT - FBbt:00111338 (aka 'fast-adapting cold cell')
TPN-II is the VP3 vPN - FBbt:00111337 (aka 'slow-cool PN'), described to recieve most of its input from VP3RNb (=ACc) in Marin et al. (2020) (tract referred to as t10ALT in hemibrain data and Bates et al. (2020), but used to be assigned to t5ALT)
