### ISSUE TITLE
`synapsed_to` should not be restricted to FBbt’s `neuron`

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1356]
`synapsed_to` (RO:0002120) is defined in RO as having a domain restriction to CL’s `neuron` (CL:0000540) (or to a `part of` a CL‘s neuron):

```
ObjectPropertyDomain(obo:RO_0002120 ObjectUnionOf(obo:CL_0000540 ObjectSomeValuesFrom(obo:BFO_0000050 obo:CL_0000540)))
```

In FBbt (in `components/fbbt_ext.owl`), we are adding a further restriction to FBbt’s `neuron` (FBbt:00005106):

```
ObjectPropertyDomain(obo:RO_0002120 obo:FBbt_00005106)
```

Given that FBbt’s `neuron` is a subclass of CL’s `neuron`, I don’t think this added restriction is useful. And while it does no harm while it says within FBbt, it causes of lot of unsatisfiability when Fbbt and Uberon/CL are merged, because then any neuron term in CL that has a `synapsed_to` relationship is inferred to be a _Drosophila_ neuron, which is obviously wrong.

There’s a similar issue with other relationships too:

* `synapsed_by` (RO:0002103)
* `electrically_synapsed_to` (RO:0002003)

I guess a workaround could be to specifically strip those added restrictions when merging FBbt with Uberon/CL, but I think it would be better if there were not there in the first place. That is, FBbt should use the relationships from RO as they are and not attempt to add its own restrictions to them.

**Comment by Clare72** [comment]
Yeah, I think you can delete these three restrictions, it seems unlikely that we would be relying on them for inference.
