### ISSUE TITLE
Problem with id: FBbt:00002541

### ISSUE THREAD

**Issue by cerivs** [FlyBase/drosophila-anatomy-developmental-ontology#1366]
The new ONTOLOGY_FBBT obo file   contains a loop and this is causing the issue (Term FBbt:00002541 is_a FBbt:00002541).

[Term]
id: FBbt:00002541
name: abdominal ventral multidendritic neuron vdaA
def: "Multidendritic neuron in the ventral sensory cluster of larval abdominal segments 1-7. Based on its dendritic pattern, it is a class I dendritic arborizing neuron. It does not persist into the adult stage (Shimono et al., 2009)." [FlyBase:FBrf0148966, FlyBase:FBrf0209127, FlyBase:FBrf0231611, FlyPNS:PNSdescription.html#vmd4, FlyPNS:PNSnomenclature.html#Swe2002]
subset: cur
synonym: "vdaD" BROAD [FlyPNS:PNSnomenclature.html#Swe2002]
synonym: "vmd4" BROAD [FlyPNS:PNSnomenclature.html#Swe2002]
synonym: "vmd5" BROAD [FlyPNS:PNSnomenclature.html#Swe2002]
xref: VFB:FBbt_00002541
is_a: FBbt:00002541 ! abdominal ventral multidendritic neuron vdaA

**Comment by chris-grove** [comment]
@Clare72  It seems a cyclic logical definition has crept into the ontology:

<img width="882" alt="Screen Shot 2022-01-26 at 9 40 04 PM" src="https://user-images.githubusercontent.com/611382/151282363-7fc31180-e996-47d4-8935-8a62b73e0530.png">
 
Could you take a look? Thanks!
