### ISSUE TITLE
Curate larval MB neurons and connectome from Eichler et al., 2017

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#137]
http://rdcu.be/uSUp

**Comment by dosumis** [comment]
We likely have most of the neurons.  Based on this, we should probably discuss whether curating neuron connectivity at class level likely to be scaleable in future.

**Comment by Clare72** [comment]
See #232

**Comment by Clare72** [comment]
Looks like I duplicated this in #374 
Closing this as other ticket is more detailed and documents progress made so far
