### ISSUE TITLE
Add fbbt-base.owl to the release files

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#1375]
A base file would be very useful for clean integration into downstream resources e.g. ubergraph and application ontologies.  It should be possible to add this by editing the ODK yaml config & updating the ODK.

**Comment by Clare72** [comment]
We already have this:
http://purl.obolibrary.org/obo/fbbt/fbbt-base.owl

**Comment by dosumis** [comment]
Somehow missed that.
