### ISSUE TITLE
Add neuropil domains & somatosensory neurons from 2017 Ito Science paper

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#138]
Ref: 
Tsubouchi, A., Yano, T., Yokoyama, T. K., Murtin, C., Otsuna, H., & Ito, K. (2017). Topological and modality-specific representation of somatosensory information in the fly brain. Science, 358(6363), 615–623. https://doi.org/10.1126/science.aan4428

**Comment by temjones** [comment]
This paper refers to  "leg neuropil", "wing neuropil", "haltere neuropil", and "abdominal neuropil" structures, which I don't think are currently in the ontology (please correct me if I'm mistaken!). I think we should get these in concurrently, elsewise we'll have to go back and add axioms to all of the neurons I'll add for this paper. @Robbie1977 , David OS said you would be a good person to ask about these structures!

**Comment by dosumis** [comment]
Need to request more painted domains and template from Kei.  (should not be a dependency for this ticket).

**Comment by Robbie1977** [comment]
See ticket https://github.com/VirtualFlyBrain/Management/issues/70 
[I can't add as blocker on this repo]

**Comment by dosumis** [comment]
@Clare72  to work on domains first - assuming there is sufficient information in this paper to add them.

**Comment by dosumis** [comment]
Related paper - still in preprint https://www.biorxiv.org/content/biorxiv/early/2017/12/11/231696.full.pdf (probably a bit project).

**Comment by Clare72** [comment]
Do we need a ticket to do something about the 'tectulum' discrepancy? Maybe making 'upper tectulum' to represent the region in the preprint and giving the new upper and lower tectulum regions part_of or overlaps relationships to the traditional tectulum region?

**Comment by Robbie1977** [comment]
Yea might be an idea and allocate to me as I'll actually check the overlaps and maybe see what David Sheperd and Hideo want to do with them (originators of both definitions since Max Power isn't with us anymore). Probably won't be a quick one.

**Comment by dosumis** [comment]
What's the status of this?  Are all terms now in FBbt?

**Comment by Clare72** [comment]
Neuropil regions went in
Need to check neurons - probably some synonyms and some new.

**Comment by Clare72** [comment]
Main classes are now all in master branch.
I did not add the subclasses ending with numbers as it was not really clear how they were different from each other/similar within the class other than reporter expression.

Examples of secondary neurons ('2N' in name) in the paper are all putative - connectivity to primary sensory neurons ('1N' in name) is not shown directly (e.g. by EM or GRASP), do we have a way of annotating something as a putative member of a class in VFB?

**Comment by dosumis** [comment]
> do we have a way of annotating something as a putative member of a class in VFB?

Looks like you should be able to automate classification of secondary neurons.  Seems clear that all of these types of neuron almost exist.  Making EC defs and then annotating subClassOf axioms on specific classes would => mostly cleanly traceable and flexible classification.  (Failing that, including evidence in  comments).

**Comment by Clare72** [comment]
I think we are talking slightly at cross purposes - I meant for annotating the images themselves e.g.

image name: leg external sensilla neurons Les2N2_NP3375
depicts: FBbt:00048308 'leg mechanosensory bristle secondary interneuron'
putative: true

I don't think I really want to make a 'Les2N2' subclass, since it might not actually connect directly and it would be more hassle than it is worth to move and rename it later.

Also I didn't make EC defs for the secondary neurons. I would want to say:

'leg mechanosensory bristle secondary interneuron' == 'adult sensory system ascending secondary interneuron' that (synapsed_by some 'leg mechanosensory bristle mechanosensory neuron' IN some 'leg neuropil')

But we don't have an IN (and this actually still might not be quite good enough)
It is possible that other types of secondary interneuron may be modulated by input from leg mechanosensory neurons in other places (some sensory neurons reach the brain), but this should not make them subclasses of 'leg mechanosensory bristle secondary interneuron'

**Comment by Clare72** [comment]
Maybe 'putative' is not the right annotation, but that is how they phrase it in the paper.
Or maybe the 'putative' annotation should be on the depicts annotation?

**Comment by dosumis** [comment]
Think you're right about adding subclasses (at least for now).

> 'interneuron' that (synapsed_by some 'leg mechanosensory bristle mechanosensory neuron' IN some 'leg neuropil')

Yeh, not possible as this is would be a ternary relationship, which is outiside of OWL-DL.  

We can  clearly define secondary interneurons in sensory pathways:
`interneuron that (synapsed_by some 'leg mechanosensory bristle mechanosensory neuron')
and (capable_of_part_of some 'sensory perception of mechanical stimulus')`

It might be safe to extend these to define ascending and descending by recording where pre vs post-synaptic terminals are (+ soma loc?).

It is possible to infer classification of individuals as well, so we could keep classification dynamic and add comments about evidence to the edges.  e.g. evidence for sensory role might come from e-phys or GCAMP & indirect evidence for direct synaptic connection might come from timing of ephys response.

Alternatively, we could assert classification and add a comment to the classification edge detailing all supporting evidence.

**Comment by Clare72** [comment]
>We can clearly define secondary interneurons in sensory pathways:
interneuron that (synapsed_by some 'leg mechanosensory bristle mechanosensory neuron') and (capable_of_part_of some 'sensory perception of mechanical stimulus')

I think that depends on how you think of the secondary neuron classes.
Would you define a neuron that receives input from a 'leg mechanosensory bristle mechanosensory neuron' in the leg neuropil and some modulatory input from a 'sensory neuron of wing campaniformium' in the brain as a 'wing sensillum campaniformium secondary interneuron' as well as a 'leg mechanosensory bristle secondary interneuron'?

Or do you mean more generally:
'sensory system secondary interneuron' == interneuron that (synapsed_by some 'sensory neuron') and (capable_of_part_of some 'sensory perception')
and subclasses for each modality - would these be different from projection neurons?

**Comment by Clare72** [comment]
Closing this as I don't think there is any more ontology work to do for now
Perhaps make a new ticket if we need sensory secondary interneurons with logical defininitions
