### ISSUE TITLE
Update larval neuropil nomenclature

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#139]
@fewtrem and others have been working on a new nomenclature for larval neuropils and tracts (@fewtrem -  is there also a draft paper to refer to?) There's still quite a bit of work to do to map these to existing or new FBbt term.  Here's the mapping table so far:

https://github.com/VirtualFlyBrain/DrosLarvalDomains/blob/master/refData/IndexKey.tsv

I think this will need an ongoing discussion between FBbt editor and @fewtrem

**Comment by fewtrem** [comment]
Yep there is a draft paper indeed and it will be added as soon as I get approval from collaborators - at least the volume definitions I expect within a week or so.

**Comment by Robbie1977** [comment]
What we have:

255 neuropils.  
In VNC these are divided (per segment) into 
centrolateral (L/R)
ventrolateral (L/R)
dorsolateral (L/R)
centromedial (L/R)
ventromedial (L/R)
dorsomedial (L/R)
central (L/R)

General terms to make:
centrolateral etc - segment independent.

~200 "lineage" tracts
We have 

![image](https://user-images.githubusercontent.com/4630768/35216276-0a289360-ff5f-11e7-829e-c95706c0d91a.png)

Tracts from David & Volker still need to be posted as TSV.

**Comment by dosumis** [comment]
Implementation going on here: #150

**Comment by dosumis** [comment]
@fewtrem Please can you add definitions for these domains here:

Leg neuropils:
Abdominal segment 9 domains:
tritocerebrum domains
Remaining missing adult neuropils:
Superior Inferior Protocerebrum	SIP
Noduli Primoridum	prNO
Posterior Lateral Protocerebrum	PLP
Ventro Medial Cerebrum posterior	VMCp
Ventro Medial Cerebrum anterior	VMCa

**Comment by dosumis** [comment]
(DOS note to self: Doc with defs sent on Slack)

**Comment by fewtrem** [comment]
[Compartment definitions for VFB.pdf](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/files/1693007/Compartment.definitions.for.VFB.pdf) (ignore the colour coding, for my reference)

Attached definitions for the following to be added / updated in FlyBase.  Note their are also extra references required.  If possible please add a placeholder for my paper from which they are taken.

These took a while to agree one so should not be changed much / if at all but comments welcome.

Tick when added:
- [ ] CL
- [ ] CR
- [ ] IPp
- [ ] SLP
- [ ] SMPa
- [ ] SMPp
- [ ] SMP
- [ ] SIP
- [ ] AL
- [ ] LAL
- [ ] PLP
- [ ] VLP
- [ ] VMCa
- [ ] VMCp
- [ ] VMC
- [ ] prAOTU
- [ ] prFB
- [ ] prNO
- [ ] PB
- [ ] Leg Domains

Please can a link to the entries be pasted once these are in so I can check them, and also for the VNC regions so I can write the A9 and tritocerebrum definitions to be consistent with them.

Thanks

**Comment by dosumis** [comment]
@fewtrem: Doc seems to lack A9 domain refs.  (IN tsv you have:
93	Abdominal Segment 9 dorsal Left	A9d L
94	Abdominal Segment 9 dorsal Right	A9d R
)

  Could you share defs for these?

**Comment by fewtrem** [comment]
I think we have all we need for now(?)
Two things that I would like to know:
- [ ] What are we doing regarding splitting into right & left as I notice the defs do not do that - what will actually display on the description? (@dosumis)
- [ ] Is the standard to not capitalise synaptic neuropil in the descriptions e.g. "ventro lateral protocerebrum (VLP)" not "Ventro Lateral Protocerebrum (VLP)".  Does it matter? (@dosumis)
- [ ] Please review my edits to the PLP/VMCa/VMCp for style.  I can (later in March) add in definitions for these that will match the missing ones above.

Merging them will not be that difficult since there is not much in the definitions yet.

**Comment by dosumis** [comment]
- [x] What are we doing regarding splitting into right & left as I notice the defs do not do that - what will actually display on the description? (@dosumis)
 - Only making general classes in the ontology right now (one class, 2 instance per organism, one left and one right).  Could add something to def to make clear that bilaterally symmetric pair per organism, but perhaps this is overkill? Have kept domain images separate though.  Can revisit as part of general review of how we cope with laterality.
- [x] Is the standard to not capitalise synaptic neuropil in the descriptions e.g. "ventro lateral protocerebrum (VLP)" not "Ventro Lateral Protocerebrum (VLP)".  Does it matter? (@dosumis)
Yep

**Comment by fewtrem** [comment]
OK - that's great with the right/left, thanks.
I will uncapitalise in future definitions then.
