### ISSUE TITLE
New anatomy term for cool sensing neurons in dorsal organ

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#140]
FBrf0227329 identifies a trio of cool sensing neurons in the larva.
FBrf0232228 & FBrf0233685 identify these as sensing via Ir21a with Ir25a and call them 'Dorsal Organ Cool Cells (DOCC)' (not a term used in the original paper - but there are shared authors).

Would a larval version of the term 'adult olfactory receptor neuron Ir21a' be appropriate?

**Comment by dosumis** [comment]
Note - to do this properly may require a GO term request for detection cool stimulus or something similar.
