### ISSUE TITLE
New anatomy term: inter-ommatidial bristle precursor

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#141]
The definition of 'inter-ommatidial precursor cell' refers to 'inter-ommatidial bristle precursors' (see below), but this term is not in the ontology (and should be). Interommatidial bristle is the corresponding adult term. 

_*Precursor of the inter-ommatidial cells (secondary and tertiary pigment cells). From 10 hours after puparium formation (APF), these cells are part of an unstructured pool of undifferentiated cells surrounding each developing ommatidial core. Around 20-23 hours APF, the primary precursors leave this pool and become part of the ommatidia. Following this, the inter-ommatidial precursors and **inter-ommatidial bristle precursors** develop into an organized lattice surrounding the ommatidia._

**Comment by Clare72** [comment]
I couldn't find any mention of inter-ommatidial bristle precursors in the reference for 'inter-ommatidial precursor cell' (FBrf0103328). The class for 'interommatidial bristle has a relationship - develops_from some 'external sensory organ precursor cell'. The precursor cells that form bristles (in general) can be found from here in the ontology. Perhaps there should be subclasses for the cells that develop into interommatidial bristles, but I think this would require another reference.
For now I will edit the definition of 'inter-ommatidial precursor cell' to match FBrf0103328.
