### ISSUE TITLE
Eschbach 2020 FB2/MB2IN neurons.

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1448]
For new term requests, please provide the following information:

Presumably these weren't made with the other neurons from this paper for a reason so this is just to check.

FBrf0245294 - All figure 5

FB2IN-19
FB2IN-11
FB2IN-18
MB2IN-207

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

Happy to check for this if these terms are worth making.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/fbbt)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by Clare72** [comment]
I used a robot template to generate these terms, so they might have been missing from whichever supplemental file I based that on.

**Comment by Clare72** [comment]
Do you mean 'FB2N', rather than 'FB2IN'? I don't see any 'FB2IN's in the paper (and we have the 'FB2N's)

**Comment by admclachlan** [comment]
Yep thanks FB2IN is FB2N, thought FB2N was FB2IN+FB2ON. Then I only can't find is MB2IN-207 then. Figure 6.

**Comment by Clare72** [comment]
Yeah, I will make the term.
