### ISSUE TITLE
Updating oboInOwl:created_by to dcterms:contributor for old terms created by ORCID-less contributors

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1459]
As part of the OBO-wide move from `http://www.geneontology.org/formats/oboInOwl#created_by` to `http://purl.org/dc/terms/contributor`, we want to massively replace all the existing `oboInOwl:created_by` annotations in FBbt (and also in other FlyBase ontologies).

However, many of the existing `oboInOwl:created_by` annotations in FBbt have a value that is _not_ an ORCID URI, and actually not even an URI at all. Instead, they have values that typically correspond to the initials of the FlyBase ontologist who created them, such as `djs93`, `mmc46`, `sr544`, etc. Overall, generalised use of ORCIDs only started a few years ago, so almost all “old” terms have a non-ORCID, non-URI creator.

But the ODK is now enforcing that all `dcterms:contributor` annotations should have an URI-like value (as part of the `iri-range-violation.sparql` standard check), so blindly replacing `oboInOwl:created_by` by `dcterms:contributor` results in a build failure because annotations like `dcterms:contributor mmc46` violate that constraint.

@matentzn You’re the one who is keen to see `oboInOwl:created_by` (along with `oboInOwl:creation_date`) replaced with equivalent DC terms, so your input here would be welcome: How should old, ORCID-less contributors be dealt with?

1) Leave them alone, as `oboInOwl:created_by` annotations; replace `oboInOwl:created_by` by `dcterms:contributor` only when the contributor is represented by an IRI (typically an ORCID URI).

Probably not very satisfying if the goal is to get rid of `oboInOwl:created_by`, as that would leave quite a large number of such annotations.

2) Make sure that all contributors have an ORCID.

I don’t think this is realistically feasible for old contributors that may not even work for FlyBase anymore.

3) Relax the `iri-range-violation.sparql` constraint to exclude `dcterms:contributor` from the list of annotations that _must_ have a IRI value.

If we go that route it should be done at the ODK level.

4) Disable the `iri-range-violation.sparql` check in FBbt.

Doesn’t require any change at the ODK level, but then we lose the benefit of that check entirely, I am not really keen to do that.

5) Create pseudo-URIs to represent old contributors.

For example, transform `mmc46` into something like `http://flybase.org/contributors/mmc46`. This can be done even if said contributor is no longer there (contrary to creating an ORCID). The constructed pseudo-URI would not resolve to anything meaningful, though, contrary to an ORCID. (Unless we ask our web developers to make those URIs point to something on our website, but that seems way overkill to me.)

**Comment by Clare72** [comment]
Does prefixing with "FBC:" stop the check failing?

**Comment by matentzn** [comment]
Great you are looking into this!

I would suggest the following:

1. Try to identify if the person has an ORCID now, and replace if they do. This is what Anita did for Uberon, and maybe she still has the tables for the tag -> orcid mapping
2. If there are not too many left after that, create wikidata entries for these (this is done in 1 minute or less per person)

If 2 is too much work, I would suggest you use dcelements:contributor for all case where the range is a string, and append a prefix "Flybase:mmc24".

Definitely avoid your solutions 3 and 4.

**Comment by Clare72** [comment]
actually there are not that many creators in FBbt:
created_by: camcur
created_by: david
created_by: djs93
created_by: dos
created_by: http://orcid.org/0000-0002-1373-1705
created_by: http://orcid.org/0000-0002-6095-8718
created_by: mmc46
created_by: sr544
created_by: temj2

(from `grep "created_by: " fbbt-edit.obo | sort | uniq > unique_creators.txt`)

**Comment by Clare72** [comment]
temj2 is my direct predecessor, Tamsin Jones - http://orcid.org/0000-0002-0027-0858
mmc46 is Marta Costa - http://orcid.org/0000-0001-5948-3092
I am not sure who sr544 is
@dosumis are you david, djs93 and/or dos?
maybe we could delete camcur? it refers to all FB Cambridge curators, which is a changing group of people, so maybe not a useful attribution

**Comment by gouttegd** [comment]
@Clare72 : No, `FBC:xxx` still violates the constraint. My understanding is that it should be written as `<FBC:xxx>` to be recognised as an IRI, but this doesn’t seem to work in an OBO file.

Thanks for the ORCID above.

@matentzn : Will create Wikidata entries if needed (if we can’t identify remaining contributors).

**Comment by gouttegd** [comment]
According to the [SourceForge pages](https://sourceforge.net/p/obo/_members/) of the OBO Foundry (didn’t know someone was still using SourceForge…):

* `sr544` is Simon Reeve (who is also listed on FlyBase.org as a former member, so it checks out), who doesn’t seem to have an ORCID;
* `djs93` is David Osumi-Sutherland.

That leaves `dos` (one occurence) and `david` (151 occurrences), who probably are David Osumi-Sutherland as well, though I’d like a confirmation.

And I agree about deleting `camcur` (18 occurrences) – if we don’t know _who_ contributed the term exactly, there’s not much point in having a `dcterms:contributor` annotation at all.

**Comment by matentzn** [comment]
For the camcur, I would like to add that we do give credit to groups in a few ontologies, and it is not redundant to do so. You could use wikidata:Q3074571 (https://www.wikidata.org/entity/Q3074571 )

**Comment by dosumis** [comment]
> On 21 Jul 2022, at 13:27, Nico Matentzoglu ***@***.***> wrote:
> 
> 
> For the camcur, I would like to add that we do give credit to groups in a few ontologies, and it is not redundant to do so. You could use wikidata:Q3074571 (https://www.wikidata.org/entity/Q3074571 <https://www.wikidata.org/entity/Q3074571> )
> 

Gillian Millburn was a very major camcur contributor, (for all ontologies but especially FBcv phenotypes) so you might want to ask her if she wants direct credit each time Camcur is used - in addition to the Wikidata FlyBase reference.

**Comment by gouttegd** [comment]
Remaining contributors referenced from within FBbt by their name rather than an identifier:

* Volker Hartenstein: ORCID available: https://orcid.org/0000-0001-9676-7393
* Michael Ashburner: ORCID available: https://orcid.org/0000-0002-6962-2807
* Kei Ito: Assuming this refers to the Kei Ito who authored the 2014 nomenclature paper for insect brain (which seems likely), this should be his ORCID: https://orcid.org/0000-0002-7274-5533
* Simon Reeve: a FlyBase-Cambridge alumnus (according to the authors list of the [2013 FBbt paper](https://jbiomedsem.biomedcentral.com/articles/10.1186/2041-1480-4-32)), but who doesn’t seem to have a semantic ID
* Gary Crumbling: a FlyBase-Indiana alumnus (according to the same paper), but who doesn’t seen to have a semantic ID

**Comment by Clare72** [comment]
orcids look good (yes you have the right Kei Ito)

**Comment by Clare72** [comment]
maybe we could use these for the others:
https://www.researchgate.net/scientific-contributions/Gary-Grumbling-2028777112
https://www.researchgate.net/scientific-contributions/Simon-Reeve-2162827703
