### ISSUE TITLE
Add in lineages for larval VNC

### ISSUE THREAD

**Issue by fewtrem** [FlyBase/drosophila-anatomy-developmental-ontology#148]
**What:** The lineages or "neurite bundles" from the following paper should be added:
https://www.ncbi.nlm.nih.gov/pubmed/15459108

**Motivation:** This is important for defining the synaptic neuropil domains (compartments) in the VNC and, eventually, for classifying neurons to lineages.

**Comment by Clare72** [comment]
commissures were added in #1021 
lineages were added in #750
