### ISSUE TITLE
Curate http xrefs -> standard DB:acccession

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#149]
e.g. 

http://www.normalesup.org/~vorgogoz/FlyPNS/PNSdescription.html#ddaC
-> 
FlyPNS:ddaC

Add to dbxrefs: 

FlyPNS -> http://www.normalesup.org/~vorgogoz/FlyPNS/PNSdescription.html#

**Comment by Clare72** [comment]
done as far as possible
