### ISSUE TITLE
new term: adult male ppk23 neuron

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#1499]
## Preferred term label 
adult male ppk23 neuron

## Textual definition
Note: I'm having trouble telling from the paper whether the cell body of this neuron is in the male prothoracic tarsus and projects to the VNC, or is in the VNC and projects to the tarsus. Male-specific cell, expresses ppk23, involved in detection of female pheromones. These neurons release CCAP. PMid:35263128

## Suggested parent term
is_a male specific neuron FBbt:00048301 (possibly also is_a adult ascending neuron FBbt:00048301)

## Attribution
FBrf0252940

**Comment by Clare72** [comment]
Whilst further researching these ppk23 neurons I found that we have these terms:
>FBbt:00111518 'adult female ppk25 neuron'
exact synonym: 'F cell'
def: "Neuron located in the adult female ventral nerve cord. It arborizes one of the two ppk23-positive cells in each leg chemosensory bristle (the ppk25 positive one) from the three leg neuromeres. It does not extend into the brain. This neuron is involved in the detection of female pheromones."


>FBbt:00111519 'adult male ppk25 neuron'
exact synonym: 'M cell'
def: "Neuron located in the adult male ventral nerve cord. It arborizes one of the two ppk23-positive cells in each leg chemosensory bristle (the ppk25 positive one) from the three leg neuromeres. It extends into the subesophageal zone in the brain. This neuron is involved in the detection of male pheromones."


The definitions (and labels) of these cell types do not fit what is in the reference (FBrf0230436):
 - Firstly, these cell types both exist in male and female - FBrf0218411 says:
>Cells from males or females showed similar response profiles. Grouping one of the two cells under a bristle as “female sensing” and the other as “male sensing” based on maximal responses revealed a clear segregation of sex-specific responses 

 - Secondly, the M cells do not express ppk25 (this is how authors of FBrf0230436 distinguish M and F cells)
 - Thirdly, the M and F cells are peripheral sensory neurons, so are not located in the VNC

These terms should be obsoleted and remade

**Comment by SianGramates** [comment]
The very terms that led me to make this request!
