### ISSUE TITLE
Miscellaneous new terms from scRNAseq papers

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1501]
New terms for cell types will be needed to annotate a few upcoming scRNAseq datasets

## FBrf0247588
New subclasses of `adult fat cell`:
* `adult abdominal fat cell`
* `adult pericerebral fat cell`
(similar to the already existing `adult pericerebral fat cell`)

## FBrf0251482
* `adult type A central brain neuron`
* `adult type B central brain neuron`
(originally described in FBrf0239740, their nomenclature has been reused in FBrf0251482)

## FBrf0244060
Larval precursors for adult testis cell types:
* `terminal epithelial precursor cell`
* `pigment cell precursor`

**Comment by Clare72** [comment]
>adult type A central brain neuron
adult type B central brain neuron

FBrf0239740 refers to these as 'states' and they are defined solely by gene expression, so probably not appropriate to add to FBbt.

**Comment by gouttegd** [comment]
Larval precursors for adult testis cell types were added in #1520. Since there’s nothing to do for the “adult type (A|B) central brain neurons” of FBrf0251482, this can can closed.
