### ISSUE TITLE
larval protocerebral bridge definition

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#152]
Need to reconcile competing defs.  Each appears to have useful information.  e.g. new def has lineage information and information about tracts and relationships to other domains (compartments) but clear statement of what this domain is part_of and doesn't mention that in two unfused halves.

Would be good to nail down the mix of primordial and differentiated chracteristics:  differentiated vs undifferentiated neurons.

From @fewtrem:

PB: Protocerebral Bridge
Previously included in the CPM compartment.
Formed from the DPMm1 and DPMpm1/2 and CM4 lineages, this small tubular-like primordium is
shaped like a dorsally convex crescent, attached to the posterior surface of the IPp compartment.
Turning anterior-medially, it connects to its contralateral counterpart right posteriorly of the
PLPC(DPLp1) commissure and Fan-shaped Body.
[Pereanu2010 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2905803/]

Current FBbt term:

embryonic/larval protocerebral bridge primordial: "The primordium of the adult protocerebral bridge in the larval brain. It consists of bilaterally symmetrical tubular shaped region containing both differentiated and undifferentiated synapses, in the posterior inferior protocerebrum (IPp or CPM). It curls around the dorsal side from the posterior, growing during the larval period towards the midline. Fusion of the two halves only occurs at 48h after pupariation." [FlyBase:FBrf0210156 = Young, J.M., Armstrong, J.D. (2010)]
SubClassOf: 'synaptic neuropil domain'
SubClassOf: 'primordium
'part of' some 'embryonic/larval posterior inferior protocerebrum'

obsoleted FBbt term:
**larval protocerebral bridge:** Synaptic neuropil domain of the third instar larval brain that is the precursor of the adult protocerebral bridge. Unlike in the adult, this exists as a pair of separate domains that do not join across the midline. Each has an arched shape, and segmentation is only barely discernible."  [FlyBase:FBrf0210156 = Young, J.M., Armstrong, J.D. (2010)]
comment "This term has been obsoleted because it refers to the same structure as 'embryonic/larval protocerebral bridge primordial' (FBbt:00111206) [FBC:MMC]. mc160810"

**Comment by dosumis** [comment]
@fewtrem.  Comments please.

**Comment by fewtrem** [comment]
**embryonic/larval protocerebral bridge primordial**
"The primordium of the adult protocerebral bridge in the larval brain, formed from the DPMm1 and DPMpm1/2 and CM4 lineages.  It consists of bilaterally symmetrical tubular shaped region containing both differentiated and undifferentiated synapses, attached to the posterior surface of the posterior inferior protocerebrum (IPp). It curls around the dorsal side from the posterior, growing during the larval period towards the midline. Fusion of the two halves only occurs at 48h after pupariation, right posteriorly of the PLPC(DPLp1) commissure and Fan-shaped Body." [FlyBase:FBrf0210156 = Young, J.M., Armstrong, J.D. (2010)]
[Pereanu2010 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2905803/]
SubClassOf: 'synaptic neuropil domain'
SubClassOf: 'primordium
'part of' some 'embryonic/larval posterior inferior protocerebrum'
