### ISSUE TITLE
Merge "centromedial neuropil of larval tritocerebrum" &  "embryonic/larval periesophageal neuropils" ?

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#153]
From DW/VH doc on larval neuropils

"The centro-medial tritocerebrum extends alongside the medial part of the anterior Central Brain. This corresponds to the former BCv compartment."

rdfs:label "centromedial neuropil of larval tritocerebrum"@en
has_obo_namespace "fly_anatomy.ontology"^^xsd:string
definition "A centro-medially located synaptic neuropil subdomain in larval tritocerebrum.  The centro-medial tritocerebrum extends alongside the medial part of the anterior central brain."^^xsd:string

Based on  our synonyms, Bcv corresponds to:

rdfs:label "embryonic/larval periesophageal neuropils"^^xsd:string
id "FBbt:00007129"^^xsd:string
has_obo_namespace "fly_anatomy.ontology"^^xsd:string
definition "One of a group of synaptic neuropil domains of the larval brain which are located ventral to the mushroom body and are grouped around the long axon tracts connecting the larval protocerebrum to the ventral nerve cord. This compartment contacts the antennal lobe posteriorly and guides the medial cervical tract (MCT). It is the larval counterpart of the adult periesophageal neuropils."^^xsd:string
rdfs:comment "Note - description of relative location of brain structures in this definition is based on Younossi-Hartenstein et al., 2003 description of the first instar larval brain and Pereanu et al., 2010 third instar larval brain."^^xsd:string
has_exact_synonym "baso-cervical synaptic neuropil domain"^^xsd:string
has_exact_synonym "basocervical compartment"^^xsd:string
has_exact_synonym "Bcv"^^xsd:string
has_narrow_synonym "larval PENP"^^xsd:string
has_narrow_synonym "larval periesophageal neuropils"^^xsd:string
database_cross_reference "VFB:FBbt_00007129"^^xsd:string

CC @fewtrem

**Comment by fewtrem** [comment]
updated to "This protruding part of the CM corresponds to the former BCv compartment." to make it clearer  So please don't merge them, the PENP / BCv is just deprecated.
