### ISSUE TITLE
add parental term 'nephrocyte'

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#155]
There are two kinds of Drosophila nephrocytes : garland cell  FBbt:00005059 and pericardial cell FBbt:00005058. I think there should additionally exist the term 'nephrocyte', and garland cell and pericardial cell should both have an is_a relationship to nephrocyte.

Additionally, there are stage-specific terms: embryonic pericardial cell  FBbt:00005678 and embryonic garland cell  FBbt:00005704 ; embryonic/larval pericardial cell FBbt:00001667 and embryonic/larval garland cell  FBbt:00001693; and adult pericardial cell FBbt:00003184 and adult garland cell FBbt:00003183 (also adult thoracic pericardial cell  FBbt:00013184, which has an existing is_a relationship to adult pericardial cell). The stage-specific terms all have existing is_a relationships to the top level terms garland cell and pericardial cells, so stage-specific versions of 'nephrocyte' may not be strictly necessary.

**Comment by dosumis** [comment]
Hi Sian,  Might it be better to add nephrocyte as synonym to both pericardial and garland cells (pericardial cell already has this synonym?).  If not, can you suggest a definition and reference for the new grouping class?

**Comment by SianGramates** [comment]
I can't tell from this ticket what the resolution of the request was. I'm currently working with the AGR Expression working group on high-level ribbons for expression data, and am trying to figure out whether to offer "Malpighian tubule + nephrocyte" to go in the renal system cell, or if I need to offer "Malpighian tublule + pericardial cell + garland cell" to account for this request being dealt with by adding synonyms rather than the requested parent term.

**Comment by Clare72** [comment]
I added the term 'nephrocyte' with garland and pericardial cells as is_a children.
'nephrocyte' is part_of the excretory and circulatory systems.

**Comment by SianGramates** [comment]
Thanks!
