### ISSUE TITLE
Issue with merging attribution in Jenkins build

### ISSUE THREAD

**Issue by temjones** [FlyBase/drosophila-anatomy-developmental-ontology#156]
I ran into some issues generating the FBbt release last night, and I _think_ the problem is a knock-on effect of merging in the attribution data during the Jenkins build (which @dosumis and I changed at the end of last year). The most annoying problem is that for some reason the ontology files generated by the build are having the date: and data-version: lines 

```
data-version: 2018-02-21
date: 21:02:2018 22:01
```

replaced by

`data-version: releases/2018-02-21`

which doesn't play nice with the release script, because it grabs the data-version: to generate the /releases/ and /tags/ folders. The release script is shared to generate releases for fbbt, fbdv or fbcv, so I don't want to have to change the release script. (I did a quick fix to get the release done last night but I had to manually edit the directory structure in the releases folder afterwards so it's not ideal for long term use).

Another issue with the way the merge works now is that it changes the output files from having a "default-namespace: fly_anatomy.ontology" in the header to having "namespace: fly_anatomy.ontology" in every term. This is a huge drag if we want to check changes with a diff between newly generated release files and previous versions (and I would recommend keeping this checking step in the release SOP). So I manually changed that back in the version of the obo file that I sent to FlyBase. This is annoying for the checking steps but not so much of an issue in terms of what ends up in the release files. 

However, there's a couple of other important things I need to add back to the obo header because they're now lost in the merge. But I'm only adding this info manually to the fbbt-simple.obo aka fly-anatomy.obo file that gets loaded into FlyBase - all the other release files will have lost it. Basically, either way we do the merge, we are having to do significant manual edits to the header because either we lose the attribution data, or we lose the date headings and the remark containing info about imports. Neither of these scenarios are good because it means that the majority of release files are losing important info from the header unless it's manually edited.

**Comment by dosumis** [comment]
Ouch.  Pity we didn't catch this earlier. I guess  the easiest fix is to switch back the merge order to the original one and punt the issue of fixing attribution to the next release.

**Comment by dosumis** [comment]
Note to self - Robot doesn't fix merge order issue, but future releases might: https://github.com/ontodev/robot/issues/287
