### ISSUE TITLE
mapping between FBbt and Uberon/CL for FBbt:00005131 dopaminergic neuron (Drosophila)

### ISSUE THREAD

**Issue by ANiknejad** [FlyBase/drosophila-anatomy-developmental-ontology#1580]
Hi FlyBase team,

I am wondering if FBbt:00005131 (dopaminergic neuron (Drosophila)) can be consider as a xref of 

[Term]
id: CL:0000700
name: dopaminergic neuron
namespace: cell
def: "A neuron that releases dopamine as a neurotransmitter." []
synonym: "dopaminergic cell" EXACT []
xref: BTO:0004032
xref: FMA:84787
xref: WBbt:0006746
is_a: CL:0000151 ! secretory cell
is_a: CL:0000540 ! neuron

Thank you in advance
Best regards,

Anne

**Comment by Clare72** [comment]
Hi Anne, yes this looks like it should be added as an xref - thanks for pointing this out.
