### ISSUE TITLE
Muscles defined as 'muscle cell', and 'sensillum' defined as tissue: something to clarify for single-cell transcriptomics annotation?

### ISSUE THREAD

**Issue by ANiknejad** [FlyBase/drosophila-anatomy-developmental-ontology#1581]
Hi FlyBase team,

there are FBbt terms where definition sounds strange, because the muscle is defined as a cell, but actually that can be the case only for embryo and larva organism, see this paper

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4456285/

'[In embryo and larva] Each muscle is comprised of a single cell; in contrast, adult fly muscles are made up of bundles of fibers, analogous to mammalian muscle.' 

So I am wandering if these classes need a review for definition and relationships (is_a: CL:0000187 ! muscle cell) and developmental constraints:

FBbt:00005073  somatic muscle (Drosophila)
FBbt:00003360  flight muscle (Drosophila)
FBbt:00003361  indirect flight muscle (Drosophila)
FBbt:00003384  basalar muscle (Drosophila)

Thank you in advance for your kind help

Anne

Anne Niknejad
biocurator at bgee.org

**Comment by ANiknejad** [comment]
I add a more general comment here: in the mood of single-cell transcriptomics, it is important to have clear definition of cell or tissue, to allow a precise mapping. I guess, 'sensillum' is maybe also to review: are there sensilla that are unicellular?
see https://pure.mpg.de/rest/items/item_3344698/component/file_3363996/content

**Comment by Clare72** [comment]
Hi Anne,

I think you might be looking at an older version of the ontology, the examples you give have now all been renamed, adding 'cell', to make clear that they refer to single muscle cells (this was always the case based on the hierarchy, but I agree that this was not obvious before). We now have new terms to refer to 'complete' muscles (including all muscle and tendon cells), to which the muscle cell terms are linked via 'part of' relationships.

Regarding 'sensillum', this term in FBbt (and its parent 'cell cluster organ') seems pretty clearly to be defined as a multicellular structure, so a unicellular sensory structure would not be classified as a 'sensillum' in FBbt, but might be a 'sensory neuron' (FBbt:00005124).

**Comment by ANiknejad** [comment]
Hi David, hi Clare,
Thank you for your answers, and sorry being late posting here, yes I am talking about the Uberon composite-metazoan.obo, and this morning I posted an Uberon issue that seems to be related considering David's comments, please see https://github.com/obophenotype/uberon/issues/2782

**Comment by ANiknejad** [comment]
At Bgee, we are now involved in a project with ASAP (https://asap.epfl.ch/ ) focusing on drosophila data,
and Bgee annotations of anatomical structures uses the composite-metazoan.obo file to do ontology mapping. I cc Frederic Bastian @fbastian here to follow the discussion

**Comment by gouttegd** [comment]
FYI, there are several known problems with the `composite-metazoan.obo` product of Uberon (e.g. obophenotype/uberon#2584, obophenotype/uberon#1466, obophenotype/uberon#1813). The pipeline to generate this product is… complicated, and is in great need of a complete overhaul.

**Comment by ANiknejad** [comment]
yes.. issue number 1813 is mine too...

**Comment by Clare72** [comment]
Closing, as I don't think any changes are needed to FBbt.
