### ISSUE TITLE
Expand mushroom body beta' lobe slice 2

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#161]
mushroom body beta' lobe slice 1&2 is divided into three sections (a, m & p) as per the definitions of dopaminergic PAM neuron 4, 13, & 14 & 2, 6 & 5.

New terms for:
mushroom body beta' lobe slice 1a
mushroom body beta' lobe slice 1m
mushroom body beta' lobe slice 1p
mushroom body beta' lobe slice 2a
mushroom body beta' lobe slice 2m
mushroom body beta' lobe slice 2p

**Comment by dosumis** [comment]
Reference?

**Comment by ah963** [comment]
FBrf0227861 - mainly supplemental figures (mostly s3 and supplemental table 1 - note this table isn't wholly represenative of expression data shown in the paper) use beta'2a, beta'2m, beta'2p. I also noticed the definitions of some PAM neurons use these subdivisions of mushroom body beta' lobe slice 2.

**Comment by Clare72** [comment]
see #192

**Comment by Clare72** [comment]
Terms for intersections of slices and layers added (for #192) - need to update relationships of MBEs to match defs
