### ISSUE TITLE
New cell type associated with PAM cluster

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#162]
FBrf0227861 describes a TH negative cell type in the PAM cluster connecting mushroom body gamma lobe slices 1, 2 & 4.

**Comment by dosumis** [comment]
We currently have:

dopaminergic PAM neuron
exact_synonym: PAM cluster neuron

IIRC - The cluster was originally identified by markers of dopaminergic neurons (e.g. TH).  So it's probably best to phrase definition as 'associated with PAM cluster' rather that 'in' it.
