### ISSUE TITLE
New Term Request: SFS

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1637]
For new term requests, please provide the following information:

## Preferred term label

Can't find the full name

## Synonyms

SFS

## Textual definition

FBrf0252547

I'm struggling to find the name for this one, there's some description in the text. Possibly I've missed it.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/fbbt)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by admclachlan** [comment]
Contact the authors?

**Comment by admclachlan** [comment]
Alex to follow up on this.

**Comment by Clare72** [comment]
adding just as 'SFS' for now - label can be updated later (leaving ticket open)

**Comment by admclachlan** [comment]
No luck on finding out what 'SFS' means.
