### ISSUE TITLE
Neuronal “superclasses” for FlyWire

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1641]
An upcoming paper is in need of 9 “superclasses” of neurons that would encompass most if not all neurons in the FlyWire dataset, based on their soma location and the target of their projections:

| Proposed name | Location of soma | Location of axonal projections |
| ------------- | ---------------- | ------------------------------ |
| sensory neuron | periphery | brain |
| ascending neuron | VNC | brain |
| central brain intrinsic neuron | central brain | central brain (axon+dendrites) |
| optic lobe intrinsic neuron | optic lobe | optic lobe (axon+dendrites) |
| visual projection neuron | optic lobe | central brain |
| visual centrifugal neuron | central brain | optic lobe |
| motor neuron | brain | periphery |
| descending neuron | brain | VNC |
| endocrine neuron | brain | ring gland |

Some of those “superclasses” are already exactly covered by existing terms:
* “optic lobe intrinsic neuron” -> [optic lobe intrinsic neuron](http://purl.obolibrary.org/obo/FBbt_00007577);
* “visual projection neuron” -> [visual projection neuron](http://purl.obolibrary.org/obo/FBbt_00048287).

For some others, we have related classes that may or not be appropriate:
* “sensory neuron” -> [sensory neuron](http://purl.obolibrary.org/obo/FBbt_00005124) (not defined in terms of soma and dendrites location, but should cover the same neurons);
* “motor neuron” -> [motor neuron](http://purl.obolibrary.org/obo/FBbt_00005123) (likewise);
* “ascending neuron” -> [adult ascending neuron](http://purl.obolibrary.org/obo/FBbt_00048301) (our term is slightly broader than intended here as it covers all neurons with a soma in the thorax and abdomen instead of only those with a soma in the VNC);
* “descending neuron” -> [adult descending neuron](http://purl.obolibrary.org/obo/FBbt_00047511) (likewise, our term is broader as it covers all neurons in the head that projects through the cervical connective).

The other terms are missing AFAIK in FBbt:
* “visual centrifugal neuron” (our [centrifugal neuron](http://purl.obolibrary.org/obo/FBbt_00003742) is something else entirely);
* “central brain intrinsic neuron”;
* “endocrine neuron“: we have [endocrine neuron](http://purl.obolibrary.org/obo/FBbt_00007436), but it is much broader than what is intended here.

**Comment by gouttegd** [comment]
From discussing with Gregory Jefferis on Slack, our existing related classes may be enough, at least for now. But we need new terms for the three missing superclasses.

So the proposition is to add:

* `adult central brain intrinsic neuron`, defined as an [intrinsic neuron](http://purl.obolibrary.org/obo/FBbt_00003664) that [has synaptic IO in region](http://purl.obolibrary.org/obo/RO_0013001) some [adult central brain](http://purl.obolibrary.org/obo/FBbt_00047887) (this is on par with how we define similar intrinsic neurons);
* `visual centrifugal neuron`, defined as a [neuron](http://purl.obolibrary.org/obo/FBbt_00005106) that [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [adult central brain](http://purl.obolibrary.org/obo/FBbt_00047887) and [sends synaptic output to region](http://purl.obolibrary.org/obo/RO_0013003) some [adult optic lobe](http://purl.obolibrary.org/obo/FBbt_00003701);
* `adult brain endocrine neuron`, defined as a [neuron](http://purl.obolibrary.org/obo/FBbt_00005106) that [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [adult central brain](http://purl.obolibrary.org/obo/FBbt_00047887) and [sends synaptic output to region](http://purl.obolibrary.org/obo/RO_0013003) some [adult ring gland](http://purl.obolibrary.org/obo/FBbt_00049278).

Other terms (such as larval equivalents) may be added later as needed when the paper is published, when relevant.

**Comment by jefferis** [comment]
@schlegelp @mmc46 any comments on this? I'd love to move forwards quickly.

> adult brain endocrine neuron, defined as a [neuron](http://purl.obolibrary.org/obo/FBbt_00005106) that [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [adult central brain](http://purl.obolibrary.org/obo/FBbt_00047887) and [sends synaptic output to region](http://purl.obolibrary.org/obo/RO_0013003) some [adult ring gland](http://purl.obolibrary.org/obo/FBbt_00049278).

@schlegelp in particular is this broad enough?

**Comment by admclachlan** [comment]
visual centrifugal neuron - I saw some of the visual_centrifugal super_class neurons have an ocellar cell_class on FlyTable Main. These don't fit the newly proposed definition as it's specific to the optic lobe? (assuming the table I can see is up to date). Same for visual projection.

**Comment by jefferis** [comment]
Good catch @admclachlan. @schlegelp?

**Comment by schlegelp** [comment]
Sorry, just catching up with this. For the visual centrifugals:
1. Their soma isn't always in the central brain. I vaguely remember a few cases where the soma is nominally in the optic lobes but with dendrites in the central brain and axon in the optic lobes.
2. Re Alex' catch: the neurons with `super_class=visual_centrifugal` and `cell_class= ocellar` go from the central brain into the ocellar ganglion. Would be possible to say "visual centrifugal neuron = axonal projections into optic *neuropils*", where "optic neuropils" is the optic lobes + the ocellar ganglion?

**Comment by gouttegd** [comment]
Regarding the “adult brain endocrine neuron”, I see in table 2 of the draft that they are defined as “neurons that exit the brain via the NCC towards the ring gland“. So we could define them more closely as

[neuron](http://purl.obolibrary.org/obo/FBbt_00005106) that [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [adult brain](http://purl.obolibrary.org/obo/FBbt_00003624) and [fasciculates with](http://purl.obolibrary.org/obo/RO_0002101) some [nervus corporis cardiaci](http://purl.obolibrary.org/obo/FBbt_00049645).

I would also suggest to call them “adult ring gland projection neuron”, which would be consistent with our existing term for similar neurons in the larva ([larval ring gland projection neuron](http://purl.obolibrary.org/obo/FBbt_00051985)). We can still have “adult brain endocrine neuron“ as a synonym.

**Comment by mmc46** [comment]
Re: visual centrifugal
If the definition using OR isn't desirable, then could a term that encompasses both the optic lobes and occeli be created, maybe referring to regions with light detection capability?

Re: adult endocrine neuron
If the table defines them as fasciculating with the NCC  that definition is probably better than using the ring gland as output.

**Comment by dosumis** [comment]
If we are using logical defs, they should be suitable for automated classification. I don;'t this '[sends synaptic output to region](http://purl.obolibrary.org/obo/RO_0013003)' or use of OR are compatible with that (given ELK reasonser).  Where we just need to group a small number of existing grouping classes it is probably be best to just rely on manual classification.  This doesn't do harm for high level grouping classes where we don't expect more direct subclasses.

**Comment by gouttegd** [comment]
@dosumis The proposed logical definition for “visual centrifugal neuron” (using '[sends synaptic output to region](http://purl.obolibrary.org/obo/RO_0013003)') does result, with ELK, in a sizeable amount of neuron classes being auto-classified under the new term.

The use of `or` here has no effect, but that’s only because we currently do not have any neuron that sends output to the ocellar ganglion.

Anyway, happy to go without a logical definition for now. At least the term will be there. Once the paper is out we can either start manually classifying the neurons that belong to that class, or have another go at a logical definition.
