### ISSUE TITLE
New Term Request: L1EM winding paper terms

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1642]
For new term requests, please provide the following information:

## Attribution

Table [here](https://github.com/VirtualFlyBrain/Management/blob/master/L1EM/L1EM%20winding%20Mapping.csv) for 46 new cell types required for the final L1EM neurons. These are only for new neurons, typings in this paper for existing neurons are not in this file.

Paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7614541/#SD6 (don't think there's an FBrf yet).
pair loop is in the supplement (17D), not sure if this class is needed. If we don't use it I'll use either the more general typing or check the other annotations. 

Table S1 shows the ascending neurons.

Please contact me if there's any questions or more detail required. Looks like some of thse are

**Comment by gouttegd** [comment]
@admclachlan I can’t access the table at https://github.com/VirtualFlyBrain/Management/blob/master/L1EM/L1EM%20winding%20Mapping.csv

In fact I can’t access anything in the `VirtualFlyBrain/Management` repository.

**Comment by Clare72** [comment]
@gouttegd did you start work on this already? I changed the ticket assignment, but might be easier for you to finish it if you have already made a lot of progress.

**Comment by gouttegd** [comment]
@Clare72 I have not done anything on that issue yet, sorry.

**Comment by admclachlan** [comment]
Also that paper updates some existing neurons as well. Is it worth adding those, or checking if they need adding?

**Comment by Clare72** [comment]
> @Clare72 I have not done anything on that issue yet, sorry.

fine - makes it easier for me to take over!

@admclachlan I will look at the paper and do any worthwhile updates/additions

**Comment by Clare72** [comment]
final version https://www.science.org/doi/10.1126/science.add9330
FBrf0255988

**Comment by Clare72** [comment]
[L1EM winding Mapping.csv](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/files/12409592/L1EM.winding.Mapping.csv)

Additional column with mappings to use (many need newly-created terms)
