### ISSUE TITLE
New Term Request: SPN

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1646]
For new term requests, please provide the following information:

## Preferred term label

'serotonergic projection neuron' but it's a specific pair that are activated by lack of Dnc so maybe needs more?

## Synonyms

SPN

## Textual definition

FBrf0244287 but original description in FBrf0238754

The SPN is located in the gnathal ganglia (GNG) and projects to central brain compartments, where it surrounds the MB peduncle.

## Suggested parent term

projection neuron?

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by gouttegd** [comment]
>'serotonergic projection neuron' but it's a specific pair that are activated by lack of Dnc so maybe needs more?

Agree, “serotonergic projection neuron” can be used as a synonym but for the label we’ll need to mint a more precise name – unless it is clear that this pair are the only projection neurons that are serotonergic, which seems unlikely.
