### ISSUE TITLE
New Term Request:  uterus and ovipositor ppk+

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1653]
For new term requests, please provide the following information:

## Preferred term label

at least two, presumably sensory so something like adult uterus sensory neuron

## Synonyms

(e.g., Absent spleen)

## Textual definition

FBrf0246914

This ppk-SS driver line labels a pair of cells at the lateral oviducts and clusters of cells at the [uterus](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/uterus) and ovipositor that are ppk+ ([Figure S4](https://www.sciencedirect.com/science/article/pii/S0960982220311428?via%3Dihub#mmc1)A) and fru− ([Figure S4](https://www.sciencedirect.com/science/article/pii/S0960982220311428?via%3Dihub#mmc1)B).

which leads to the activation of ppk+ mechanosensory neurons in the [uterus](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/uterus)

For ovipositor extrusion, mating status information is evidently conveyed by the ppk+ neurons in the [oviduct](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/oviduct) and uterus. These mechanosensory neurons are believed to detect the passage of an egg following the onset of ovulation and fertilization after mating [[13](https://www.sciencedirect.com/science/article/pii/S0960982220311428?via%3Dihub#bib13)].

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/fbbt)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by gouttegd** [comment]
I note that we already have a term for similar neurons in the oviduct ([adult oviduct mechanosensory neuron](http://purl.obolibrary.org/obo/FBbt_00049944)), from FBrf0226663 (which is the reference “13“ in the quoted extract).

That paper only described such neurons in the oviduct, now apparently we have some in the uterus and the ovipositor as well.

We can either:
* extend the scope of our existing term [adult oviduct mechanosensory neuron](http://purl.obolibrary.org/obo/FBbt_00049944) to also cover the uterus and ovipositor neurons;
* leave [adult oviduct mechanosensory neuron](http://purl.obolibrary.org/obo/FBbt_00049944) as it is and add `adult uterus mechanosensory neuron` and `adult ovipositor mechanosensory neuron` to refer specifically to the neurons in the newly described locations.

I am slightly inclined toward the first option, as the new paper doesn’t describe the uterus and ovipositor neurons in great details (apart from saying they are here).

**Comment by admclachlan** [comment]
Both of those work for me, ideally the separate terms but agreed there isn't much description so the group term seems more appropriate for now.
