### ISSUE TITLE
New Term Request: LC6/26 putative downstream neurons

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1654]
For new term requests, please provide the following information:

## Preferred term label

LC6G1 - LC6G5 and LC26G1

## Synonyms

LC6 Glomerulus 1–5 LC26 Glomerulus 1

## Textual definition
some anatomy definition + NTs

Cell body positions, presumably reflecting distinct developmental origins, are in the cell body rind of the anterior dorsal (LC6G1 and LC6G3) or posterior (LC6G4) central brain and in the space between the optic lobe and central brain (LC6G2 and LC6G5). Bilateral arbors that span both brain hemispheres differentiate LC6G1 from the other LC6Gs (which have only ipsilateral processes

Is this enough to make terms for these? Without specific terms curating the split-GAL4s for these would be very vague.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/fbbt)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by gouttegd** [comment]
Which paper(s) do they come from? Do you have a FBrf?

**Comment by admclachlan** [comment]
oops, it's FBrf0247630

**Comment by gouttegd** [comment]
We already have ‘[LC6 glomerulus interneuron 1](http://purl.obolibrary.org/obo/FBbt_00049987)’ (synonym “LC6G1”) and likewise for LC6G2–5, and ‘[LC26 glomerulus interneuron 1](http://purl.obolibrary.org/obo/FBbt_00049992)’ (synonym “LC26G1”), based on descriptions from this very paper. Unless I am missing something I believe this is exactly what you wanted?

**Comment by admclachlan** [comment]
Sorry Damien, I'm not doing well with this issue. My protege search gave up. Yes they're all there. Thanks.
