### ISSUE TITLE
Mapping Review: Otto 2020

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1688]
For new term requests, please provide the following information:

FBrf0246510

Looks like new terms from this paper have been added. 

Can you check if the tsv for the splits in this paper looks correct? - mainly is OTHERS just a subset of adult neurons in the brain? There's a lot of very vague terms used in the tsv, but I don't think the paper provides enough info to do more so just checking.

https://github.com/VirtualFlyBrain/Management/blob/master/Expression_curation/splits_tsvs/Papers/Otto2020/Otto2020_splits_for_splitcombo.tsv

**Comment by Clare72** [comment]
>OTHERS, a variety of neurons conveying information from other brain areas

so, yeah, could be anything

**Comment by Clare72** [comment]
Not sure about the MBON-gamma1gamma2gamma3gamma4 cell type - might be multiple cell types that collectively innervate those regions? Not clear from paper.

**Comment by Clare72** [comment]
Likewise, are you sure that MBONgamma2 means all of MBONs 32, 34, 35? or could it just mean at least one gamma2-innervating MBON.

**Comment by admclachlan** [comment]
OK thanks, will leave the sezons and others as is. No I'm not sure on MBONgamma2 either. Thanks for confirming, I'll see if it's worth contacting the authors.
