### ISSUE TITLE
Some terms for primordia and anlagen have multiple definitions

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1761]
Since PR #1750, some terms for primordia and anlagen end up with multiple definitions (one generated from the pattern and one that was already “manually” set on the term). This is not allowed and results in a failure of the build pipeline:

```sh
OBO STRUCTURE ERROR Ontology does not conform to OBO structure rules:
multiple def tags not allowed. in frame:Frame(FBbt:00001946 id( FBbt:00001946)def( A(n) anlage that develops into some lobula plate. It develops from some larval inner optic anlage.[FBC:Autogenerated ])def( Anlage of the embryo/larva that is the precursor to the adult lobula plate.[https://orcid.org/0000-0001-5948-3092 ])subset( cur)xref( larvalbrain_neuropil:558)name( lobula plate anlage)xref( VFB:FBbt_00001946)xref( larvalbrain_neuropil:380)namespace( fly_anatomy.ontology)relationship( BFO:0000050 FBbt:00001930)relationship( RO:0002202 FBbt:00001951)is_a( FBbt:00005426)relationship( RO:0002203 FBbt:00003885))
For details see: http://robot.obolibrary.org/errors#obo-structure-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make: *** [fbbt.Makefile:173: tmp/nosymbolsmerged-fbbt-edit.obo] Error 1
```

This was not caught by the CI check because, while the error [did occur during the check](https://app.travis-ci.com/github/FlyBase/drosophila-anatomy-developmental-ontology/builds/268291477) for PR #1750, the test still returned success because of an [horrendous bug in the ODK](https://github.com/INCATools/ontology-development-kit/issues/981).

**Comment by gouttegd** [comment]
There is a couple of other problems in both the #1750 and #1754 PRs (which should again have been caught by the test suite, but were not because of the aforementioned bug):

## `definitions.owl` contains a weird class declaration:

```
Declaration(Class(<http://purl.obolibrary.org/obo/FBbt_>)
```

This is caused by [this line](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/5390d5306ab39a69b95bf8add6bd36ebcae18c27/src/patterns/data/all-axioms/developingEntityWithEarlierAndLaterStructures.tsv#L50) in the `developingEntityWithEarlierAndLaterStructures.tsv` data file:

```
FBbt:00007049  head visceral muscle primordium FBbt:00005495   primordium      FBbt:                   
```

We do not have a `head visceral muscle` term, so we should either create it or remove that line.

## Some prothoracic muscles are inferred to be equivalent to their mesothoracic counterparts.

This is caused by a couple of errors in the `anatomicalEntityBySegment.tsv` data file:

* `mesothoracic dorsal acute muscle` is [classified](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/5390d5306ab39a69b95bf8add6bd36ebcae18c27/src/patterns/data/logical-only/anatomicalEntityBySegment.tsv#L487) as part of some `larval prothoracic segment`
* there are two rows for `mesothoracic oblique muscle`, [one of them](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/5390d5306ab39a69b95bf8add6bd36ebcae18c27/src/patterns/data/logical-only/anatomicalEntityBySegment.tsv#L491) assigning the muscle to the `larval prothoracic segment`.

**Comment by Clare72** [comment]
Haha, how strange - not sure how that happened, would have expected dosdp to throw an error if an invalid id is used...
We probably don't want the primordium term if we don't have a term for 'head visceral muscle', but that is not for this ticket - I will sort out the 'head visceral muscle primordium' term for now

**Comment by gouttegd** [comment]
I’m already on it, I can submit a PR in a moment. :)
