### ISSUE TITLE
All PMID & ISBN in FBbt/dv should be switched to FBrf

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#177]
All PMID & ISBN in FBbt/dv should be switched to FBrf.  Where necessary, FBrfs can be requested from FlyBase.    This is required for harmonization of the VFB representation of references.
CC @gm119

List of IDs here (FBbt only):

{'ISBN:0126603030',
 'ISBN:0192801023',
 'ISBN:0198506732',
 'ISBN:0198547684',
 'ISBN:0198606907',
 'ISBN:0387520546',
 'ISBN:0395448956',
 'ISBN:0582015952',
 'ISBN:0582227089',
 'ISBN:0697037754',
 'ISBN:0709408862',
 'ISBN:0716731363',
 'ISBN:0721619908',
 'ISBN:0721662544',
 'ISBN:0781735149',
 'ISBN:0815316194',
 'ISBN:0877797099',
 'ISBN:087797099',
 'ISBN:3527307206',
 'ISBN:978-0-12-024226-9',
 'ISBN:978-0-12-374144-8',
 'ISBN:978-0-19-514324-9',
 'ISBN:978-0-19-860917-9',
 'ISBN:978-0-387-30053-5',
 'ISBN:978-0-470-14987-4',
 'ISBN:978-0-521-57048-0',
 'ISBN:978-0-521-57890-5',
 'ISBN:978-0-521-58445-6',
 'ISBN:978-0-521-82149-0',
 'ISBN:978-0-691-05912-9',
 'ISBN:978-0-7204-7136-6',
 'ISBN:978-0-87893-726-4',
 'ISBN:978-1-58706-259-9',
 'ISBN:978-3-11-014898-5',
 'ISBN:978-3-540-07343-7',
 'ISBN:978-3-540-42590-8',
 'PMID:10885514',
 'PMID:11102830',
 'PMID:1234',
 'PMID:12726833',
 'PMID:12966498',
 'PMID:1346506',
 'PMID:16902576,
 'PMID:24568158',
 'PMID:16991854',
 'PMID:1707069',
 'PMID:18269908',
 'PMID:18355807',
 'PMID:18535862',
 'PMID:19279637',
 'PMID:20160973',
 'PMID:21062451',
 'PMID:21576241',
 'PMID:2469195',
 'PMID:26780543',
 'PMID:28730682',
 'PMID:3373206',
 'PMID:5029818',
 'PMID:8650222',
 'PMID:8938125',
 'doi:10.1098/rstb.1948.0007',
 'doi:10.1371/journal.pbio.1000461.g002',
 'doi:10.1371/journal.pbio.1000461.g003',
 'doi:10.1371/journal.pbio.1000461.g004'}

(created using https://gist.github.com/dosumis/60fc1736ebe44d2742b8c3bda7479d2c)

**Comment by Clare72** [comment]
Also need to do PMID:19783135 (nephrocyte reference)

**Comment by dosumis** [comment]
Sorry. It seems my script pulled in some GO references.  We may have to cope with some of these for VFB - but agree this is outside scope of FlyBase.

Here's the regenerated list with only directly associated refs:

{'ISBN:978-0-387-30053-5', 'PMID:3373206', 'ISBN:978-0-7204-7136-6', 'PMID:1346506', 'ISBN:978-0-521-57890-5', 'ISBN:978-3-11-014898-5', 'PMID:28730682', 'ISBN:978-0-691-05912-9', 'PMID:16991854', 'ISBN:978-0-521-82149-0', 'doi:10.1371/journal.pbio.1000461.g003', 'ISBN:978-0-521-58445-6', 'ISBN:978-3-540-42590-8', 'doi:10.1371/journal.pbio.1000461.g004', 'PMID:12966498', 'ISBN:978-1-58706-259-9', 'ISBN:978-0-19-860917-9', 'doi:10.1098/rstb.1948.0007', 'PMID:26780543', 'ISBN:978-0-19-514324-9', 'doi:10.1371/journal.pbio.1000461.g002', 'PMID:5029818', 'PMID:21062451', 'ISBN:978-0-470-14987-4', 'ISBN:978-0-87893-726-4', 'ISBN:978-0-12-024226-9', 'ISBN:978-3-540-07343-7', 'ISBN:978-0-521-57048-0', 'PMID:1707069', 'PMID:18355807', 'ISBN:978-0-12-374144-8', 'PMID:18535862'}

Apologies for any extra work caused.
