### ISSUE TITLE
founder cell for visceral somatic muscles

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/drosophila-anatomy-developmental-ontology#1780]
Found when working on scRNAseq data from [Mendoza-Garcia et al. (2021; FBrf0251121)](https://doi.org/10.1242/dev.199465):

FBbt currently describes `muscle founder cell` (FBbt:00005084) as a precursor specific to _somatic_ muscles:

* the definition states “there is one founder cell for each embryonic/larval _somatic_ muscle”;
* the term is `part_of` some `somatic muscle primordium`.

Likewise, `fusion competent cell` (FBbt:00005085) is also `part_of` some `somatic muscle primordium`.

However it seems that _visceral_ muscles (both circular and longitudinal) also originate from the fusion of a “founder cell” and several “fusion competent cells”, as first reported by [San Martin et al., (2001; FBrf0138374)](https://doi.org/10.1242/dev.128.17.3331).

So we might need to either

* make our `muscle founder cell` and `fusion competent cell` neutral wrt to the somatic/visceral distinction, or
* create distinct terms for visceral muscle founder and fusion-competent cells.

**Comment by Clare72** [comment]
I think I would go with the first option - definitions and labels are not specific to somatic muscle (saying there is one founder for each somatic muscle does not preclude the existence of founders for visceral muscles), so just need to change the logical axioms.

**Comment by gouttegd** [comment]
Agree. San Martin et al. (2001) explicitly state that the founder cells of visceral muscles might not actually be any different from those of somatic muscles (apart from their slightly different locations in the mesoderm), so we might not need two distinct terms.
