### ISSUE TITLE
Check all axiomatisation relations in  FBbt-edit and FBb_ext files is in RO

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#179]
- [ ] Check axioms in fbbt files against RO and move anything missing to RO.
- [ ] Remove all axioms except old style OBO ID + xref mappings 

NOTE - This is really necessary to clean up pipeline, but could potentially cause headaches for loading to FlyBase....  even though (AFAIK) relations axioms loaded in FlyBase are completely unused.

**Comment by Clare72** [comment]
I think this is all done now
