### ISSUE TITLE
adult muscle merges

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#1814]
adult muscle classes that only have one child - check whether these are redundant:

Parent | Children
-- | --
tergal remotor muscle | [coxal tergal remotor muscle]
prothoracic remotor muscle | [prothoracic pleural remotor and abductor muscle 29]
prothoracic tibial depressor muscle | [prothoracic tibial depressor muscle 40]
lateral cervical muscle | [lateral cervical muscle 24]
anterior rotator muscle | [prothoracic sternal anterior rotator muscle 31]
posterior rotator muscle | [prothoracic sternal posterior rotator muscle 32]
tergopleural promotor muscle | [prothoracic tergopleural promotor muscle 28]
intracoxal lateral levator muscle | [prothoracic intracoxal lateral levator muscle 36]
intracoxal mesal levator muscle | [prothoracic intracoxal mesal levator muscle 37]
mesothoracic tibial depressor muscle | [mesothoracic tibial depressor muscle 71]
metathoracic tibial depressor muscle | [metathoracic tibial depressor muscle 92]
adductor muscle | [prothoracic sternal adductor muscle 33]

query:
`match (sc:Class)-[:SUBCLASSOF]->(m:Class)-[:SUBCLASSOF*]->(h:Class) where h.label="adult somatic muscle" return distinct m.label, collect(distinct sc.label), count(distinct sc.label) order by count(distinct sc.label)`

**Comment by Clare72** [comment]
Parent | Children | merge? | notes
-- | -- | -- | --
tergal remotor muscle | [coxal tergal remotor muscle] | yes | parent not used directly for curation
prothoracic remotor muscle | [prothoracic pleural remotor and abductor muscle 29] | yes | parent not used directly for curation
prothoracic tibial depressor muscle | [prothoracic tibial depressor muscle 40] | yes | parent not used directly for curation
lateral cervical muscle | [lateral cervical muscle 24] | yes | parent not used directly for curation
mesothoracic tibial depressor muscle | [mesothoracic tibial depressor muscle 71] | yes | parent not used directly for curation
metathoracic tibial depressor muscle | [metathoracic tibial depressor muscle 92] | yes | parent not used directly for curation
adductor muscle | [prothoracic sternal adductor muscle 33] | no | should be other child classes
anterior rotator muscle | [prothoracic sternal anterior rotator muscle 31] | no | this might be in other segments
posterior rotator muscle | [prothoracic sternal posterior rotator muscle 32] | no | this might be in other segments
tergopleural promotor muscle | [prothoracic tergopleural promotor muscle 28] | no | this might be in other segments
intracoxal lateral levator muscle | [prothoracic intracoxal lateral levator muscle 36] | no | this might be in other segments
intracoxal mesal levator muscle | [prothoracic intracoxal mesal levator muscle 37] | no | this might be in other segments


for merges, also need to merge 'cell' terms

**Comment by SianGramates** [comment]
While I agree with the proposed merges, I'd advocate for using the child term as the term that is kept (the muscle number has meaning to the people who study the muscle system.

**Comment by Clare72** [comment]
Thanks, yes, that was the plan (also because there is no existing curation directly to the parent terms), should have stated this.

**Comment by SianGramates** [comment]
I'm happy we're on the same ontological page.
