### ISSUE TITLE
Migrate perl scripts to run from makefile - either as perl or as new sparql

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#182]
### [chado_load_checks.pl](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/tools/release_and_checking_scripts/trunk/chado_load_checks.pl): 

1. Are there multiple terms with the same name?
2. Do all non-anonymous terms have names?
3. Are def_dbxrefs and synonym_dbxrefs one of the following: FlyBase:FBrfnnnnnnn; FlyBase:FBimnnnnnnn; FBC:\<curator initials\>; PMID:\d+;  http://...; ISBN:<legal ISBN13>; CARO:<CARO curator initials>; VFB_vol\:\d{8}; DOI\:\d+\.\d+\/\w+; FlyBrain_NDB\:\d+; CHEBI\:\d+; MeSH\:D\d+; GOC:\S+; Reactome\:\d+; UniProt\:P\d+/
    - Note - this is the allowable list for FBbt and FBdv.  FBcv terms that import def_dbxrefs from GO may have dbxrefs from the longer, GO approved list: https://flybase.org/svn/ontologies/CVS_versions/GO.xrf_abbs.  There are currently no scripted checks of this list.
2. Checks for descriptions inserted into synonym or def dbxref lists:
It is legal in OBO 1.2 format for synonym  or def dbxref lists to include quoted descriptions of references following each dbxref. Depending on the setup of the OboEdit reference library, these may be inserted automatically when adding references. However,  GO::Parser (used in loading) fails to strip out these comments before parsing as a comma delimited list, leading badly formatted xrefs and failure of loading into chado.
3. Checks (via OboModel STDERR) that all Term stanza tags are from the following allowable list:
/^name\: |^id\: |^namespace\: |^def\: |^comment\: |^intersection_of\: |^relationship\: |^xref\: |^synonym\: |^is_a\: |^subset\: |^union_of\: |^is_obsolete\: |^is_anonymous\: |^disjoint_from\: |^alt_id\: |^consider\: |^replaced_by\: |^creation_date\: |^created_by\: |^exact_synonym\: |^broad_synonym\: |^narrow_synonym\: |^related_synonym\: |^xref_analog\:/
4. Checks that namespaces match id-prefixes.

## reports: 

Tracking changes: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/tools/release_and_checking_scripts/trunk/obo_track_new.pl

percent classes with a logical or textual defintion: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/tools/release_and_checking_scripts/trunk/onto_metrics_calc.pl

## Release:
  This perl script rolls autodefs:  [update_EC_defs.pl](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/tools/release_and_checking_scripts/trunk/update_EC_defs.pl). It should probably just be rolled into the makefile release process for now, but could be migrated to scala.

**Comment by dosumis** [comment]
Sketch of Actions required:

Tests: 
1&2. are probably already checked by ODK as standard (check)
3. Configurable checks for valid xrefs would be nice to have in ODK, but not essential
4. This is almost certainly irrelevant as the tools that produced these problems are no longer used.
5. The new OBO syntax checker can take care of this,  once added
6. A configurable check that matches OBO namespaces to IDs would be useful as mismatches here (especially if they occur between releases) can cause problems for CHADO loading.

Reports: 

Track changes report logic is described in the perldoc here: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/tools/release_and_checking_scripts/trunk/obo_track_new.pl

onto_metrics_calc gives are port of percentage of terms with textual IDs & percentage of terms with logical definitions.  Historically useful for tracking progress at defining terms in ontologies that were previously very poor in definitions.  May not be so important anymore.

@matentzn

**Comment by Clare72** [comment]
I think all of this functionality is now in place - closing
