### ISSUE TITLE
`adult DUM neuron` can perhaps be deprecated in favor of `adult VUM neuron`

### ISSUE THREAD

**Issue by jasper-tms** [FlyBase/drosophila-anatomy-developmental-ontology#1842]
I see that [FBbt:00049554](https://www.ebi.ac.uk/ols4/ontologies/fbbt/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FFBbt_00049554) is `adult dorsal unpaired median neuron` and my paper is cited. A few years ago we had some internal discussion about whether DUM neurons and VUM neurons both exist or are different names for the same thing – it seems like the existence of two separate terms VUM and DUM is due in part to cross-species differences in the soma location of a single type of cells. Some people said they thought DUM and VUM neurons were separate things that both existed in some species, but we didn't really resolve the conversation definitively. Anyway, what is certain is that the cells in Drosophila reported in my paper that are referred to by FBbt:00049554 actually do have their cell body on the ventral side of the VNC, and are certainly the same cells that Erika refers to in FBbt:00052750. (I think we may have had the term "DUM neuron" in our preprint but then in the published paper we changed it to "UM" neuron. I don't believe the term "DUM neuron" in Drosophila exists really, or at least I couldn't tell you what cells it would refer to, other than being a synonym for these VUM/UM neurons.)

I would be in favor of removing/deprecating/marking as obsolete/whatever you call it the term FBbt:00049554

**Comment by Clare72** [comment]
Thanks for the clarification - I have to run any term obsoletions/merges past the FlyBase curators, but if nobody objects I will do the merge before the next release (keeping the VUM term).
