### ISSUE TITLE
New Term Request: oviDN input neurons

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1853]
For new term requests, please provide the following information:

## Reference(s) (Required)

Publication(s) with information about this term (FBrf, DOI or PMID)

FBrf0257087

## Term label(s)

Name(s) given to the new entities in above publication(s), or location of type names in publication (e.g. table).

Had a few mapping questions from this paper. Most splits are straightforward but a few seem to be only linked to hemibrain bodyIds in the paper, and those don't seem to have types. Could you check the 'ontology notes' column?

combo | DBD(short) | AD(short) | <t> | <a> | unmapped | bodyids | notes | Ontology Notes
-- | -- | -- | -- | -- | -- | -- | -- | --
SS69920 | VT064568 | R14D05 | A | oviposition excitatory neuron |   |   |   |  
SS69913 | R26D04 | VT050229 | A | oviposition excitatory neuron | SMP550 |   | stochastic | Could SMP550  be a   oviEN?
SS69542 | VT043700 | R34F03 | A |   | PAL02 |   |   | PAL02 is not in the ontology, but I don't see much of a description in   this paper either
SS69540 | VT033614 | R34F03 | A |   | PAL02 |   |   | PAL02 is not in the ontology, but I don't see much of a description in   this paper either
SS66793 | VT002057 | VT040569 | A | adult superior lateral protocerebrum neuron 212 |   |   |   |  
SS66794 | VT002057 | VT002857 | A | adult superior lateral protocerebrum neuron 212 |   |   |   |  
SS65423 | VT026035 | VT026347 | A | oviposition inhibitory neuron |   |   |   |  
SS65424 | VT010054 | VT027273 | A | oviposition inhibitory neuron |   |   |   |  
SS65422 | VT010054 | R68A10 | A | oviposition inhibitory neuron |   |   |   |  
SS64946 | VT002223 | VT017683 | A |   | group B | 671618401 |   | body ID doesn’t seem to have a type?
SS64927 | VT017683 | VT028555 | A |   | group B | 422328492 |   | body ID doesn’t seem to have a type?
SS45323 | VT016254 | VT019330 | A | adult superior medial protocerebrum neuron 094 |   |   |   |  
SS45323 | VT016254 | VT019330 | A | adult superior medial protocerebrum neuron 602 |   |   |   |  
SS69514 | VT008660 | VT027104 | A | adult superior medial protocerebrum neuron 094 |   |   |   |  
SS69514 | VT008660 | VT027104 | A | adult superior medial protocerebrum neuron 602 |   |   |   |  
SS69457 | R55D08 | VT008660 | A | adult superior medial protocerebrum neuron 094 |   |   |   |  
SS69457 | R55D08 | VT008660 | A | adult superior medial protocerebrum neuron 602 |   |   |   |  
SS69505 | VT005534 | VT008474 | A |   | group T | 704816317, 1629383757 |   | body ID doesn’t seem to have a type?
SS69429 | VT045575 | VT039470 | A | adult crepine neuron 039 |   |   |   |  
SS66864 | VT022246 | VT024647 | A | adult superior medial protocerebrum neuron 029 |   |   |   |  
SS54798 | VT020732 | VT017683 | A | adult fruitless aDT-h neuron \| subset |   |   |   |

**Comment by Clare72** [comment]
>Could SMP550  be a oviEN?
It is possible, but far from clear in this paper.

AFAIK there is no mapping or description of the PAL01, 02 etc types anywhere, so just have to go with parent class ('dopaminergic PAL neuron').

I think your guess is as good as mine as to what 'group B' and 'group T' neurons are - there doesn't seem to be any description of them aside from connectivity, so not really possible to make terms.

**Comment by admclachlan** [comment]
Thanks for confirming that Clare.
