### ISSUE TITLE
New larval interneurons from Jovanovic 2016 Larval paper: Competitive Disinhibition Mediates Behavioral Choice and Sequences in Drosophila 

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#188]
Drunken-1 a1l
Drunken-1 a1r
Griddle-1 a1l
Griddle-1 a1r
Griddle-1 t3l
Griddle-1 t3r
Griddle-2 a1l
Griddle-2 a1r
Handle-A a1
Handle-B a1
Ladder-a a1
Ladder-b a1
Ladder-c a1
Ladder-d a1
Ladder-e a1
Ladder-f a1
Ladder-f a2
fbLN-Hb
fbLN-Ha

see also https://github.com/VirtualFlyBrain/Management/issues/33

**Comment by Clare72** [comment]
We decided not to separate left and right.
All the a1, a2 etc. that seemed to exist (including these) are in the next release.
Btw,  fbLN-Ha = Handle-A and fbLN-Hb = Handle-B (synonyms are in ontology)
