### ISSUE TITLE
Crop innervating MS neurons

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#1908]
For new term requests, please provide the following information:

## Reference(s) (Required)

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7610780/
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/243f397d-e1c2-4c5c-9331-9d3a93e5e59c">

Publication(s) with information about this term (FBrf, DOI or PMID)

## Term label(s)

Name(s) given to the new entities in above publication(s), or location of type names in publication (e.g. table).

MS neuron of adult pars Intercerebralis
 - crop innervating MS neuron of adult pars Intercerebralis

Might also be worth distinguishing two subpopulations mentioned in paper.

I wonder whether we can use something stronger than 'overlaps' as relationship to Crop.  Really important we find a way to expose/query this from Crop on VFB.

## Notes

 - it looks like these are a subset of the PI neurons that we already have - already related to crop
<img width="680" alt="image" src="https://github.com/user-attachments/assets/a0d98008-0edb-4f5f-8d9c-f7763f5885d1">

- interesting to see MS in some of these populations detected in scRNAseq   https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?q=FBgn0011581,expressionCluster

**Comment by Clare72** [comment]
>I wonder whether we can use something stronger than 'overlaps' as relationship to Crop. Really important we find a way to expose/query this from Crop on VFB.

This is a larger issue that I am not addressing here - I think we need something new in RO to represent peptide release sites to do this properly. Currently all represented as 'overlaps'.
