### ISSUE TITLE
obsoletion of undefined terms

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#1935]
FBbt:00001573 'EN neuron' has no definition, references or curation, so we should just obsolete it.
FBbt:00001575 'VL neuron' has no definition, references or curation, so we should just obsolete it.
FBbt:00002062 'subesophageal commissure' has no definition, references or curation, so we should just obsolete it.
FBbt:00003061 'adult abdominal dorsal tracheal branch 9' has no definition, references or curation, and has a comment indicating that it does not exist, so we should just obsolete it.
FBbt:00001574 'DL neuron' has no definition or references and its only usage in curation is to represent the dorsolateral (DL) corazonin neurons of the larva from FBrf0184106 - Choi et al. (2005), which are better represented by FBbt:00052005 'larval corazonin neuron of pars lateralis'.
FBbt:00001932 'embryonic/larval optic stalk sheath cell' has no definition or references. It has been used in curation of FBrf0219021 - Jin et al. (2012), probably to represent 'Optic stalk ensheathing glia', which might be the same cell type as FBbt:00100522 'embryonic/larval optic stalk surface glial cell', but is neither depicted nor described in FBrf0219021.

**Comment by SianGramates** [comment]
Assuming you can retrofit the handful of curation that use couple of the obsoleted terms, I have no objections to the proposed obsoletions.
