### ISSUE TITLE
obsolete 'region of integument defined by pigmentation pattern'

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#1947]
This term only has one child and has not been directly used for curation.
Having terms like this create an unnecessary maintenance overhead and don't seem to be particularly useful.

**Comment by SianGramates** [comment]
But you are leaving the child, 'trident', in place, right? I fully agree if that is the case, and you're just getting rid of the intermediate term.

**Comment by Clare72** [comment]
yes of course, 'trident' will be a direct child of 'region of integument', just cutting out the intermediate term
