### ISSUE TITLE
Is 'adult Leucokinin LHKL lateral horn neuron' a typo?

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#197]
Should it be 'adult Leucokinin _LHLK_ lateral horn neuron'? - this is how it is referred to in FBrf0155902 and FBrf0209907, the given references.

**Comment by Clare72** [comment]
Yes, I agree, I found LHKL in one place in the references, but it looks like that was a typo. Clearly meant to be LHLK:

>Two marked protocerebral cells are known as the lateral horn leucokinergic (LHLK) cells

-FBrf0209907
