### ISSUE TITLE
Fix upper ontology conflicts causing failure of FBbt Uberon bridge

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#201]
(@Clare72  - don't worry about this one.  Nico and I'll will deal with fixes.)

Combining FBbt, Uberon and CL using [bridge/uberon-bridge-to-fbbt](https://github.com/obophenotype/uberon/blob/master/bridge/uberon-bridge-to-fbbt.obo) causes a number of inconsistencies.  These date back to the development of CARO & its separate implementation in Uberon and FBbt.  We need to fix these problems for a number of reasons, including: 
  * Ensuring Monarch can properly use FlyBase phenotypes
  * Generating nested Uberon + CL + FBbt files for use in multi-species resources that need to group anatomy and cell types.  This includes EBI resources including the single cell atlas.

This is an umbrella ticket for documenting these issues and their fixes.

There is a serious possibility of becoming bogged down in upper ontology issues which are of little interest to biologists, so some slightly unsatisfactory compromises may have to be made.  In these cases the aim should be to document those compromises and park any remaining issues on a ticket.   This ticket can be closed once issues are resolved and compromises suitably documented. 

Fixes may be in FBbt or Uberon.  If the latter, then any Uberon tickets should be linked from here.

**Comment by dosumis** [comment]
### Brief outline of issues

Issue 1:   Anatomical group in Uberon vs FBbt:  https://github.com/obophenotype/uberon/issues/1430
Possible solutions: 
* Fix Uberon following CARO (This is clearly longer term and requires much more testing.) 
* Remove mapping of anatomical group to Uberon term - they are clearly incompatible.  This solution is preferable as long as it doesn't leave too many orphan terms.  
* Remove 'anatomical structure'/'anatomical group' disjointness in FBbt?  - 

Issue 2: non-connected anatomical system is classified in uberon under 'anatomical entity' which is defined as connected.  Possible solutions:
   * Fix Uberon following CARO (This is clearly longer term and requires much more testing.) 
   * Remove mapping of non-connected anatomical system to Uberon term.  This solution is preferable as long as it doesn't leave too many orphan terms.   Not entirely satisfactory though.  Anatomical system being a reasonable grouping that will be lost.

Issue3: What's a ganglion ?
   - cell cluster organ vs multi-tissue structure.

Issue4: Gonadal sheath
   - granularity issue.   Gonadal sheath in mammals is an epithelium. Gonadal sheath in insects includes a visceral muscle component. 
   Poss solution: Does FBbt have gondal sheath epithelium?  Could map to that.

Issue5: Single cell muscles! 
   - granularity issue!
   - Map to myotubes instead?

**Comment by dosumis** [comment]
@cmungall for changes to mappings I'm assuming I should create a pull request with and edit to
 https://github.com/obophenotype/uberon/blob/master/bridge/uberon-bridge-to-fbbt.owl + change xrefs to FBbt in uberon-edit.obo.  Is this correct?

**Comment by dosumis** [comment]
Note: this is required for EBI scAtlas to be able to consume FBbt and use it for annotation.   

@cmungall - Almost  all of these issues are to do with granularity and in general I think FBbt is justified in  the granularity/composition based classifications it makes  given  what we know of fly biology.   Given that, I think  the  best course may be to make the problematic granularity-based classifications in Uberon more general.  Either that or we need more general grouping classes for FBbt to  map up to.

**Comment by cmungall** [comment]
You only need to change the edit.obo file, the bridge axioms are auto-generated from those

**Comment by gouttegd** [comment]
Regarding issue 1:

Uberon now has `disconnected anatomical group` (`UBERON:0034923`), mapped to the same term in CARO (`CARO:0020000`). The definition does not exactly match that of FBbt’s `anatomical group`:

* FBbt’s `anatomical group`: “Material anatomical entity generated by coordinated expression of the organism’s own genome and whose component parts are not all connected to each other.”
* Uberon’s `disconnected anatomical group`: “Material anatomical entity consisting of multiple anatomical structures that are not connected to each other.”

but it still looks like a better match than Uberon’s `anatomical group`.

Suggestion is thus to map FBbt’s `anatomical group` to Uberon’s `disconnected anatomical group` instead of `anatomical group`.

**Comment by gouttegd** [comment]
Regarding issue 2:

As far as I can tell there is no `non-connected anatomical system` term in Uberon. Are you referring to `non-connected functional system` (`UBERON:0015203`)? If so:

That term is mapped to an identical term in FBbt (`FBbt:00007278`) with an identical definition. The mapping looks correct to me, but maybe the problem stems from the fact that `anatomical system` in Uberon (`UBERON:0000467`) is defined as a “connected anatomical structure“? Some of the systems below it are made of components that are certainly not physically connected, e.g. `immune system` or `exocrine system`.

**Comment by gouttegd** [comment]
Regarding issue 3:

FBbt’s `ganglion` (`FBbt:00005137`) is a `multi-tissue structure` (`FBbt:00007010`) while Uberon’s `ganglion` (`UBERON:0000045`) is a `cell cluster organ` (`UBERON:0010001`).

Both classifications make some sense, except that Uberon’s definition of a cell cluster organ is that of “a *small* cluster of cells of various types […]”. In my opinion this “small” adjective should preclude `ganglion` from being a `cell cluster organ`, given that ganglions can be quite large, at least in _Drosophila_. For example the entire ventral nerve cord is a ganglion – if I recall correctly that’s at least a few thousands of cells, so not really a “small” cluster.

**Comment by gouttegd** [comment]
Regarding issue 4:

Yes, FBbt now has `gonadal sheath epithelium` (“epithelial component of the gonadal sheath”) (`FBbt:00047208`). I’ll update the mapping accordingly.

**Comment by gouttegd** [comment]
Regarding issue 5:

We plan to introduce new terms to represent the muscles themselves, so that should take care of this.

**Comment by gouttegd** [comment]
Regarding issue 6:

FBbt’s `central nervous system` is a `organ system subdivision` as in Uberon, so I am not sure I understand what the issue here is…

**Comment by dosumis** [comment]
I think 'cell cluster organ' was one of my terms - designed for sensilla and other small cuticular organs.  I'm not sure how it came to be applied to Uberon:Ganglion.  Maybe just map both to organ?

**Comment by dosumis** [comment]
I've given thumbs up to solutions you proposed that I think are good.

**Comment by dosumis** [comment]
Issue 6 - maybe this has been fixed? It caused inconsistencies previously so if those have gone away then there is no issue.

**Comment by gouttegd** [comment]
All the problems above (and some more) have been fixed; Uberon, CL, and FBbt can be merged while keeping all disjointness axioms without leading to unsatisfiable classes.
