### ISSUE TITLE
"Tectulum" region from Namiki et al preprint

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#204]
We need to decide how this should be handled:

> Our analysis of the VNC suggests that the tectulum, a neuropil near the dorsal surface associated with flight and other wing-related behaviors (Power, 1948; Murphey et al., 1989; Shepherd et al., 2016), stratifies into a dorsal layer that we propose retain the name ‘tectulum’ (Figure 4G, green) and a more ventral layer we call the ‘lower tectulum’ (Figure 4G, red)

https://www.biorxiv.org/content/biorxiv/early/2017/12/11/231696.full.pdf

**Comment by Clare72** [comment]
See also #138

**Comment by Robbie1977** [comment]
@Clare72 We've finally managed to match up Hiro's subdivisions (which extend further than the previous Power 1948 defined tectulum but we've kept the naming). We need the new class definitions for 
https://github.com/VirtualFlyBrain/Management/issues/242#issuecomment-652528976

**Comment by Robbie1977** [comment]
Paper is out of preprint: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6019073/

**Comment by Clare72** [comment]
from https://github.com/VirtualFlyBrain/Management/issues/242

Symbol | is_a IRI | is_a label | Notes
-- | -- | -- | --
ABDNM | FBbt_00110173 | adult abdominal neuromere | Checked OK
AMNP | FBbt_00004091 | adult accessory mesothoracic neuromere | Checked OK
METANM | FBbt_00110176 | adult metathoracic neuromere | Checked OK
MesoNM | FBbt_00110175 | adult mesothoracic neuromere | Checked OK
PRONM | FBbt_00110174 | adult prothoracic neuromere | Checked OK
haltere tectulum | ? | haltere tectulum | FlyBase/drosophila-anatomy-developmental-ontology#204
intermediate tectulum | ? | intermediate tectulum | FlyBase/drosophila-anatomy-developmental-ontology#204
lower tectulum | ? | lower tectulum | FlyBase/drosophila-anatomy-developmental-ontology#204
mVAC | ? | medial ventral association center | FlyBase/drosophila-anatomy-developmental-ontology#204
neck tectulum | ? | neck tectulum | FlyBase/drosophila-anatomy-developmental-ontology#204
wing tectulum | ? | wing tectulum | FlyBase/drosophila-anatomy-developmental-ontology#204

**Comment by Clare72** [comment]
Some of these look like straightforward mappings, but let me know if definitions no longer fit.
Also - where are your region names coming from, they don't quite match what is in Namiki paper?

region | FBbt ID | FBbt name | notes
--|--|--|--
haltere tectulum | FBbt:00047138 | haltere neuropil | 
lower tectulum | FBbt:00047174 | lower tectulum | as in Namiki paper - does it need changing?
mVAC | FBbt:00047176 | medial ventral association center
neck tectulum | FBbt:00047173 | neck motor neuropil |
wing tectulum | FBbt:00047137 | wing neuropil |

We have 'tectulum' 'upper tectulum' and 'lower tectulum' in the ontology. Does 'intermediate tectulum' now correspond to one of these or does it need a new term (and maybe edits to other tectulum terms)? Please can you provide a reference for this @Robbie1977 ?

**Comment by Robbie1977** [comment]
From the latest version of the submitted paper:
**Tectulum**  

The tectulum is a distinct subdivision of the thoracic regions of the VNC. The region forms a saddle-like structure located dorsally, primarily over the accessory mesothoracic neuropil (AMNp) and the mesothoracic neuromere (MesoNm) but extending over the posterior-most region of the prothoracic neuromere (ProNm) and the anteriormost region of the metathoracic neuromere (MetaNm). Its internal boundaries within the VNC can be defined as the dorsal region of the neuropil posterior to ventral ellipse in ProNm, but dorsal to the bundles from 12B, 6B, 23 17, 18B, and e. Extending posteriorly through MesoNm to the entry point of hemilineage 3 in MetaNm. The tectulum can be stratified into three regions (Namiki et al., 2017), which the working group renamed as upper, intermediate and lower tectulum.  

The upper tectulum is the dorsal most stratum of the tectulum, is the dorsal most part of the tectulum sitting dorsal to the tracts DMT, MTD and ITD-HT. The upper tectulum can be further segregated on the basis of the synapse rich neuropil regions into three neuromere specific neuropils. A prothoracic neck neuropil (NTct), a mesothoracic wing neuropil (WTct) and a metathoracic haltere neuropil (HTct). 

The intermediate tectulum, lies immediately ventral to the upper tectulum and dorsal to the lower tectulum and extends from the ProNm mVAC to the posterior margin of the MesoNm at the ITD-CFF commissure. 

The lower tectulum is a region of the pro and mesothoracic neuromeres ventral to the intermediate tectulum extending posteriorly from the proNm mVAC and the posterior margin of the mesoNm at the ITD-CFF commissure. It is contained ventrally by the tract VTV and laterally by DLV tract.  

Changes: 
Abbreviation changed from Power’s ‘T’ (Power, 1948) to avoid potential confusion. The internal boundaries were clarified in relation to lineage tracts (Shepherd et al., 2016). Agreed naming and definitions of the upper, intermediate and lower tectulum. 
 

Synonyms: 

• Tct (Proposed by group), 
• T (Power, 1948), 
• Flight neuropil RELATED (Power, 1948; (Leise, 1991).

**Comment by Robbie1977** [comment]
Jim Truman also added these abbreviations in the Table of Contents for terms but are missing in the above text: 

Tectulum  

- Upper tectulum (UTct) 

- Intermediate tectulum (IntTct) 

- Lower tectulum (LTct)

**Comment by Robbie1977** [comment]
@Clare72 it might be best to shelve this until the paper is out as a clear definition reference; I can just assign as synaptic neuropil for now.

**Comment by Robbie1977** [comment]
from https://github.com/VirtualFlyBrain/curation/blob/0f1d4bc72a4d54073f51a9cb052049997edf9278/records/new_images/working/anat_Court2020_200702.tsv


index | filename | synonyms | label | is_a | part_of | classification_reference
-- | -- | -- | -- | -- | -- | --
   | 13 | haltere_tectulum_only | HTct | haltere tectulum on adult VNC, JRC2018VU | haltere neuropil | thoracico-abdominal ganglion | doi:10.1101/122952
  | 14 | intermediate_tectulum | IntTct | intermediate tectulum on adult VNC, JRC2018VU | synaptic neuropil domain | thoracico-abdominal ganglion | doi:10.1101/122952
  | 15 | lower_tectulum | LTct | lower tectulum on adult VNC, JRC2018VU | lower tectulum | thoracico-abdominal ganglion | doi:10.1101/122952
  | 19 | neck_tectulum | NTct | neck tectulum on adult VNC, JRC2018VU | synaptic neuropil domain | thoracico-abdominal ganglion | doi:10.1101/122952
  | 21 | wing_tectulum | WTct\|Flight Neuropil | wing tectulum on adult VNC, JRC2018VU | wing neuropil | thoracico-abdominal ganglion | doi:10.1101/122952

**Comment by Robbie1977** [comment]
VNC paper is now out that gives final definitions https://doi.org/10.1016/j.neuron.2020.08.005 
https://www.cell.com/cms/10.1016/j.neuron.2020.08.005/attachment/f7602644-8c73-45ad-a36d-b2d36af4e758/mmc1.pdf

**Comment by Clare72** [comment]
VNC paper - FBrf0246815

**Comment by Clare72** [comment]
Closing this as VNC paper is anatomy-curated and I think all these mappings are now correct
