### ISSUE TITLE
Extract neuron names from FlyLight and map to neuron types in FBbt

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#212]
@Robbie1977: FlyLight neuron names we have don't appear to include greeks - but names on the website do.  

e.g.  MBON-gamma5beta'2a

vs 

![image](https://user-images.githubusercontent.com/112839/40418342-00697310-5e7a-11e8-85b3-45676f57a999.png)

Can we get UTF-8 ?

**Comment by dosumis** [comment]
Extracted names in mapping table are here: https://github.com/VirtualFlyBrain/Management/blob/master/Janelia/Janelia_terms_to_map.tsv

Mapping is needed both for adding official abbreviations/symbols to FBbt and for generating expression proformae.  @Clare72 & @ah963 - up to you who does what.

**Comment by ah963** [comment]
Do you know if there is a tool available to batch convert synonyms to FBbt IDs? I can't find one, and no such feature exists on FB @dosumis ?

**Comment by Robbie1977** [comment]
@ah963 you can query the solr server directly:
```
http://solr.virtualflybrain.org/solr/ontology/select?wt=json&fl=short_form+label+synonym&sort=score+desc&df=short_form&q=*:*&fq=synonym:*medulla*
```
just modify the '*medulla*' and remove the wildcard (*) for direct matches

**Comment by Robbie1977** [comment]
I tried to find MBON-gamma5beta.... but doesn't seem to be there. 
To list all (```*MBON*```):
http://solr.virtualflybrain.org/solr/ontology/select?fl=short_form+label+synonym&rows=500&q=synonym:*MBON*

**Comment by dosumis** [comment]
> I tried to find MBON-gamma5beta.... but doesn't seem to be there. To list all (*MBON*): http://solr.virtualflybrain.org/solr/ontology/select?fl=short_form+label+synonym&rows=500&q=synonym:MBON

It's in the list of all MBONS

```xml
</doc>
<doc>
<str name="short_form">FBbt_00100234</str>
<str name="label">mushroom body medial lobe arborizing neuron 6</str>
<arr name="synonym">
<str>MBON-gamma5beta'2a</str>
<str>MBON-01</str>
<str>M6</str>
<str>MB-M6</str>
</arr>
</doc>
```

**Comment by dosumis** [comment]
@ah963 wrote:                       
> Do you know if there is a tool available to batch convert synonyms to FBbt IDs? I can't find one, and no such feature exists on FB

I think I had something in my old Perl scripts for that, but it might be easier to write a new Python script.  This could work by querying SOLR, but perhaps easier to use the JSON version of FBbt.  Could be a cool first project if you're interested in learning some Python.

**Comment by ah963** [comment]
@dosumis, @Clare72  I've done as much as I can until terms are created for the descending neuron paper.

**Comment by Clare72** [comment]
looks like mapping table never got updated with DNs - have done this now at:
https://github.com/VirtualFlyBrain/Management/blob/master/Janelia/Janelia_terms_to_map.tsv
