### ISSUE TITLE
Add official abbreviations (symbols) for neurons

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#214]
It would be very useful to have official abbreviations/symbols for neurons and neuropils that are closer to those typically used in the literature.   Official symbols are useful could be boosted in search, displayed prominently in on TermInfo and used in situations such as float-over or a summary of connections where a shorter display name would be preferable.   This is an epic for grouping tickets relevant to this aim.

Note - long descriptive names are still useful for disambiguation - short names are often highly ambiguous outside of their usual contexts - DA1 might be a muscle, and tracheal system anastamosis or a neuron. 

User stories: 

* As a biologist I want to be able to see a short, familiar name for every neuron type I encounter on VFB so that I can quickly recognise it and assess whether I am interested to explore further.

* As biologist I want to be able to reliably search VFB with familiar short names for neurons and brain regions.
   - Note - this is already supported with synonyms, but we might consider boosting official abbreviations on autcomplete return lists

* As a biologist viewing summary information about synaptic connectivity, I want to see a compact representation grouping presynaptic connections, postsynaptic connections and displaying connection number (where known).

TBD - do we enforce uniqueness for these symbols across the ontology?  Across the nervous system?  Across entities of one type?

Adding an official symbol for every neuron is a very large job and so can only be done gradually, but we can partially automate this process by harvesting symbols from external resources.  For example, FlyLight has: 

![image](https://user-images.githubusercontent.com/112839/40418342-00697310-5e7a-11e8-85b3-45676f57a999.png)

(http://splitgal4.janelia.org/cgi-bin/view_splitgal4_imagery.cgi?line=MB002B10)

In other cases we could use the number &/or publication date of references attached to a synonym as a way to choose an official abbreviation.

**Comment by dosumis** [comment]
Other potential sources of official abbreviations: 

NeuronDB - curated resource from Kei Ito's lab.  We should be able to generate a list of names linked to references for these.

CATMAID dumps + short names used in papers publishing circuits from work on a CATMAID instance.

**Comment by dosumis** [comment]
All FlyLight names  should now be in as synonyms, except for descending neurons (TBA).  We need to go through and flag all of these as official synonyms.  I think the easiest way to do this would be with a new synonym type.  We have a few of these already:

![image](https://user-images.githubusercontent.com/112839/42102439-cf689b72-7bbd-11e8-938a-9727e6d75299.png)

(Note - most are inherited from GO, but 'BrainName official Abbreviation' is in use.)

Here's an example:

![image](https://user-images.githubusercontent.com/112839/42102505-feb783e8-7bbd-11e8-97d4-9fd3a1dbc754.png)

I think we need a new synonym type - maybe 'Official symbol'?  This should be used for all FlyLight abbreviation synonyms and all BrainName ones too. 

(@Clare72 )

**Comment by dosumis** [comment]
@Clare72  - where are we with this?  If I go down to [subticket on FlyLight symbols](https://github.com/flybase/drosophila-anatomy-developmental-ontology/issues/212) I can see a table of names and some pull requests that suggest these symbols are now synonyms.  Is this correct?

But I guess we still need to flag these synonyms as official symbols - either by annotating synonyms using synonym type - or by creating annotations under a new 'symbol' or 'abbreviation' annotation property.  If we do the same using NDB symbols, we should have a pretty extensive set of symbols to use for display for adult brain neurons.

**Comment by Clare72** [comment]
Yes, I think I added everything in the table as synonyms.
For the descending neurons we created a synonym type 'official symbol used on Virtual Fly Brain'
Would this be suitable?

**Comment by Clare72** [comment]
https://www.ebi.ac.uk/ols/ontologies/iao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000028

**Comment by Clare72** [comment]
So I should probably make 'symbol's for most terms in this table:
https://github.com/VirtualFlyBrain/Management/blob/master/Janelia/Janelia_terms_to_map.tsv

Some do not seem like great symbols: 'inner ring', 'outer ring', 'SIFamide' and 'descending neurons', should probably not be added.

Maybe we should have ' KC' after each Kenyon cell symbol?

I will convert spelled out greeks to unicode characters.

Should we have symbols duplicated as synonyms? My instinct is yes (unless they contain greeks), I think this will be easier to maintain than having to remove synonyms that get upgraded to symbols and if FlyBase can't use the symbols import, they still need the synonyms in there.

**Comment by Robbie1977** [comment]
I would also like the symbols to be duplicated in the synonyms; certainly for the time being anyway.

**Comment by Clare72** [comment]
Did a little test, and a greek-containing IAO_0000028 ('symbol') annotation turns in fbbt-edit.obo as:
>property_value: IAO:0000028 "MBON-β2β2'2a" xsd:string

This gets stripped out when the FlyBase version (fly_anatomy.obo) is made during a release, but makes it into other versions.
Adding it as an exact synonym instead (still using "MBON-β2β2'2a" with greeks) allows it get into fly_anatomy.obo.

**Comment by dosumis** [comment]
> This gets stripped out when the FlyBase version (fly_anatomy.obo) is made during a release, but makes it into other versions.

Yep - we filter all property_value tags.

**Comment by dosumis** [comment]
* Agree it is worth duplicating as synonyms as this will allow you to record where they come from.

* Also agree on not using long names from FlyLight

* I'm also having second thoughts about the MBON names in this list as official symbols (sorry!).   I now know more about this nomenclature than I did when I made the ticket.  It might be better to choose the numbered names as official  symbols  (e.g. MBON-01) and keep the more complex, descriptive names as synonyms (both with UTF8 greeks and spelled-out).

* Agree Kenyon cell symbols should end with KC.   Important to keep greeks in symbol in this case.

**Comment by Clare72** [comment]
A few terms in the table were incorrectly mapped, resulting in duplications - these are now fixed

**Comment by dosumis** [comment]
Trying to work out again where we are on this.

### sources of mapping

 - [Janelia-FlyLight terms](https://github.com/VirtualFlyBrain/Management/blob/master/Janelia/Janelia_terms_to_map.tsv)
 - [FlyBrain_NDB](https://flybrain-ndb.virtualflybrain.org/fmi/xsl/recordlist.xsl@-lay=NDB&-max=500&Public.op=eq&Public=yes&-find=-find&-sortfield.1=Category%20code&-sortfield.2=Pathway%20name.html) = IIRC we have a mapping table somewhere we could use for extracting symbols for these.

#### Other potential sources:

- Survey recent papers (pull from expression/phenotype curation)
- Expert consultation (see FCA work for a model of this)

### Implementation:

Use Robot templates to generate a table of axioms for merging to FBbt at release time. AP = 

https://www.ebi.ac.uk/ols/ontologies/iao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000028

**Comment by Clare72** [comment]
looks like I got to the point of making a template for adding symbols:
https://github.com/Clare72/coding-projects/tree/master/neuron_symbols/src

But haven't done synonyms yet

**Comment by Clare72** [comment]
Closing this issue now as symbols import is now being reliably generated (mostly using hemibrain symbols minus _a, _b, _c subtypes and also some flylight symbols).
Code on [flybase-ontology-scripts](https://github.com/FlyBase/flybase-ontology-scripts) repo
