### ISSUE TITLE
new term request: OL and subesophageal tracts/fascicles

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#217]
FBrf0232885 defines and characterises several tracts - summarised in Table 1

Optic lobe calycal tract 1-5 (OLCT)
subesophageal calycal tract 1-2 (SCT)

I think the recommendation is that these should be called fascicles rather than tracts?

**Comment by Clare72** [comment]
So looking through the ontology, a 'fascicle' is a subclass of 'ipsilateral tract' and several subclasses of 'fascicle' exist. There are also non-'fascicle' sub-classes of 'ipsilateral tract', several of which have the word "fascicle" in their name!

@dosumis is there a clear distinction between 'fascicle' and non-'fascicle' 'ipsilateral tract' classes?

From this paper, I think OLCT5 is not a 'fascicle', as it crosses the midline. Naming this one a tract and the other OLCTs fascicles would create consistency issues. I would prefer to use the names used by the authors.

**Comment by ah963** [comment]
Ito, 2014 - Systematic Insect Brain Nomenclature Document S1 II-1 suggests fascicle over tract

**Comment by Clare72** [comment]
This was duplicated in issue #350 and fixed by PR #570
