### ISSUE TITLE
update larval Hugin neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#229]
FBrf0234450 demonstrates that some of the larval hugin neuron subtypes (larval Hugin neuron of the protocerebrum, larval Hugin neuron of the pharynx & larval Hugin neuron of the ventral nerve cord) are cholinergic. This paper also has lots of EM connectivity data for all the larval hugin neurons (summarised in [supplemental file 1](https://elifesciences.org/download/aHR0cHM6Ly9jZG4uZWxpZmVzY2llbmNlcy5vcmcvYXJ0aWNsZXMvMTY3OTkvZWxpZmUtMTY3OTktc3VwcDEtdjIucGRm/elife-16799-supp1-v2.pdf?_hash=VhWGi2M4Wn8SMsE3nOlJAAav2RffF6t5jqFN2pQ1FlM%3D)).

**Comment by Clare72** [comment]
also see #230 to make PI neurosecretory cell subclasses

**Comment by Clare72** [comment]
This detail was added for ticket #371
