### ISSUE TITLE
New anatomy terms for various subsets of dorsomedial neurosecretory cells

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#230]
Related to https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/120

Should dorsomedial neurosecretory cells be divided into (adult and larval) subsets (similar to DH44) for other neuropeptides, such as insulin, Ms, etc?

(No specific references - but FBrf0234450 uses subsets defined by the nueropeptide and bases this on [Park, 2008)](https://europepmc.org/abstract/med/18365028)

**Comment by Clare72** [comment]
Yes, this was partially done whilst addressing #120 
Park 2008 = FBrf0210278 is not in the ontology yet, so I need to add anatomical information from this paper.
