### ISSUE TITLE
New term: Female-specific Ilp7 neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#237]
FBrf0222499 describes a female-specific set of adult dMP2 ILP7 neurons

Amend 'adult female posterior abdominal ganglion neuron' to capture identity as female-specific Ilp7 neurons, also new term needed for these neurons at the larval stage
Tidy up adult male Ilp7 posterior abdominal ganglion neuron, adult male posterior abdominal ganglion neuron and adult dMP2 ILP7 neuron definitions - some redundancy between them and posterior neurons form two distinct clusters, worth capturing?
Note also sexual dimorphism in neurotransmitter expression.

**Comment by Clare72** [comment]
I think this is FBbt:00110664 (has FBrf0222499 as cross ref), but this is perhaps not as clear as it could be - I will try to improve it.

**Comment by ah963** [comment]
Yes, it looks like it.

**Comment by ah963** [comment]
Updated original issue.

**Comment by Clare72** [comment]
Adult gender-specific ILP7 neurons don't exist until late third instar at the earliest and there is no information in this paper about the developing late larval/pupal cells, so I did not create extra classes for these.
All else is addressed.
