### ISSUE TITLE
New term request: hg1 & ps1 muscle and motor neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#240]
FBrf0223321 describes a sexually dimorphic wing muscle, hg1 and a monomorphic wing muscle, ps1, that are involved in courtship songs and the motor neurons that innervate them.

**Comment by Clare72** [comment]
flight muscles need synonyms - map from FBrf0098527 to Biology of Drosophila 475-479.
