### ISSUE TITLE
Update defintions of OSNs and Olfactory Glomeruli

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#241]
based on findings of FBrf0233453

**Comment by Clare72** [comment]
Note to self: OR83c-farnesol branch has some of these changes - needs to merge before working on this.

**Comment by admclachlan** [comment]
Can this now be added?

**Comment by Clare72** [comment]
Yes, I merged the branch I was working on, so doing this won't cause conflicts any more.
