### ISSUE TITLE
Update synonyms for FlyLight neurons 

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#252]
Related to #212 

Not all names used by FlyLight are listed as synonyms. The following synonyms are not yet in the ontology:

- [x] SIFamide is possibly a synonym for 'mushroom body calyx arborizing neuron 2'
- [x] T4 is a synonym for 'T neuron T4'
- [x] T5 is a synonym for 'T neuron T5' 
- [x] inner ring is a synonym for 'ellipsoid body inner ring'
- [x] outer ring is a synonym for 'ellipsoid body outer ring'
- [x] CSD is a synonym for 'CSD interneuron' - this might need tidied up a little too, one of the listed synonyms is 'adult serotonergic IP1-1 neuron' but there is an existing neuron called 'serotonergic IP1-1 neuron' that has an overlapping definition. 
- [x] gammamain is a synonym for 'gamma main Kenyon cell'
- [x] gammad is a synonym for 'gamma d neuron'
- [x] alpha/betac is a synonym for 'alpha/beta core Kenyon cell'
- [x] alpha/betap is a synonym for 'alpha/beta posterior Kenyon cell'
- [x] alpha/betas is a synonym for 'alpha/beta surface Kenyon cell'

I will add to this issue if/as I find more.

**Comment by Clare72** [comment]
Now merged - any new synonyms please open a new ticket
