### ISSUE TITLE
New term: PBG1–7.s-FB‘2.s-LAL.b-cre.b/PB1-glomerulus-FBe->IDFPHB-latera

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#260]
From FBrf0227801, the neuron called PBG1–7.s-FB‘2.s-LAL.b-cre.b/PB1-glomerulus-FBe->IDFPHB-lateralHB needs added to the ontology

Summarised:
Table 3A - line 12
Table 4

The synonym for SPS-PB neuron needs fixed - should be _PBG1/2-9.b-SPSi.s neuron_ NOT _PBG1/2-9.b-SPS.s neuron_

The synonym for CCP-VMP-PB neuron needs fixed - should be _PBG2-9.b-IB.s.SPS.s neuron_ NOT _PBG2-9.b-IB.s-SPS.s neuron_

**Comment by Clare72** [comment]
I think this is FBbt:00111433
This has synonyms 'PB1-glomerulus-FBe>IDFPL-HB-lateral' and 'PB1-glomerulus-FBe>IDFPL-HB-lateral'
I will add the general (non-L/R) synonym and the Wolff synonym.

**Comment by Clare72** [comment]
Guessing that this is no longer a priority since no new terms

**Comment by ah963** [comment]
thanks, looks like it
