### ISSUE TITLE
New term request: hunger regulating neurons?

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#264]
FBrf0234209 identifies a subset of gustatory receptor neurons (that may also be peptidergic/neurosecretory) in the central brain that regulate feeding motivation. They call these Taotie neurons 'after an ancient gluttonous ogre from Chinese mythology'.

**Comment by Clare72** [comment]
I don't think it is sensible to make a class for all cells covered by the taotie-Gal4 driver. The PI cells seem to be the interesting ones, but it isn't really clear how to distinguish these cells from the parent class, "neurosecretory cell of pars intercerebralis", except for Gal4 expression.
I will make adult and larval terms for "neurosecretory cell of pars intercerebralis" and the PI taotie neurons can be annotated with the adult term.
