### ISSUE TITLE
Pattern for fruitless clones needs fixing

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#274]
"adult fruitless aDT-g neuron"
EquivalentTo: neuron
 and (develops_from some 'neuroblast ALad1')
 and (expresses some fruitless)

> 

"adult fruitless aDT-g neuron"
EquivalentTo: neuron
 and (develops_from some 'neuroblast ALad1')
 and (expresses some fruitless)
 and ('part of' some adult)

subClassOf: 'part of' some 'adult fruitless aDT-a lineage clone'

Textual definitions should be re-written to start with the sentence: "Any adult, fruitless expressing neuron that develops from the ALad1 neuroblast. "

The rest of the definition should follow this sentence.  e.g. in this case

Any adult, fruitless expressing neuron that develops from the ALad1 neuroblast. These are all projection projection neurons that innervate the ipsilateral antennal mechanosensory and motor center (AMMC) zone A and project to the posterior lateral protocerebrum."

This should be done for all neuron types from the Cachero paper.  Worth looking into whether this is justified for any other fruitless clones.

**Comment by Clare72** [comment]
The lineage to type mapping does not seem to be in the Cachero et al. (2010) - FBrf0211926 paper, so I am not sure where this information came from.
There does not always seem to be a 1:1 mapping (i.e. one fru type from one neuroblast), so I am not sure that these logical definitions are justified.
This especially seems to be the case for type II neuroblasts, investigated by Ren et al. (2016) - FBrf0233706. We currently have pIP-a mapped to DPMl1 (PSp3), but in Ren et al. (2016) it is mapped to DL2 (CP3). Ren et al. (2016) also map pMP-e to DM4, but we currently map pMP-c to DM4, and they map both pIP-h and pMP-f to DM6 (CM1). For dopaminergic neurons they also specifically show that multiple neuroblasts can contribute to the same cluster and that one neuroblast can contribute to multiple clusters.
see #116

**Comment by dosumis** [comment]
May be worth pulling Greg and Marta into this discussion.  For hard to resolve cases, might be topic for mini-workshop on lineage.

**Comment by Clare72** [comment]
Lineage info may originally be from Yu et al. (2013) - FBrf0221412:
>We tentatively mapped major Fru-positive clusters onto those NB clones whose sexual dimorphism could be masked by the gross complexity (Table S1), but it is difficult to map fru clones containing only a few neurons. To unveil all sexually dimorphic or glia-producing neuronal lineages requires more detailed morphological analysis of not only entire clones but also their specific constituents.

Most (but not all) of our lineage relationships for fru neurons seem to be in that table
(all our fru neuron lineages `MATCH (a:Neuron)-[:develops_from]->(b:Neuroblast) WHERE (a)-[:SUBCLASSOF*]->(:Neuron {short_form:"FBbt_00016687"}) RETURN a.label, b.label ORDER BY a.label`)

**Comment by Clare72** [comment]
Looking back at some old issues - the way I would like to fix one this would be to relax all of these logical defs to SC axioms, as I am not convinced of the 1:1 NB to fru type mappings.

We could use DOSDP to generate the SC axioms and autogenerate defs for those that currently rely on "."

I would also like to obsolete all the fru clone terms - we do not have terms for other collections of neurons, e.g. dsx clusters, PAM, PPL clusters, so I think it is strange to have them for fru, but I think that is out of scope for this ticket and might require major retrofits of annotations...
