### ISSUE TITLE
postembryonic neuronal lineage paper (FBrf0224164) [sf#28]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#28]
@gm119
**Reported by gm119 on 2014-03-28 11:20 UTC**
I am curating a paper that describes "most postembryonic neuronal lineages in the Drosophila thoracic central nervous system".
## 
## Title:

   Transcription factor expression uniquely identifies most postembryonic neuronal lineages in the Drosophila thoracic central nervous system.
## 
## PMID: 24550109

They say they have 'constructed a gene expression map that enables the rapid, unambiguous identification of 23 of the 25 postembryonic lineages based on the expression of 15 transcription factors'.

I thought you might want to be alerted to this (!) as hopefully this can be used to make a nice set of terms for postembryonic neurons, plus I need a couple of specific anatomy terms to record phenotype from the paper.

The terms I need are for:

'3il axon bundle'
'3id axon bundle'
'lineage 3 postembryonic neuroblast clone'

I will attach my curation record so you can see where I need the terms.

**Comment by mmc46** [comment]
**Updated by mmc46 on 2014-06-02 14:13 UTC**
- **Milestone**: FB_2014_03 --> FB_2014_06

**Comment by mmc46** [comment]
**Commented by gm119 on 2014-07-29 15:24 UTC**
I'm going to submit the main part of my record now, minus the new FBbt terms.  Am happy to make the .edit record to add the FBbt terms once they are made.
This is what needs adding:

FBrf0224164

HGTX[D25]
3il?? | third instar larval stage

HGTX[Scer\UAS.cBa]
3id?? | third instar larval stage { Scer\GAL4[elav-C155] }

unc-4[Scer\UAS.cLa]
lineage 3 postembryonic neuroblast clone?? | third instar larval stage { Scer\GAL4[elav-C155] }

**Comment by Clare72** [comment]
primary and secondary lineages added in #750 (but not hemilineages or clones)

**Comment by Clare72** [comment]
appropriate term for this is probably 'lineage 3 secondary neuron' FBbt:00048918
