### ISSUE TITLE
new terms needed for motor neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#299]
related to https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/240
from fig 1E FBrf0223321
new terms for hg 2 motor neuron
hg 3 motor neuron
I2 motor neuron

**Comment by Clare72** [comment]
Hmm, not sure if there is really enough evidence for this - it is not clear from the picture whether the muscles are innervated by separate neurons or branches of the same neuron and they aren't really characterised in the paper.
Would you like a superclass - say 'fruitless-expressing flight muscle motor neuron'?

**Comment by ah963** [comment]
I think a superclass might be useful, but maybe just 'flight muscle motor neuron' given that the fru ones (and assuming there are fru negative neurons) may have sex specific differences?

**Comment by Clare72** [comment]
'flight muscle motor neuron' is FBbt:00047247

**Comment by ah963** [comment]
ahh, missed that, i'll use it instead

**Comment by Clare72** [comment]
Closing - no changes needed
