### ISSUE TITLE
New term: medial clusters of C4 da second-ordern interneurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#303]
FBrf0236440 describes a new cluster of neurons - medial clusters of C4 da second-order interneurons (mCSIs)

Term probably needed for C4 da neurons too.

**Comment by Clare72** [comment]
C4 da is "class IV dendritic arborizing neuron" FBbt:00007275
Added mCSI and segment-specific subclasses
