### ISSUE TITLE
Imaginal precursor

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#320]
FBbt:00005023 - "Imaginal precursor" definition states that it proliferates to produce an imaginal disc, but FBbt:00001761 - "imaginal disc" is a child term.

Need to look at usage and address this - maybe create an "imaginal tissue" term to encompass imaginal precursors and the discs they develop into.

What is the difference between FBbt:00005023 "imaginal precursor", FBbt:00001648 "embryonic imaginal precursor" and FBbt:00001760 "embryonic/larval imaginal precursor"?

**Comment by SianGramates** [comment]
My understanding is that "embryonic imaginal precursor" are imaginal tissues in the embryo that become larval imaginal or adult structures. "embryonic/larval imaginal precursors" include the imaginal discs and other larval imaginal tissues (imaginal rings, histoblasts, etc.). "imaginal precursor" is the is_a parent to both terms.

**Comment by Clare72** [comment]
So how much of this would you agree with?
 1. "embryonic/larval imaginal precursor" develops from "embryonic imaginal precursor"
 2. "embryonic/larval imaginal precursor" should perhaps be renamed to "larval imaginal precursor" or "late embryonic/larval imaginal precursor" (I think there also needs to be some discussion about embryonic/larval terms in general at some point)
 3. "imaginal precursor" should have its definition changed to be able to include developed imaginal discs as well as the tissues that produce them (! - probably better to do this using a new term, depending on how this has been used in curation)

**Comment by SianGramates** [comment]
1. Yes!
2. (I'm going to confess that I've never liked 'embryonic/larval'. It was an awkward compromise). I'd really like to **not** add "late embryonic/larval" anywhere. I support changing to "larval", but there's likely to be pushback.
3. I just checked; there's one allele (and its causative insertion" and two genes attached specifically to "imaginal precursor". Suggestion:A. rename to 'imaginal disc precursor' (existing curation should be attached to that; maintain existing definition), and add term 'imaginal precursor' with a definition that that includes the other imaginal tissues. OR B .leave 'imaginal precursor" with its existing definition, but change its relationships (develops_from to imaginal disc; drop is_a children), and make new term "imaginal tissue', assign that term the existing is_a relationships.Again, existing curation to exact term stays with original term.

It looks like there's several missing develops_from relationships.

**Comment by Clare72** [comment]
Thanks
2. for this term I think it will be fine to change to "larval" as it has not been curated to, I will just need to check that there are no embryonic terms below it or embryonic part_of or is_a statements above it.
3. I think a combination of the two is best - rename to "imaginal disc precursor" and remove some subclasses, then create "imaginal tissue" to replace "imaginal precursor"
4. I will also have a look through the whole section to check everything seems to be in the right place and add any missing relationships

**Comment by Clare72** [comment]
So if you remove non-disc terms, there is very little under "embryonic imaginal precursor" (only those already grouped under "imaginal disc primordium") and nothing under "embryonic/larval imaginal precursor". Since these haven't been used for curation, I think it is best to repurpose them as stage-specific "imaginal tissue" terms.
