### ISSUE TITLE
midgut part renamed without maintaining old names as synonyms

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#321]
I'm fairly confused as to why these terms were renamed at all, much less renamed without maintaining the old term as a synonym. I strongly believe the old terms ought be exact synonyms.

The embryonic constriction & chamber terms have a lot of curation attached them (i.e., are the sort of term that the expression curators are likely to be carrying in our heads). 

midgut chamber 1 ; FBbt:00000453 has changed name to embryonic midgut chamber 1. The old name is not a synonym.
midgut chamber 2 ; FBbt:00000454 has changed name to embryonic midgut chamber 2. The old name is not a synonym.
midgut chamber 3 ; FBbt:00000455 has changed name to embryonic midgut chamber 3. The old name is not a synonym.
midgut chamber 4 ; FBbt:00000456 has changed name to embryonic midgut chamber 4. The old name is not a synonym.
midgut constriction 1 ; FBbt:00000458 has changed name to embryonic midgut constriction 1. The old name is not a synonym.
midgut constriction 2 ; FBbt:00000459 has changed name to embryonic midgut constriction 2. The old name is not a synonym.
midgut constriction 3 ; FBbt:00000460 has changed name to embryonic midgut constriction 3. The old name is not a synonym.
midgut constriction ; FBbt:00000457 has changed name to embryonic midgut constriction. The old name is not a synonym.

The adult terms that have changed would, it seems to me, impact the groups working on single-cell RNAseq projects; the adult midgut is one of the tissues being analyzed by single-cell RNAseq. We've been trying quite hard to persuade the groups working on this to use valid FBbt terms; it seems like a bad idea to suddenly change terms names without leaving these groups the breadcrumbs of the old names retained as synonyms. You'd specifically mentioned  "adult midgut anterior region R3b" as an ambiguous term, but literature describes R3a and R3b as anterior, and R3c as posterior, so I'm not understanding what the ambiguity was.

adult midgut anterior region R3a ; FBbt:00110898 has changed name to adult midgut region R3a. The old name is not a synonym.
adult midgut anterior region R3b ; FBbt:00110899 has changed name to adult midgut region R3b. The old name is not a synonym.
adult midgut posterior region R3c ; FBbt:00110900 has changed name to adult midgut region R3c. The old name is not a synonym.

**Comment by Clare72** [comment]
The names for the chambers include the old names as part of the name - so these will still be picked up by any search. Other gut parts have stage-specificity in their name, so I thought it best for these to have it also.

R3 is the middle midgut (as any gut scientist should know!), so it is strange to refer to the subregions as anterior or posterior (without saying 'anterior middle midgut' or 'posterior middle midgut'). I would be happy to add "adult anterior middle midgut region R3a" and equivalent as synonyms if you think this will help curators, but I really think that anyone working with the gut (particularly for expression analysis) should be familiar with the work of the Lemaitre lab and the R.. terminology.

**Comment by SianGramates** [comment]
I was looking at what appears to be the paper that the nomenclature is based on, FBrf0221749, which states, "R3 could be subdivided into an anterior section containing copper cells (R3ab) and a posterior one (R3c) with large flat cells (LFCs)." It looks like the existing terms reflect that, that while R3b is between R3a and R3c, it, along with R3a, are part of the functionally distinct **and** anterior copper cell region of midgut R3, while R3c is the posterior flat cell region of midgut R3. 
It would be good to have a collective term for copper cell region (R3a and R3b together). Kind of wondering if the more correct choice for the terms to start with might have been "adult midgut copper cell region R3a" and "adult midgut copper cell region R2b".

The embryonic terms...we're unhappy with the idea of changing the names of terms that we've used often enough that we don't look them up every time we use them. In any case, if a term frequently used in annotation is changed, we always want  the old term as an exact synonym to the new term.

**Comment by Clare72** [comment]
I think for the term names, it is better to be consistent with "adult midgut region R.."

I would be happy to create "copper cell region" terms (and "large flat cell region" and "iron cell region" if you think these would be useful) - I didn't make these during the first pass to avoid bloating the ontology (needs general term + embryonic/larval + adult for each region).

As for synonyms, shall I add "adult anterior middle midgut region R3a", "adult anterior copper cell region R3a" (and equivalent for b and c)?

For the embryonic terms - I think it is clearer for new users to have the stage in the name (especially when this is the case for most other gut terms). If you think it is necessary for curators to have "midgut chamber X" as synonyms, I can add these.

**Comment by SianGramates** [comment]
The meta-issue with the adult midgut terms is that there is a large multi-lab single cell sequencing project that we are desperately trying to get to use valid FBbt terms. We (HarvCur) feel that it's only going to be harder to get such projects to be CV-compliant if we change the CV out from under them. I've done the exercise of expression-curating a couple of hundred GAL4 drivers where the authors used abbreviations of non-CV-compliant anatomy terms gathered from multiple sources (which ones I had to guess). It made a curator-time-intensive task much more time-intensive.

**Comment by Clare72** [comment]
Yeah, I get that it can be difficult to find the right terms sometimes - a lot of them are not very clear (names and definitions) and I am trying to improve this where I can.

In this particular case, "adult midgut anterior region R3a" sounds like a region of the anterior midgut, when it is actually a region of the middle midgut. I think that names like this are misleading and may result in curators selecting an incorrect term, which is why I am particularly reluctant to keep this (and the other two) in the ontology.

**Comment by Clare72** [comment]
R3ab (adult copper cell region) term now exists, so I don't think there are any changes to make from this ticket
