### ISSUE TITLE
Eggs and Oocytes

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#324]
- Need to add develops_from relationship to eggs.
 - Currently "unfertilized egg" is an "organism", which doesn't seem right to me. Perhaps it should be a "gamete".
 - Above point means that "egg" needs moving - either to "cell" or "anatomical structure", depending on whether we still want the term to apply after a few divisions or whether this would then be an "embryo".
 - Many of these terms need definitions.
 - Oocyte stages have 'deprecation warning' as comment - possibly due to overlap with fbdv. None of these "stage X oocyte" terms have been curated to, so perhaps I should go ahead and obsolete them - suggesting use of "oocyte" instead?

**Comment by SianGramates** [comment]
Oocyte stages (as anatomy terms) also have no attached definitions, so they're not terribly useful (in contrast to oogenesis stage terms, which have very informative definitions; if you decide to un-deprecate the FBbt oocyte stages, you can just grab the FBdv definitions.). I think it could be argued than an unfertilized egg is a gamete, and should have a develops_from relationship with oocyte. The egg part_of children are distinct from the oocyte part_of children (and appropriately so; the oocyte parts change dramatically during oogenesis).

Fertilized egg stage/fertilized egg is the very beginning of embryonic stage 1/stage 1 embryo (immediately precedes embryonic cycle 1, which is the first mitotic cell cycle after fertilization).

**Comment by ANiknejad** [comment]
Dear FlyBase Team,

The current classification of FBdv:00005288 'fertilized egg stage ' as a child of FBdv:00005286 'egg stage' does not fit with the developmental stages defined by Uberon. For sake of consistency with Uberon developmental stages, FBdv:00005288 'fertilized egg stage', which (as far as we understand) is the zygote stage, should have the relationship part_of  FBdv:00005289 embryo stage, to be then classified as a child of UBERON:0000068 ! embryo stage
