### ISSUE TITLE
rename of neuroepithelial cell (not retained as synonym)

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#330]
I'm uncomfortable with not retaining  the term used in the definitional reference (FBrf0193624 ) as a synonym (I very much prefer the new name).

neuroepithelial cell ; FBbt:00111738 has changed name to optic lobe neuroepithelial cell. The old name is not a synonym.

**Comment by Clare72** [comment]
As for midgut chamber - the old name is included in the new name, so I didn't think it necessary to keep, but happy to add back.

**Comment by SianGramates** [comment]
Thanks Clare!
