### ISSUE TITLE
serotonergic abdominal neuron changed name; not retained as synonym

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#336]
serotonergic abdominal neuron ; FBbt:00110975 has changed name to larval serotonergic abdominal neuron. The old name is not a synonym.

Please add adult abdominal serotonergic neuron (with is_a children FBbt:00111305 adult dorsal posterior ILP7 (male) neuron and FBbt:00110663 serotonergic abdominal giant (male) neuron). Add back sertonergic abdominal neuron as is_a parent to larval serotonergic neuron and adult serotonergic neuron

**Comment by SianGramates** [comment]
My thought was it's good to have a term to use when authors are unspecific; are we sure 'serotonergic abdominal giant (male) neuron" covers all the adult serotonergic abdominal neurons (are there none in female adults)?

**Comment by Clare72** [comment]
Not at all, but that is all that is currently in the ontology. Which makes me feel that it is premature (but perhaps not unnecessary) to have a grouping term. If there is such a paper, which would ideally show and name more types of adult abdominal serotonergic neuron (but non-specific may suffice, especially if present in females), I can add the terms.

**Comment by Clare72** [comment]
closing this issue - new ticket can be made if new terms needed based on publications in future
