### ISSUE TITLE
Problems with latest release files

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#341]
Relationships seem to be screwed up in http://purl.oblibrary.org/obo/fbbt/fbbt-simple.obo

has_part and part_of are not RO.

Many RO relations are just blank declarations - missing all content.

Needs further investigation.

**Comment by dosumis** [comment]
Hmmm - something weird going on when loading from PURL in Protege.  Locally loaded file is fine, as is one using the address that the PURL resolves to!.  But  I repeatedly see this problem when using PURL. - i.e. seems to be a Protege bug - perhaps loading incomplete OBO file?

**Comment by Clare72** [comment]
Closing - this does not seem to be an FBbt issue
