### ISSUE TITLE
Add missing Ohyama neurons

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#346]
Some terms from Ohyama et al., 2015 - FBrf0228257 never made it into the ontology, and many are missing segment-specific terms.
See https://github.com/VirtualFlyBrain/Management/issues/57

Add terms missing from [this spreadsheet](https://github.com/VirtualFlyBrain/VFB_owl/blob/master/data/Ohyama2016_neurons_annot_file.tsv) to ontology and fill in the table.

**Comment by ah963** [comment]
note to self @ah963 - check expression curation of FBrf0228257 to see if it can use new terms

**Comment by Clare72** [comment]
Missing general classes - A00c added (and a3 version).
hook-2, telegoro, A08h, Telephone-1 and Basin-related descending neuron-1 do not seem to be mentioned in this paper (main or supplementary) - perhaps they are described somewhere else?

**Comment by Clare72** [comment]
The terms that were not added here were ones that I could not find in the paper.
Not sure how sensible it would be to make a brief description of the shapes and reference the VFB individual IDs. It isn't really the ideal way of adding terms, but if it is holding up high priority work, maybe it could be a solution?

**Comment by Clare72** [comment]
Closing this as remaining terms are not in the publication
