### ISSUE TITLE
Larval connectomics papers - urgently need anatomy curation

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#351]
dataset.short_form | paper
-- | --
Burgos2018  |  FBrf0238464
Eichler2017 |   FBrf0236359
Larderet2017  |  FBrf0237760
Schlegel2016 |   FBrf0234450
Takagi2017 |   FBrf0237618
Gerhard2017  |  FBrf0237057

**Comment by ah963** [comment]
just to note Schlegel2016 | FBrf0234450 has been curated and was in the last FlyBase release

**Comment by Clare72** [comment]
We need to decide on a threshold for adding synapsing data - is one synapse in one brain sufficient to add this to the class? Do we want L/R consistency? Should be able to do this by modifying the script made for Jovanic synapsing in PR #273 

I can just add the terms for now without connectomics info, but this is something that needs thinking about.

**Comment by dosumis** [comment]
Related image curation: https://github.com/VirtualFlyBrain/Management/issues/159

**Comment by mmc46** [comment]
L/R consistency should definitely be considered, at least until there are more datasets that can be used for comparison.
At an individual level, we'd usually ignore things with less than 3-5 synapses, but this depends a lot on neuron type, total number of inputs/outputs. So there isn't a fixed threshold, it depends on the context. You should also consider, when available, functional data.

**Comment by ah963** [comment]
Larderet2017 | FBrf0237760 now curated for expression
