### ISSUE TITLE
INCA cell

### ISSUE THREAD

**Issue by Robbie1977** [FlyBase/drosophila-anatomy-developmental-ontology#352]
For new term requests, please provide the following information:

## Preferred term label

INCA cell ?

THis is a neuropeptide secreting cell assoc with trachea.    Only cell of tracheal system we have that is recorded as secreting neuropeptides = peritracheal cell.  Don't know if this is related

e.g. see http://www.jneurosci.org/content/24/17/4283

**Comment by Clare72** [comment]
Comment on "larval peritracheal cell" FBbt00006017:
>There seem to be processes that connect the three cells (Laneve et al., 2013). The peptidergic cell is referred to as Inka (or INKA or PM) cell (O'Brien and Taghert, 1998; Laneve et al., 2013) and it expresses dimm and Phm (Hewes et al., 2003). This cell is also labelled by the Aplysia peptide myomodulin just prior to ecdysis (O'Brien and Taghert, 1998).

Sounds like we need subclasses for the different types of peritracheal cell
