### ISSUE TITLE
Attribute learning and memory to MB cell type classes?

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#354]
The following (non-exhaustive) list of papers attribute specific learning and memory phenomena to individual cell types in the mushroom body:
FBrf0226572
FBrf0235522
FBrf0228475
FBrf0227330

**Comment by Clare72** [comment]
Yes, this is definitely possible. There are GO terms that can be imported into the ontology. The first two are examples of 'olfactory learning' GO:0007616 (associating an odour with the presence of water), which has already been imported. The third has 'short term memory' and anesthesia-resistant memory' (both in GO) and the fourth has 'long-term memory' (already imported).
These functions could easily be added to existing classes.

**Comment by ah963** [comment]
FBrf0238232 attributes antagonistic memory forming roles to CRE positive and CRE negative gamma kenyon cells.
