### ISSUE TITLE
Overlaps between sibling terms FBdv:00000054 cleavage stage and FBdv:00005290 pre-blastoderm stage [sf#36]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#36]
**Reported by fbastian on 2014-07-11 00:16 UTC**
FBdv:00000054 cleavage stage has children embryonic stages 1-4. FBdv:00005290 pre-blastoderm stage has children embryonic stages 1-3.

So FBdv:00000054 and FBdv:00005290 are clearly overlapping, yet FBdv:00005290 is not part_of FBdv:00000054, and cleavage stages 1-3 have part_of relations to both. Is it intended? 

Thanks.

**Comment by mmc46** [comment]
**Commented by mmc46 on 2014-07-11 14:26 UTC**
I've corrected this. The next release will be on the 7th August.

**Comment by mmc46** [comment]
**Commented by fbastian on 2014-07-12 03:43 UTC**
Thanks.

**Comment by mmc46** [comment]
**Updated by mmc46 on 2014-07-15 09:26 UTC**
- **status**: open --> closed

**Comment by mmc46** [comment]
**Commented by anneniknejad on 2014-10-27 15:48 UTC**
Hi Marta,

I re-open this issue.

http://svn.code.sf.net/p/fbbtdv/code/fbdv/releases/latest/fbdv.obo

In this version (it is the latest one, right?) we have

id: FBdv:00000054
name: cleavage stage
def: "A collective term for stages 1-4." [FBC:DOS]

this term is parent of only one child:
id: FBdv:00005290
name: pre-blastoderm stage
def: "Embryonic stage 1-3." [FBC:DOS]

As you can see, definitions do not fit the ontology structure, and also because there is only one child, maybe 'cleavage stage' and 'pre-blastoderm stage' can be merged?


Thanks in advance for taking care of that.
Best regards,

Anne

**Comment by mmc46** [comment]
**Updated by mmc46 on 2014-11-17 10:18 UTC**
- **status**: closed --> open

**Comment by mmc46** [comment]
Hi Anne,

The latest is here
https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/tree/master/fbdv/releases

'pre-blastoderm stage' is part of cleavage stage, not a child. Can you check if your issue is alreaady solved please?

**Comment by Clare72** [comment]
Looks like this is fixed - closing
