### ISSUE TITLE
"morning" and "evening" neurons (might be new terms, might be synonyms to existing terms)

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#362]
FBrf0208444 makes reference to a couple of subsets of pacemaker neurons, "morning" (M) and evening (E) cells. From the introduction to this reference:

Approximately 150 pacemaker neurons in the adult Drosophila brain are implicated in the regulation of circadian locomotor behavior. These neurons can be roughly divided into the PIGMENT DISPERSING FACTOR (PDF)-expressing small and large LNv (sLNv, lLNv), a single non-PDF sLNv, the dorsal lateral neurons (LNd), and three groups of dorsal neurons (DN1, DN2, and DN3) [FBrf0183981]. Ablation of PDF+ neurons results in substantial reduction in morning anticipation [FBrf0123172],[FBrf0179740]. A functional clock in the small subset of PDF+ neurons is sufficient to drive morning behavior, and these cells have thus been dubbed “morning” (M) cells [FBrf0179741]. The large LNv have been observed to promote arousal especially during the light period [FBrf0207380],[FBrf0206340],[FBrf0207206]. A subset of ∼30 circadian pacemaker neurons, including the non-PDF sLNv, LNd, and/or a small subset of DN1s and DN3s [FBrf0179740],[FBrf0179741],[FBrf0167403],[FBrf0195358], are essential for evening anticipatory behavior, and are thus dubbed “evening” (E) cells.

**Comment by dosumis** [comment]
Quite a few talks on this at NeuroFly.  I don't think there are any new neurons, but we might want to make two new classes - one to group morning pacemaker neurons and one to group evening ones.   These could be logically defined using new terms from GO (probably need to be requested).

**Comment by Clare72** [comment]
There is already a class for 'LN PDf neuron' FBbt:00003762, so could add 'morning cell' as a synonym and maybe this GO term:
GO:0010841 - positive regulation of circadian sleep/wake cycle, wakefulness

There is also a negative regulation GO term, but I would need to look into "evening" behaviour and see if it is appropriate.

**Comment by dosumis** [comment]
Be careful with the positive and negative reg terms here.  There are peaks of activity in the morning and evening.  I could be wrong but think the E cell may also control that increase in activity before sleep.  If so I think negative reg would not be appropriate.

**Comment by SianGramates** [comment]
Just checking in on this ticket (I've been going through proformae in my 'hold for anatomy' folder).

**Comment by Clare72** [comment]
This is not currently a priority ticket - if it is a blocker for something important we can bump it up with the 'priority for next release' label(?)
(The next update of FBbt in chado will be 02 Apr 2020)

**Comment by Clare72** [comment]
Looking at FBrf0208444 and a more recent paper (FBrf0235909), I don't think that these cells can be defined logically like that. 'Morning' and 'evening' cells are non-overlapping sets of particular pacemaker neurons. FBrf0208444 is actually showing that 'evening' cells are involved in morning behaviour, but this does not qualify them as 'morning cells'.

'adult morning cell' and 'adult evening cell' should probably be new terms with manually specified children based on papers from the last 5 years or so (I get the impression that the groups have been refined a little since FBrf0208444 - 2009).

**Comment by Clare72** [comment]
Looks like 'evening cells' are the LNds and the Pdf negative s-LNv - adding a new class
'Morning cells' is only the Pdf s-LNvs - this can be a synonym

This is stated explicitly in FBrf0243753:
>two sets of clock neurons that control circadian locomotor activity: Pdf+ s-LNvs comprise the ‘morning oscillator’ and control the morning peak of activity, while the 5th s-LNv and LNds comprise the ‘evening oscillator’ and control the evening peak of activity

It is also partially stated/strongly implied in other recent refs FBrf0234230, FBrf0235909, FBrf0231110, FBrf0233350

FBrf0208444 includes l-LNvs as morning cells, but this is quite clearly not the case in recent papers.
FBrf0208444 includes some DN1s and DN3s as evening cells, I found one recent paper (FBrf0233224) where some DN1s were included based on older refs, but mostly DNs were not included, so I won't classify any DNs as evening cells.

**Comment by Clare72** [comment]
fixed by #899
