### ISSUE TITLE
Automate clean up of FBbt for loading into FlyBase

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#363]
This ticket lists requests from HarvDev and describes how we can fix them

The following can all be done with grep -v or sed:

   - In header, change tag default-namespace: "fly_anatomy.ontology" to default-namespace: "FlyBase anatomy CV”. 
   - Delete all lines starting with tag "owl-axioms:”
   - Delete all lines with tag "property_value:”
   - Delete all lines with tag "expand_expression_to:”
   - ^xref: OBO_REL:part_of   -> xref_analog: OBO_REL:part_of
   - ^xref: OBO_REL:has_part -> xref_analog: OBO_REL:has_part

This can be done manually in the editor's file, as none of these should be there:

  - Delete full typedefs containing tag namespace: “gene_ontology"

I'm not sure how best to support this.  It might be possible to use a ROBOT filter that explicitly names the offending object properties

  - Delete full typedefs containing tag "is_obsolete:”

Additional changes required:

  -  Typedefs used to define APs on the ontology (header tags in OBO) may also need to be removed.

**Comment by dosumis** [comment]
First set fixed in #364 (actually the script was already doing most of what was needed so request form HarvDev may have been out of date).

@Clare72: For  "Delete full typedefs containing tag "is_obsolete:”"  - This could be done with a [ROBOT remove command](http://robot.obolibrary.org/remove).  The crude way to do this would be to find the offending terms and specify them for removal.  But it looks like we might be able to specify objectProperties flagged as obsolete using the SELECT subcommand.  Can you look into this?  

I think we can close the ticket once this is done and the gene_ontology Typedefs are removed from fbbt-edit.obo.

**Comment by Clare72** [comment]
Remove and filter aren't working for me in latest (1.2.0-alpha-1) robot version - no errors, they just don't make any changes. Filter seems to be working in 1.1.0 (no remove in this version), but it works a bit differently, I can pull out one of the typedefs, but also get all the classes (not clear how to avoid them in this version). The only way I have successfully managed to remove the typedefs is to manually create a file with them and use unmerge (not ideal).
I would like to run the release soon, so don't really have any more time to troubleshoot this. I will just delete them manually for now and come back to this later (maybe next stable release of robot).

**Comment by dosumis** [comment]
> I would like to run the release soon, so don't really have any more time to troubleshoot this. I will just delete them manually for now and come back to this later (maybe next stable release of robot).

OK.  Thanks for trying.  Can you also submit tickets on the Robot tracker detailing these problems?

**Comment by Clare72** [comment]
Ok, it might be that the whole 1.2.0-alpha isn't working for me, will have to test further. 1.1.0 is running as expected (behaviour of filter was changed for 1.2.0-alpha-1).

I can confirm that everything above this step (in original ticket) is now correct when I generate fly_anatomy.obo

**Comment by Clare72** [comment]
After a bit more robot experimentation, I managed to find a way to get the obsolete typedefs out.

These typedefs also need to be removed (I currently have to do this manually):

[Typedef]
id: cc-attributionURL
name: attributionURL
xref: http://creativecommons.org/ns#attributionURL
is_metadata_tag: true

[Typedef]
id: dc-creator
name: creator
xref: http://purl.org/dc/elements/1.1/creator
is_metadata_tag: true

[Typedef]
id: dc-rights
name: rights
xref: http://purl.org/dc/elements/1.1/rights
is_metadata_tag: true

I'm not sure where these come from - I see them when I open fly_anatomy.obo in Aquamacs, but I can't find them in Protege. I don't know what they are, which makes it difficult to work out how to get them with filter/remove.

**Comment by dosumis** [comment]
The Typedefs above are annotation properties that are used to define tags in the OBO header.   If it is possible to filter annotation properties with Robot then it should be safe to strip these out in fly_anatomy.obo.

**Comment by dosumis** [comment]
The AP IRIs are 

 http://purl.org/dc/elements/1.1/creator

etc

**Comment by Clare72** [comment]
These typedefs are each removed individually (by IRI) using ROBOT
