### ISSUE TITLE
Update descriptions and synonyms of small field neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#368]
FBrf0235702 adds more detail to the descriptions of what they call E-PGs and P-ENs, synonyms need added too. 
However, they say E-PGs are eb-pb-vbo neuron/EB-IDFP DSB-PB 1 glomerulus neuron/EB-IDFP VSB-PB 1 glomerulus neuron but these have separate entries in the ontology, not clear if they are using E-PG as a synonym for all of them?
P-EN and 'shifting neurons' are synonyms for pb-eb-no neuron but then also use P-EN1 and P-EN2 to describe (overlapping?) subclasses o fP-EN neurons

**Comment by Clare72** [comment]
synonyms and merges done while addressing other central complex tickets
some detail has been added, but much redundant with newer papers (already curated)
