### ISSUE TITLE
FBdv terms with missing relations preceded_by or starts_at_end_of [sf#37]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#37]
**Reported by fbastian on 2014-07-11 01:04 UTC**
The following FBdv terms have no temporal relations: FBdv:00005315 embryonic cycle 15 and FBdv:00005316 embryonic cycle 16.

**Comment by mmc46** [comment]
**Commented by djs93 on 2014-07-11 12:11 UTC**
This is deliberate. Cycles of nuclear division during embryonic development are synchronous across the entire embryo up to the end of cycle 13.  They can therefore be used to stage embryos.  Subsequent divisions are synchronous within local domains but highly asynchronous between domains. Over the whole embryo cycles 14 15 and 16 overlap.

**Comment by mmc46** [comment]
**Updated by mmc46 on 2014-07-11 13:19 UTC**
- **status**: open --> closed

**Comment by mmc46** [comment]
**Commented by fbastian on 2014-07-12 03:41 UTC**
And yet if a cycle 16 of cell division occurs somewhere in the embryo, it has to have been preceded by a cycle 15, isnt't it? I understand it is not possible to have temporal relations to embryonic developmental stages, but you could have relations between these cycles.

Also, I'm stuck with ordering FBdv stages using precedence relations. Is it possible simply by using relations between stages, or is it necessary to use the temporal ordering in comments? (:/)

**Comment by mmc46** [comment]
**Updated by mmc46 on 2014-07-15 09:28 UTC**
- **status**: closed --> open

**Comment by mmc46** [comment]
**Commented by djs93 on 2014-07-15 09:54 UTC**
Timings are implicitly relative to some process.  Timing relationships in FBdv are relative to the life of the whole animal.  Because cycles 0-13 are synchronous, they can be used to divide up the life of an embryo and so the timing relations make sense as being relative to the life of the whole animal, just as they do between stages. Cycles 14-16 occur at different times (relative to the life of the animal) in different domains - cycle 16 doesn't even happen in all cells.

I'm reluctant to mix in timing relations that are defined with reference to a different relative processes.  This is especially so if some timing relations between cycles refer to the life of the whole animal and some to the life of any one cell.

**Comment by mmc46** [comment]
**Commented by fbastian on 2014-07-15 11:35 UTC**
I understand what you mean. Then: 

- shouldn't you remove the existing relation FBdv:00005312 embryonic cycle 14 starts_at_end_of FBdv:00005309 ! embryonic cycle 13?
- couldn't you simply add the precedence relations from cycle 15 to cycle 14, and from cycle 16 to cycle 15? The precedence relations would be "break" at cycle 14, if it has no other relations.

**Comment by dosumis** [comment]
> * shouldn't you remove the existing relation FBdv:00005312 embryonic cycle 14 starts_at_end_of FBdv:00005309 ! embryonic cycle 13?
> * couldn't you simply add the precedence relations from cycle 15 to cycle 14, and from cycle 16 to cycle 15? The precedence relations would be "break" at cycle 14, if it has no other relations.

That would work.
