### ISSUE TITLE
Visual System

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#375]
Adding to this ticket as directly related to functional systems:
There is no "visual system" in FBbt:

Current structure under sensory system:

|__sensory system
           |___chemosensory system
               |____gustatory system
               |____olfactory system
           |__hygrosensory system
           |__mechanosensory system
               |____auditory system
           |__thermosensory system

It would be good to have this grouping wrt aligning ourselves with the Alliance and for our own phenotype/expression summary ribbons.

_Originally posted by @hattrill in https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/57#issuecomment-407763445_

**Comment by Clare72** [comment]
I think it is best to categorise this using the function GO_0050953 "sensory perception of light stimulus" rather than GO_0007601 "visual perception", to include non-image-forming functions.

**Comment by SianGramates** [comment]
I'm surprised at this resolution. We urgently need "visual system" for the AGR expression ribbon.

**Comment by gildossantos** [comment]
Adding an "urgent" label at Sian's request while she waits for access to the GitHub FlyBase repos.

**Comment by SianGramates** [comment]
It looks like I misinterpreted your comment; OLS indicates that "visual system" FBbt:00047735 was indeed made.

**Comment by Clare72** [comment]
Yes, visual system was made - using GO_0050953 "sensory perception of light stimulus" in logical definition.
