### ISSUE TITLE
Add synonym to Va neuron

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#378]
'Va neuron' FBbt:00110116 appears to be sometimes referred to as "Capa neuroendocrine cell" References: FBrf0217221 (Fig 5), cites FBrf0146873

**Comment by Clare72** [comment]
"capa neuroendocrine cell" refers to a superclass (now added - FBbt:00047737), including a pair of neurons in the subesophageal ganglion (also added - FBbt:00047738).
I have also added some other synonyms and relationships found in these papers.
