### ISSUE TITLE
General neuropil grouping terms needed

### ISSUE THREAD

**Issue by bevmatthews** [FlyBase/drosophila-anatomy-developmental-ontology#381]
For new term requests, please provide the following information:

## Preferred term label
larval dorsomedial neuropil
larval centromedial neuropil
larval ventrolateral neuropil
larval ventromedial neuropil
larval central neuropil

May have missed it but we seem to have terms for e.g.
central neuropil of [every larval segment] but no grouping term.
Expression data is rarely defined in specific segments and one can't assume that it applies to all so a grouping term is needed.

## Suggested parent term
ventral nerve cord synaptic neuropil subdomain

**Comment by bevmatthews** [comment]
The thing that I would like to able to capture and distinguish is that expression occurs in the ventrolateral neuropil as opposed to the dorsomedial, centromedial, ventromedial, or central neuropil (for example). That's why I think there should be the term larval ventrolateral neuropil in addition to having ventrolateral neuropil of larval (every individual segment).

Any place that specific terms like this are listed individually for each segment without a generic (but still specific) grouping term are not useful for expression curation.

**Comment by Clare72** [comment]
Revisiting this ticket just now - I think the appropriate terms for this use case are the ones I previously suggested - "__ subdivision of ventral nerve cord"
I will add your suggested labels as synonyms

**Comment by bevmatthews** [comment]
Hi Clare,

Sorry not to respond sooner. I agree with your solution.
The necessary terms were already there but since you added the synonyms I
will be more likely to find them.

Thanks,
Bev
