### ISSUE TITLE
Group terms needed for leg taste bristle chemosensory neurons

### ISSUE THREAD

**Issue by bevmatthews** [FlyBase/drosophila-anatomy-developmental-ontology#382]
## Preferred term label
leg taste bristle chemosensory neuron
leg taste bristle ascending tarsal chemosensory neuron 
leg taste bristle segmental tarsal chemosensory neuron

Again the CV is too specific and does not have the needed group terms
We have, e.g.
prothoracic leg taste bristle chemosensory neuron
mesothoracic leg taste bristle chemosensory neuron
metathoracic leg taste bristle chemosensory neuron

but that is too specific for expression curation.
Need the more inclusive terms

**Comment by Clare72** [comment]
I have added the terms.
If you use sensillum/sensory neuron terms a lot, you might also want to comment on #311 
I'm thinking about changing the relationship between sensory neurons and sensilla (probably won't happen soon).
