### ISSUE TITLE
Sensory neurons in the CNS

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#394]
![image](https://user-images.githubusercontent.com/112839/46810445-9da61400-cd68-11e8-8be5-77ca45474aaf.png)

We need to fix these:

LNs are not sensory
ORs should not part_of CNS.

once they're fixed, we should add suitable disjointness axioms.

**Comment by Clare72** [comment]
ORs sorted in PR #549 

It will be a bigger job to get the disjoint in.
All nerves are currently part_of PNS, with some also being part_of CNS.
Some classes under nerve (e.g. 'cervical connective') probably shouldn't be there given the definition of nerve.
Also need to look at nerve-associated glial cells.

**Comment by Clare72** [comment]
Moved disjoint issue to its own ticket #1043 
The rest of this is done, so closing
