### ISSUE TITLE
New term: prefollicle cell

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#395]
## Attribution: FBrf0233947

NOTE: I'm not solidly convinced about the need for this term: I'm basing this request on this bit of text from the above reference:
The formation of new follicles during early oogenesis requires proper differentiation in the FSC lineage. This begins in the germarium (Fig. 1 B) with a pair of FSCs at the region 2a/2b border (FBrf0084162; FBrf0202474) that divide regularly to self-renew and produce prefollicle cell (pFC) daughters. Upon exiting the niche, a subset of pFCs begin to differentiate into polar and stalk cells (FBrf0090659; FBrf0151279; FBrf0209788), which facilitate follicle budding, while the remaining pFCs differentiate into main body follicle cells (FCs) that surround the developing germline cyst. This well-defined lineage makes it possible to identify the stem cell and distinct stages of differentiation in vivo with single-cell resolution

**Comment by SianGramates** [comment]
Yet more info in FBrf0234236

**Comment by Clare72** [comment]
Sounds reasonable (and will be quick to do).
