### ISSUE TITLE
'somatic cell of ovary' - definition and daughter terms

### ISSUE THREAD

**Issue by vmt25** [FlyBase/drosophila-anatomy-developmental-ontology#404]
This comes from an email discussion (Clare, then Victoria)

>On 17 Oct 2018, at 09:08, Clare Pilgrim <cp390@cam.ac.uk> wrote:

>3. "somatic cell of ovary" FBbt:00006030 relationships to move to become 
a logical definition, i.e. any "somatic cell" that 'part of' some 
"ovariole" == "somatic cell of ovary". I think this may have been 
intended in the first place, as the current definition is ".", which 
only works with a logical definition.

>This conflates ovary, ovariole, and egg chamber (developing egg that is still in ovariole).  Somatic cells that are part of the ovariole are the muscle sheath cells - see http://flybase.org/reports/FBrf0202672 for some work characterizing those cells.  The daughter terms that "somatic cell of ovary" includes are all somatic cells that are part of an egg chamber, which is a parent term for them. All FCs cells exist in ovarioles, but are part of an egg chamber inside the ovariole, and will make it into a egg that can be laid, whereas cells of the ovariole never will.  "Somatic cell of egg chamber" would describe those daughter terms without referring to the ovariole at all.  "Somatic cell of ovary" would include the muscle sheath cells and the neurons that control them, which is not included in the daughter terms for FBbt:00006030.

When I think of an ovariole I always imagine the production line of egg chambers and completely ignore the muscle sheet. I believe that this is how most researchers think about it (maybe all of us all wrong). Extrapolating, when I think of a 'somatic cell of ovary’ I think of the somatic cells of the ovariole (germarium, egg chambers, and stalks and not of the muscle sheath.

Therefore, I would be more comfortable with excluding the ovarian sheet (and making it clear in the definition).
Otherwise, make muscle non-muscle daughter terms, although it will risk becoming a bit absurd:
Somatic cell of ovary
	ovarian sheet
	non-somatic cell associated with the female germline? non-muscle sheet somatic cell of the ovary? Blah!

Anyways, if we exclude the muscle sheet, the term is still missing the following daughter terms:
1. hub cell (there is already a term, which is specific for the male gonad - wrong!)
2. cap cell
3. escort cell

**Comment by Clare72** [comment]
From Victoria:
>Specifically saying that this does not include muscle sheath would be a straightforward fix, and the daughter terms would then make sense.  99% of researchers are interested in cells that are in (or connecting) egg chambers & the stem cells that make them, and that will help those people get the information that they expect to see.  Great idea, thank you!

>Escort cell  FBbt:00006049 and cap cell FBbt:00004868 are listed under germarium currently.  Is it possible to have them show up under another category as well, or do all terms need to have only one "parentage"?  Thank you!

**Comment by Clare72** [comment]
If the muscle sheet is not generally considered to be part of the "ovariole", I can move the "ovarian sheath" FBbt:00004896 to be part of the "ovary" instead, so that is would not be picked up by ['part of' some ovariole].
"escort cell" and "germarium cap cell" are already picked up by ['part of' some ovariole] (since "germarium" is 'part of' "ovariole"). I can also make a "female hub cell" term (if you could point me towards a reference for this, that would be helpful).
Should we then rename the term "somatic cell of ovariole"?

**Comment by SianGramates** [comment]
I think ticket #393 might be related to these issues.

**Comment by Clare72** [comment]
Based on FBrf0216027, it looks like a hub cell is the male equivalent of a cap cell, so I have not added a female hub cell term.
