### ISSUE TITLE
New Term/Synonym from Fly Brain

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#416]
New terms/synonyms from http://flybrain-ndb.iam.u-tokyo.ac.jp

See new terms need column in .xlsx from https://github.com/VirtualFlyBrain/Management/issues/148

**Comment by Clare72** [comment]
From spreadsheet:

From FBrf0205263:
Kenyon cells (ACX), MB-C3

From FBrf0174482:
mALT (DL1), mALT (VA6), mALT (DA1/DC3/VA1d), mALT (DM1/VA4/VC1)
mALT (VM2) probably adult antennal lobe projection neuron VM2 adPN
Also see #358 FBrf0219809

From FBrf0210154:
PFS1 + PFS2 (pontin neuron P1 +2?), PB1

Not published but referred to in FBrf0230403:
CT02, CT03, CT34, CC1, CC2

Others:
H1 - FBrf0051327
FD1 - no obvious publication
vCal1 - no obvious publication
LPL01 - FBrf0240358 (DONE)

JONs (done on separate ticket)

**Comment by Clare72** [comment]
Not adding MB-C3, CT02, CT03, CT34, CC1, CC2, FD1 or vCal1 at this time due to lack of available evidence.

**Comment by Clare72** [comment]
Closing this issue as the remainder will be covered by #495
