### ISSUE TITLE
New terms: neurons of the chemosensory organs of the larval terminal organ

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#419]
I'm not solidly convinced on the necessity of this request.

FBrf0236934 maps the sensilla and neurons of the gustatory external sensory organs for the larval terminal organ. It looks like the sensilla are already identified and named (distal group terminal organ sensillum FBbt:00002691 and its children; dorso-lateral group terminal organ sensillum FBbt:00002706 and its children). It looks like this paper maps neurons to the TO sensilla (individuating them with GAL4 drivers). Some of the neurons they map are mechanosensory rather than chemosensory.

**Comment by ah963** [comment]
This seems to refine the findings referred to in this ticket
