### ISSUE TITLE
Remove dead links from ontology

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#428]
As far as I can tell, this is just the flybrain links - http://flybrain.neurobio.arizona.edu/...
These need removing and replacing with (ideally) appropriate FBrf references if not in place already

**Comment by ah963** [comment]
FBrf0240283 is a PC for the flybrain expression data, you could always cite this It will be in the next FB release.

**Comment by Clare72** [comment]
Ref is currently been used for anatomy info - cell types, neuropil details etc.
Would this be covered by the PC?

**Comment by ah963** [comment]
@gm119 would know

**Comment by dosumis** [comment]
The FlyBrain site dates from the 90s (I believe Douglas wrote some of the original in emacs!).  It seems that it is no longer live and there's no obvious ref to replace. I'd just delete.

**Comment by Clare72** [comment]
Yeah, if there are alternate refs in place, that is fine, but some terms would be left without a reference.

**Comment by dosumis** [comment]
We should probably look for alternate refs for these.

**Comment by Clare72** [comment]
Also http://www.neuro.uoregon.edu/doelab/neuro/... links
