### ISSUE TITLE
Improve definition of adult SIFamide cell of pars intercerebralis

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#430]
FBrf0236047 provides more anatomical detail about the extent these neurons project within the nervous system  - Fig1A and 1B
also some split gfp/fucntional connections data in figs 2, S2, 4, S3, S4, S5, S6 & S7

**Comment by Clare72** [comment]
No subclasses are named/identified and nothing seems to be applicable to all SIF neurons, so can't add any relationships. Closing issue.
