### ISSUE TITLE
GABA-ergic antennal lobe projection neurons

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#435]
"Inhibitory responses were occasionally observed when stimulating glomerulus DA1 or VA1v (Figure 2D). Notably, these are the only two glomeruli that contain GH146-positive GABAergic PNs in addition to GH146-positive cholinergic PNs (Jefferis et al., 2007, Lai et al., 2008, Marin et al., 2002, Wong et al., 2002) (Figure S5)." [Jeanne et al., 2018](https://www.cell.com/neuron/fulltext/S0896-6273(18)30383-0)

We don't have any records for GABA-ergic PNs.  From this, it looks like we should.

**Comment by Clare72** [comment]
Not quite sure what you were asking for - I have added functionality to the two classes in question (was already in description).
There are now 2 GABA-ergic PNs in the AL and 2 in the AMMC.
