### ISSUE TITLE
Merge terms: Lv1+Ld fru neurons are fru+ lobula columna neurons LC10? New term for fruitless expressing LC10a neurons?

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#436]
FBrf0239559 asserts that the fru+ Lv1 and Ld neurons (collectively described as Lv1+Ld, FBbt term is adult fruitless pIP-d neuron) in FBrf0205974 (Fig1E & Table S1) are the same neurons as the LC10, or more likely a subset of LC10a, described in FBrf0228418 (fig3D - LC10a), FBrf0193607 (Summarised Table1 - LC10) and FBrf0234700 (fig2 & supplement - LC10).

If there's not enough evidence to merge, FBrf0239559 provides evidence through intersections with fru-FLP that a subset of LC10a are also fruitless expressing neurons so perhaps there should be a new term for this?

**Comment by Clare72** [comment]
From the other references, I can't find any evidence/assertions that Lv1+Ld (pIP-d) == LC10.
I wonder whether FBrf0239559 meant that their identified neuron class belongs to both of these groups, rather than that the two groups are identical?
