### ISSUE TITLE
New terms for larval and adult local interneurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#437]
FBrf0239187 described larval and adult local interneurons and how some of the former develop into the latter

**Comment by Clare72** [comment]
Some description added to FBbt:00007226 and FBbt:00007390, but they don't properly define any new subclasses (other than by Gal4 driver).
Decided not to add group 1, 2 and 3 neurons as this cannot be matched with any existing classes at this time.
Added larval cell body rind regions (but used FBrf0216269 positions for subregions)
