### ISSUE TITLE
Cleaning up xrefs - URLs should go if poss

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#439]
1. All current URLs should be tested to see if they still resolve & those that don't should be deleted. 
1. We should follow a standard DB:accession pattern for all xrefs if poss 

e.g. 

http://www.normalesup.org/~vorgogoz/FlyPNS/PNSdescription.html#vch2

=> FlyPNS:vch2

We store the expansion FlyPNS -> http://www.normalesup.org/~vorgogoz/FlyPNS/PNSdescription.html# in a standard mapping file.  See - https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

We should make our own db-xrefs.yaml file for mappings not covered by the GO db-xrefs.yaml.

Note - we may not be able to completely abolish raw URLs, as, IIRC, OBO format won't allow blank accessions - making it hard to support links to the homepage of some resource.  But (a) maybe we just shouldn't do this & (b) it may be possible to support with longer accessions, e.g.

FlyPNS

http://www.normalesup.org/~vorgogoz/FlyPNS/PNSdescription.html#vch2
http://www.normalesup.org/~vorgogoz/FlyPNS/PNSdescription0.html

=> 
FlyPNS:PNSdescription.html#vch2
FlyPNS:PNSdescription0.html

FlyPNS -> 
http://www.normalesup.org/~vorgogoz/FlyPNS/

**Comment by dosumis** [comment]
The following Cypher query on [pdb](http://pdb.virtualflybrain.org/browser/) finds all the offending URLs:

```cql
MATCH (c:VFB:Class)-[:has_reference]->(n:pub) where exists(n.http) RETURN distinct n.http
```

It would be pretty simple to script a check for HTTP return status.

**Comment by Clare72** [comment]
see also #428

**Comment by dosumis** [comment]
I'd like to make the FlyPNS xrefs sometime soon as I've now got code that can generate linkouts directly from xrefs.   All we need is a Site node in our Neo4J DB with information about FlyPNS.

e.g. here's the one we made for DoOR:

``` json
{
  "link_base": "http://neuro.uni-konstanz.de/DoOR/content/receptor.php?OR=",
  "xref_db": "DoOR",
  "iri": "http://neuro.uni-konstanz.de/DoOR",
  "link_icon_url": "http://neuro.uni-konstanz.de/DoOR/navi_pic.jpg",
  "short_form": "DoOR",
  "description": [
    "Database of Odorant responses."
  ],
  "label": "DoOR"
}
```

Can you spec something similar out for FlyPNS?

**Comment by Clare72** [comment]
Based on VC:
`create (S:Site:Individual) set S.short_form = "FlyPNS" set S.label = "FlyPNS" set S.link_base = "http://www.normalesup.org/~vorgogoz/FlyPNS/" set S.description = [" Database of the D. melanogaster embryonic and larval peripheral nervous system."] set S.iri = "http://www.normalesup.org/~vorgogoz/FlyPNS/page1.html"`

Would the "xref_db" also need adding as "FlyPNS"?
And will this do for the logo ("link_icon_url")?
![FlyPNS_logo](https://user-images.githubusercontent.com/38460997/57385795-fe84b600-71aa-11e9-8d44-11158159ba3f.png)

**Comment by dosumis** [comment]
Added.  @Robbie1977 - OK to use above as icon?

One other thought. We should probably link this site node to the pub on their home page:

FlyPNS, a database of the Drosophila embryonic and larval peripheral nervous system. BMC Dev Biol. 2005, 5:4. Medline. PDF

(Clare: I can show you how to use library methods to add this next time we meet).

I don't think this will show up yet, but will be ready to use if we make a TermInfo for Site nodes.

**Comment by Robbie1977** [comment]
@dosumis @Clare72 Only issue with the icon is it is only a big red font on their site (not an image). We could create an image copy (as you have above) but we would have to host ourselves or we simply just don't add an icon until they add one.

**Comment by Clare72** [comment]
all replaced where possible now
