### ISSUE TITLE
equivalence -> xrefs - a step backwards? [sf#44]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#44]
**Reported by djs93 on 2014-12-18 17:16 UTC**
It feels like a step backwards to switch equivalence axioms (which have defined semantics) to xrefs (which don't): https://sourceforge.net/p/fbbtdv/code/591/

Wondering what the motivation is and if there is some alternative that will solve the same problem.  Perhaps just move the equivalence axioms out into a bridge file?

Cheers,
David

**Comment by mmc46** [comment]
**Commented by mmc46 on 2014-12-18 17:22 UTC**
I changed it because I'm getting an error for equivalent classes on the build for a jenkins job to update GO in FBdv. Would that be solved by a bridge file?

**Comment by mmc46** [comment]
**Commented by cmungall on 2014-12-29 20:27 UTC**
Which job is this?

If the error is coming from Oort, you can say --allow-equivalent-pairs

Aside: you have a typo in one of your replacements (xerf not xref)

**Comment by mmc46** [comment]
**Commented by mmc46 on 2015-01-02 11:46 UTC**
Thanks Chris, adding --allow-equivalent-pairs solved it, so the job (to update GO terms in FBdv) works, after I've reverted the changes to the equivalent_to axioms.

However, the equivalent_to axioms in fbdv-merged.obo have changed to xref. I was expecting them to be unchanged from equivalent_to, so that I could save fbdv-merged.obo (with updated GO) over fbdv-edit.obo ahead of the ontology release process. Is there a way around it in Oort?

**Comment by dosumis** [comment]
The simplest solution would be to get rid of named equivalent classes and just use BFO.  I was always worried that this would break FB ontology browsing - which I believe makes assumptions about IDs.  Could try checking on that again.  (Then again - I seem to remember we have another use case for named equivalent classes in FBcv (mutagen links to ChEBI) that is likely harder to solve.

**Comment by Clare72** [comment]
This is no longer an issue with new odk release process.
