### ISSUE TITLE
Update descriptions of Pdf neuron close to tritocerebrum, EH neuroscretory neuron and adult CCAP neuron

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#442]
FBrf0238423 has a lot of new detail on the following neurons (summarised table 2)

Pdf neuron close to tritocerebrum - pharate & adult stages
EH neurosecretory neuron - post larval stages - note current definition of this term implies larval specific, should be changed
adult CCAP neuron - pharate adult stage

**Comment by Clare72** [comment]
new subclasses of CCAP neurons and new class for adult EH neuron as well as description edits
