### ISSUE TITLE
New terms for lateral horn neuron types?

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#443]
FBrf0239324 describes 39 lateral horn neuron types by morphology and identifies their various inputs (these vary significantly within and between neuron types)
see also
https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/435

**Comment by Clare72** [comment]
The 39 types are based on clustering analysis (NBLAST) and are not defined well in words.
They have limited intra-group similarity in the AL projection neurons that target them and the odours they respond to.
I don't think it is possible to make classes for these without more information for the definitions.

Making term for 'adult lateral horn neuron'
