### ISSUE TITLE
New collective terms for leg GRNs

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#446]
Currently there are terms for individual leg GRNs (mesothoracic, metathoracic and prothoracic leg taste bristle chemosensory neuron) but often authors won't specify which leg they see expression in, recording it only as leg bristle expression (e.g. FBrf0240321). A collective term for 'leg taste bristle chemosensory neuron' would be useful for these situations.

**Comment by Clare72** [comment]
Looks like I already did this in #389
'leg taste bristle chemosensory neuron' will be FBbt:00047767
