### ISSUE TITLE
Update S cell/New term for sugar sensing leg neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#448]
The definition of S cell is specific to the labellum, however sugar sensing neurons (which express Gr5a) are also found in the legs. These don't have a specific term to describe them. Should the S cell definition be changed to incorporate these, or a new term created for them? See FBrf0225125 for a description of leg neurons and an example of these being sugar sensing is also in FBrf0240321 - Sfig4

**Comment by Clare72** [comment]
This needs a new term, in fact we are missing all of the specific leg sensillae and neurons from FBrf0225125, including 5b and 5s (tested in FBrf0240321).

**Comment by ah963** [comment]
not to self @ah963 , this information is captured as a compound term in FBrf0225125 using S cell. This will need fixed if the decision is to change this.
