### ISSUE TITLE
wing hinge primordium definition edit

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#458]
I think there is a copy-paste error in the definition of "wing hinge primordium"
"wing blade" should be changed to "wing hinge"

FBbt:00006033 - wing hinge primordium
>Region of dorsal mesothoracic disc that will develop into the wing blade. Its boundary is delimited by folds in the third instar disc epithelium."

FBbt:00006029 - wing pouch:
>Region of dorsal mesothoracic disc that will develop into the wing blade. Its boundary is delimited by folds in the third instar disc epithelium. The cells in this region can also be distinguished from surrounding cells in the third instar disc by their basal accumulation of lipid granules. The wing pouch is bisected by the anterior-posterior compartment boundary of the disc.

**Comment by SianGramates** [comment]
I think whoever entered the definition just put in the wrong word.  I'm looking at a wing fate map  (in the Held imaginal discs book, page 138), and  I've been curating the fate map region labeled "hinge" as "wing hinge primordium (it roughly forms a ring around the wing pouch), I agree that the solution is to change "wing blade" to "wing hinge" in the definition. I'm emailing you an image.
