### ISSUE TITLE
Missing assertions of synaptic terminal locations on adult CSD

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#460]
![image](https://user-images.githubusercontent.com/112839/49869223-afa74000-fe07-11e8-8d2d-8b36b6ddd6e6.png)

![image](https://user-images.githubusercontent.com/112839/49869209-a4541480-fe07-11e8-87d2-adeed018df56.png)

Def: "A large serotonergic interneuron of the adult brain whose cell body is located close to the antennal lobe, whose dendrites innervate the antennal lobe in the same hemisphere as the cell body and whose axons innervate the contralateral antennal lobe and higher brain centers including the mushroom body cortex, the dorsal horn and the posterior superior protocerebrum. There are only two CSD interneurons per brain (one cell body per hemisphere)."

More recent papers map to MBCalyx & LH and 'lateral protocerebrum'  - see figure 1 here: https://neuraldevelopment.biomedcentral.com/articles/10.1186/1749-8104-2-20

Looking at the one example we have on VFB suggests protocerebral arborization  = SLP &  SMP

https://v2.virtualflybrain.org/?i=VFB_00017894,VFB_00014123,VFB_00030900,VFB_00030614,VFB_00030623,VFB_00030838,VFB_00030629

Both formal assertions and textual definition need updating.  'dorsal horn' and PSP are outdated (pre BrainName standard) terms.

**Comment by Clare72** [comment]
If this looks okay, please close, otherwise suggest improvements to this version.

**Comment by Clare72** [comment]
Closing as no additional improvements suggested
