### ISSUE TITLE
collective term for chemosensory neurons of the labral sense organ

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#464]
There's no way to refer to a generic chemosensory neuron of the labral sense organ, only. The ontology includes chemosensory neuron of adult labial sensillum 7, chemosensory neuron of adult labial sensillum 8, and chemosensory neuron of adult labial sensillum 9, but there's no parental term to refer to them collectively, or when it's not clear which is meant.

I'm looking at FBrf0151944, figure 3, panel D

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

**Comment by ah963** [comment]
There's a term for labral sense organ neuron FBbt:00004026

'Sensory neuron that innervates the adult labral sense organ of the adult pharynx. There are 18 of these, 8 mechanosensory and 10 gustatory receptor neurons.'

If a specific term for chemosensory neuron is created, it's probably worth creating one for the mechnosensory neurons as well.

**Comment by SianGramates** [comment]
Agreed re: mechanosensory neurons.
