### ISSUE TITLE
combine terms: dopaminergic PAM neuron 1 and adult fruitless aSP13 neuron

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#465]
dopaminergic PAM neuron 1 and adult fruitless aSP13 neuron are the same neuron, currently PAM neuron 1 is the child of aSP13. In the source reference for dopaminergic PAM neuron 1 - FBrf0227179 (table1) - it is stated they are the same. Later publications also use these terms interchangeably, e.g. FBrf0238058.

**Comment by ah963** [comment]
via email

> I propose to keep "fruitless aSP13 neuron", as this is favoured by the 
>     more recent paper FBrf0238058.
> 

Personally, I think the better term is “dopaminergic PAM neuron 1” as fits with the nomenclature used to describe other neurons in the PAM cluster. 

I suppose it comes down to if it’s better to describe a neuron by function/location or by lineage.

**Comment by Clare72** [comment]
Yeah, I don't really have a strong opinion on which term to keep, happy to go with “dopaminergic PAM neuron 1”

**Comment by SianGramates** [comment]
I'm comfortable with keeping “dopaminergic PAM neuron 1” and making "adult fruitless aSP13 neuron" (and any of its existing exact synonyms) an exact synonym.
