### ISSUE TITLE
Possible rename: adult cell body glial cell

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#466]
Term is currently 'adult cell body glial cell' FBbt:00100501, with is_a parents 'cortex associated CNS glial cell' FBbt:00001297 and 'adult CNS glial cell" FBbt:00100499. It has part_of relationship to 'adult brain cell body rind' FBbt:00003625 and  'glial mesh' FBbt:00100503.

The definition of this term is "Glial cell of the adult that is associated with the cortex of the brain..", and it has the existing exact synonym "adult cortex associated glial cell".

I'm wondering if it ought be renamed "adult cortex associated glial cell" or "adult cortex associated CNS glial cell". The definition of 'adult brain cell body rind' is "Superficial layer of the brain, composed of glia and the cell bodies of neurons (soma).", suggesting to me that the 'cell body' part of that term is intended to refer to the neuronal cell bodies present in that tissue, rather than to the glial component, so it seems like the term  'adult cell body glial cell' is named for its neighboring cells, rather than for itself.

The reference I'm looking at, FBrf0240164],  states "An adult Drosophila brain contains five major glial subtypes: perineurial, subperineurial, cortex, ensheathing, and astrocyte-like glia (FBrf0234767, FBrf0206543)".  I had to do a bit of digging to figure out that what this paper calls "cortext glia" (expressing marker NP2222-GAL4) almost certainly maps onto the non-obviously named 'adult cell body glial cell'.

**Comment by ah963** [comment]
Note: this overlaps with #366

**Comment by Clare72** [comment]
Cell body glia are a subtype of cortex glia (they enclose neuronal cell bodies), but are the only cortex glia in drosophila (other insects have more) - FBrf0082171, making the terms synonymous for our purposes.
I agree that the parent class should be consistent with the children, but I would be inclined to do this the other way around (make all "cell body" rather than "cortex") to maintain this specificity. I think it is also a good idea to avoid the word "cortex" as suggested in the brain nomenclature paper FBrf0224194.
I will update definitions and synonyms a bit too.

**Comment by Clare72** [comment]
@ah963 - use of "cortex associated CNS glial cell" and "adult cell body glial cell" appear to be mostly for expression - any preference for which should be name vs synonym?

**Comment by SianGramates** [comment]
I understand what you're saying, but still think it's not a great idea for FBbt terms to be in conflict with how researchers in the fly community are referring to these cells. I think it makes searching harder than it needs to be for our users (autocomplete doesn't work for synonyms; and sometimes the Vocabularies/Expression search interfaces fail to recognize synonyms. I've answered help mails from users who've run up against the latter, and have seen it happen myself. I think there must be some easily accidentally changed browser setting in play).

There's nothing in the name 'adult cell body glial cell' that suggests to me that I've found the cortex glia.

**Comment by SianGramates** [comment]
Having two competing names that are both being actively used in the community does make this much more problematic! That said, I do in fact like the idea of incorporating both terms into the name: how about "adult cortex associated cell body glial cell" or "adult cell body cortex associated glial cell"?
