### ISSUE TITLE
Attribute behaviour to descending neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#471]
Descending neurons identified by FBrf0239335 (see #345 ) are starting to have behavioural function attributed to them. I will use this ticket to add references for this should you want to record this in the ontology via GO terms.

FBrf0240068 attributes freezing behaviour to descending neuron of the posterior brain DNp09

**Comment by Clare72** [comment]
For this it is probably best to do on a paper by paper basis, rather than trying to collect them and do them together -> leaving this as single paper ticket rather than converting to EPIC.
