### ISSUE TITLE
New and updated dsx clusters

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#478]
FBrf0228365 describes dsx-GAL4 expression using MARCM and the researchers identify new clusters of dsx neurons, provide male/female cell counts for existing clusters while also using some new synonyms (summarised table S1)

NOte that they claim pmn2 is fmale specific and that pmn3 ( a new cluster in males) isn't a male homologue of this.
adult doublesex SN (male) neuron is also (sometimes) present in the female - the current description states it disappears during pupal develppment in the female - maybe it would be best to rename this 'adult doublesex SN neuron'.
'adult doublesex TN2 (male) neuron' - not mentioned in this paper, but see FBbt refs - is also described as disappearing in pupal development in the female  - could also be renamed 'adult doublesex TN2 neuron'

**Comment by ah963** [comment]
'adult doublesex TN2 (male) neuron' - not mentioned in this paper, but see FBbt refs - is also described as disappearing in pupal development in the female - could also be renamed 'adult doublesex TN2 neuron'

**Comment by Clare72** [comment]
Wondering if (female) pMN2 and (male) pMN3 from Kimura et al., 2015 -  FBrf0228365 (shown to be distinct clusters), were both considered to be pMN2 by Robinett et al., 2010 - FBrf0210735, who claimed there was no dimorphism.

This would mean that pMN2 in the male (expression curation) is actually the pMN3 from Kimura et al., 2015. Current expression curation for pMN2 is based on Robinett et al., 2010 - FBrf0210735 and Zhao et al., 2014 - FBrf0225543 (Both same research group).

The best way to fix this might be to obsolete the current term, create the gender-specific pMN2 and pMN3 terms from Kimura et al., 2015 -  FBrf0228365, with pMN2 as a broad synonym for pMN3 and change the expression curation statements for the male to pMN3 and for the female to the new pMN2 term.

**Comment by Clare72** [comment]
>adult doublesex SN (male) neuron is also (sometimes) present in the female - the current description states it disappears during pupal develppment in the female - maybe it would be best to rename this 'adult doublesex SN neuron'.
'adult doublesex TN2 (male) neuron' - not mentioned in this paper, but see FBbt refs - is also described as disappearing in pupal development in the female - could also be renamed 'adult doublesex TN2 neuron'

FBrf0228365 gives an average count of 0.2 +/- 0.1 per female for SN neurons. I will make a term for the female SN2 neuron as it is found in ~20 % of 'wild-type' females.
For TN2, I would like to see similar evidence that they are sometimes seen in the adult female before making a term.
