### ISSUE TITLE
Change name: embryonic/larval somatic muscle

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#492]
embryonic somatic muscle AND embryonic/larval somatic muscle are separate terms - suggest either combining them or changing embryonic/larval somatic muscle to larval somatic muscle.

**Comment by SianGramates** [comment]
As much as it pains me to say this, as I've always disliked the embryonic/larval terms, I have to object to this proposal. I'm looking at the Atlas of Drosophila Development, pp 38-39 (the Volker Hartenstein pamplet): myoblast fusion is complete at the end of stage 13, so it's then correct to speak of 'embryonic somatic muscle'; but the larval muscle pattern isn't complete until dorsal closure. So embryonic/larval somatic muscle is appropriate for late embryonic, and all larval, stages: the parts are continuously existing.

**Comment by ah963** [comment]
Ahh, that's good to know. Maybe it would be better to expand the definitions to capture this information.

Atlas of Drosophila development is FBrf0064803
