### ISSUE TITLE
New term: MBIN-e1

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#496]
FBrf0236359 describes MBIN-e1 at L1 & L3 stages. This is currently missing from FBbt

**Comment by Clare72** [comment]
FBrf0238440 (Saumweber et al., 2018) supplementary fig 1 has some neurons that are not in the main table (supplementary table 1). These are stated to be larval stage specific in this paper, but for at least one (MBIN-e1), this disagrees with Eichler et al., 2017 - FBrf0236359.

Add these terms and make comments about stage.
