### ISSUE TITLE
larval mushroom body output neuron b1 and b3 have the same synonym

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#497]
larval mushroom body output neuron b1 and larval mushroom body output neuron b1 both have the synonym 'MBON-b1'. Is this correct?

**Comment by Clare72** [comment]
No, this looks like a copy-paste error. Fixed directly on master branch.
commit 3531b6817884551aaa4178998dc1fc8ddb8b6221
