### ISSUE TITLE
Should we have a general class for Mushroom Body Output Neuron (MBON)

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#501]
see Aso2014 FBrf0227178

**Comment by Clare72** [comment]
FBbt:00047953

**Comment by Clare72** [comment]
It is FB_2019_01. There has been a bit of a gap between FBbt releases, as FB_2018_06 version was early in the cycle (early October) and FB_2019_01 version was late in the cycle (mid January).
