### ISSUE TITLE
Leucokinin neurons should be renamed

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#503]
The following neurons;

adult Leucokinin ABLK neuron of the abdominal ganglion
adult Leucokinin SELK neuron of the subesophageal zone
adult Leucokinin LK anterior neuron
adult Leucokinin LHLK lateral horn neuron
larval Leucokinin ABLK neuron of the abdominal ganglion
larval Leucokinin SELK neuron of the subesophageal zone
larval Leucokinin LK anterior neuron
larval Leucokinin LHLK lateral horn neuron

could all be renamed as the LK refers to Leucokinin and the other two letter part of the abbreviate refers to the anatomical region, e.g ABLK refers to Abdominal Ganglion LeucoKinin so is redundant within the term - 'adult Leucokinin Abdominal Ganglion LeucoKinin  neuron of the abdominal ganglion'

Suggest using 'adult ABLK neuron', etc, for each term, already present as a synonym

**Comment by Clare72** [comment]
keeping unabbreviated names, but removing redundant abbreviations and reordering to better reflect naming scheme in paper (and word order of abbreviations)
