### ISSUE TITLE
new term:ipc-2a

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#504]
FBrf0211291 describes ipc-2a neurons

**Comment by bevmatthews** [comment]
This paper is now on my to do list after having requested thin curation from Aoife. Waiting for the ipc-2a neurons.
Thanks.

**Comment by Clare72** [comment]
also other ITP neurons from FBrf0204742 (including ipc-2 parent class to ipc-2a)

**Comment by bevmatthews** [comment]
Wow! Thanks for the rapid turnaround.
