### ISSUE TITLE
Synonym suggestion: limb primordium

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#510]
We've recently run across several papers in which genes are described as being expressed in the "limb primordia"  (or between the limb primordia) at embryonic stages, when what is meant is dorsal thoracic disc primordium FBbt:00001653 and ventral thoracic disc primordium FBbt:00001657, collectively (that is, all six primordia at once). Could "limb primodium" be added as a synonym to both terms?

**Comment by Clare72** [comment]
Might be better to make a superclass - could you give an example reference where it is used?

**Comment by dosumis** [comment]
> that is, all six primordia at once

6 = dorsal and ventral discs for pro, meso, meta 

Referring to legs as limbs seems reasonable if non-standard.  Wings... maybe.  Halteres seems like a stretch.  There is no prothoracic dorsal appendage. 

The terminology is sufficiently non-standard that I'd rather have it as a synonym.  If you want a grouping term then perhaps 'thoracic appendage primordium' (all thoracic discs except dorsal pro) with 'limb primordium' as a narrow synonym?  Or perhaps just group legs under 'leg primordium' and add synonym there?

**Comment by Clare72** [comment]
>We've recently run across several papers

Please can you list a few example FBrfs?

**Comment by SianGramates** [comment]
References in support: FBrf0091309, FBrf0183907, FBrf0239510

**Comment by Clare72** [comment]
Based on FBrf0183907, 'thoracic limb primordium' sounds like a precursor of the disc primordia (and Keilin's organ). Made a new term to reflect this.
