### ISSUE TITLE
New term:  DSK neuron

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#517]
FBrf0219451 describes expression of the neuropeptide DSK in a small number of previosuly uncharacterised larval and adult neurons and a subset of IPCs.

**Comment by Clare72** [comment]
DSK cells in PI are a large subset of the IPCs (not clear how these are distinct, except for expression)
Other cells, not really studied in FBrf0219451:
>In addition, we found DSK-immunolabeling and Gal4 expression in interneurons in other parts of the protocerebrum and subesophageal ganglion (Figure 1A2), also shown by Nichols et al. (Nichols and Lim, 1996; Nichols et al., 1997a,b).

Characterised here (1995 paper):
https://link.springer.com/article/10.1007%2Fs004410050518

**Comment by Clare72** [comment]
Adding general adult/larval classes for DSK neuron and PI DSK neurons as subclasses of PI IPCs.

If detailed subclasses from FBrf0085661 are required, this should be a new ticket.
