### ISSUE TITLE
Defecation terms

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#521]
New terms from FBrf0226857
Including 'larval rectal sphincter', 'anus sensory neuron' and merge of two terms for adult rectal sphincter FBbt:00003147 and FBbt:00003541.

**Comment by SianGramates** [comment]
I approve the suggestion to merge FBbt:00003147 "adult rectal sphincter" and FBbt:00003541 "rectal circular muscle".
