### ISSUE TITLE
Brain definitions

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#526]
Current definition of FBbt:0005095 'brain':

>The supra-esophageal ganglion of the central nervous system, composed of three primitive ganglia known as protocerebrum, deutocerebrum and tritocerebrum. In the context of Drosophila it refers to the pre-oral ganglionic mass of the central nervous system containing the ventral ganglia.

The second sentence of this is not very clear, I think it is trying to say that the central nervous system includes the ventral ganglia, but it sounds as though the brain includes the ventral ganglia!

The first sentence seems inaccurate for the adult; the subesophageal zone should also be included according to the Brain Name paper (FBrf0224194). Other terms in the ontology assume it is included in the adult brain e.g. FBbt:00014013 'adult gnathal ganglion':
>Region of the adult brain beneath the esophagus, consisting of the fused ganglia of the three gnathal neuromeres: mandibular, maxillary and labial.

For the adult, I would like to include subesophageal/gnathal ganglia in the definition for consistency within the ontology and with Ito et al., 2014 (FBrf0224194). I would also like to make it clear that the thoracico-abdominal ganglion is excluded.

For the larva, it is less clear whether anything below the esophagus should be considered to be part of the brain or not, but larval gnathal neuromeres are currently asserted to be part of the brain in the ontology, making this inconsistent with the definition of 'brain'. However, some definitions include them in the VNC e.g. FBbt:00007703 'centromedial subdivision of ventral nerve cord':
>A centro-medially located longitudinal subdivision of the larval ventral nerve cord spanning the gnathal, thoracic and abdominal segments to abdominal segment 8. An axial plane just dorsal to the intermediate commissures and CITd (`C1 fascicle` [FBbt_00005905]) specifies the dorsal boundary of this domain. A virtual axial plane intersecting the ventral centro-intermediate tract (CITv) and the VMT (`ventro-medial tract` [FBbt_00001646]) forms the ventral boundary of this domain. (CITv encompasses `CI2`[FBbt_00005906] and `CI3`[FBbt_00005907]).

It may make more sense for the larval brain to exclude anything subesophageal, as implied by the current 'brain' definition, in which case some other definitions and relationships will need fixing.

**Comment by dosumis** [comment]
> The supra-esophageal ganglion of the central nervous system, composed of three primitive ganglia known as protocerebrum, deutocerebrum and tritocerebrum. In the context of Drosophila it refers to the pre-oral ganglionic mass of the central nervous system containing the ventral ganglia.

Ughhh - this is a legacy definition from before my time.  Agree the last sentence must go.  Also supra-esophageal is too restricted (see below).

Note: As far as we can assign structures to proto, deuto and tritocerebrum, the latter is (partially?) subesophageal.  

Re larva vs adult:
  - Most or all usage of the term brain referring to adult includes the gnathal ganglia (subesophageal)
  - Most or all usage of the term brain referring to lava excludes the gnathal ganglia, making them part of the VNC.

**Comment by ah963** [comment]
The definition should be broadened to make clear that glial cells, for example adult brain perineurial glial cell, are part of the brain - right now it seems ambiguous for some of these as they are not all associated with neuropils?
Also, the axons of ascending neurons in the brain are presumably part of the brain as is the cervical connective?

**Comment by Clare72** [comment]
Recent publications and Brain Name paper - FBrf0224194 include the adult subesophageal zone as part of the brain.

The larval SEZ is a little more controversial, but most recent papers consider this as being distinct from the VNC and the brain:
https://neuraldevelopment.biomedcentral.com/articles/10.1186/s13064-018-0103-z (Doe lab, 2018)
https://www.sciencedirect.com/science/article/pii/S0022191017301154 (Pankratz lab, 2018)
https://www.sciencedirect.com/science/article/pii/S0959438820301355 (Eschbach & Zlatic, 2020)
https://elifesciences.org/articles/38740#fig2 (multiple Janelia authors, 2018)
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0191453 (Technau lab, 2018)

We currently consider the larval tritocerebrum to be part of the brain - supported by:
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0191453 (Technau lab, 2018)
https://link.springer.com/protocol/10.1007/978-1-4939-9732-9_5 (Hirth & Diaper, 2019)
https://academic.oup.com/genetics/article/213/4/1111/5930636 (Crews, 2019)
https://www.cell.com/cell-reports/pdfExtended/S2211-1247(14)00569-5 (Truman lab, 2014)

Other recent papers seem to class the tritocerebrum as part of the SEZ (perhaps in addition to part of the brain):
https://www.sciencedirect.com/science/article/pii/S0960982220308526 (Pankratz lab, 2020)
https://www.sciencedirect.com/science/article/pii/S0896627320306486 (Zhang lab, 2020)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5963519 (Hartenstein et al., 2018)
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008478 (Cavanaugh lab, 2019)

Probably best to leave the tritocerebrum as part of the brain for now and add a comment.
Not clear whether tritocerebrum should also be included in the larval supraesophageal ganlion, which currently seems to be the same thing as the larval brain - perhaps best to just merge these?
We might need terms for larval subesophageal/supraesophageal zone (to mirror adult terminology and have overlaps relationship with tritocerebrum).

**Comment by Clare72** [comment]
It might also be a good idea to align the larval and general 'subesophageal ganglion' terms to use 'gnathal' in the label to match adult terminology and make a clearer distiction between 'subesophageal ganglion' and 'subesophageal zone'
