### ISSUE TITLE
New term: nur neuron

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#532]
from FBrf0241362 - nur is a secreted protein (albeit they only show this in culture) expressed in a couple of neurons in the fan shaped body

**Comment by Clare72** [comment]
These neurons are not well characterised in this paper and I am hesitant to add based on expression alone, as nur is not a well known neuropeptide (I don't want to end up making a cell type for every gene in every location!)
Maybe just use 'fan-shaped body' as the location for this one.
