### ISSUE TITLE
Populate functional systems [sf#57]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#57]
@dosumis 
**Reported by djs93 on 2015-05-19 14:33 UTC**
Add capable_of_part_of some sensory perception of **\* to secondary/tertiary sensory neurons.

For olfactory secondary neurons - can add to all PNs that innervate a glomerulus innervated by an ORN shown to respond to olfactory signal.   This reasoning should be recorded in a comment.

For visual: Need to think through justifiable assumptions based on location/known connectivity in order to get complete coverage.

NOTE: This is needed for building functional system based entry points for VFB.

**Comment by mmc46** [comment]
**Updated by djs93 on 2015-05-19 14:33 UTC**
- **Priority**: 1 --> 7

**Comment by dosumis** [comment]
@Clare72 - I'd like to bump the priority of this up.  

Perhaps turn this  ticket into an epic and make separate issues for visual system and olfactory system neurons.

We currently have no projection neurons in the olfactory system, even though there are lots that are known to be.

![image](https://user-images.githubusercontent.com/112839/42577979-74e85944-851d-11e8-9de1-1bc4bd2acaa1.png)

A logically defined term for 'olfactory projection neuron' would be useful for mapping up to CL. 

Poss ways to map:

1. For olfactory secondary neurons - can add to all PNs that innervate a glomerulus innervated by an ORN shown to respond to olfactory signal. This reasoning should be recorded in a comment.

2. Track down sources of functional data on olfactory projection neurons  - could ask @mmc46 or @jefferis for good papers to use for this. 

3. Use Ito/Shinomiya data from NeuronNDB - which assigns to functional classes (should investigate origins of these assertions if using though)

**Comment by mmc46** [comment]
For 2, one is https://www.cell.com/neuron/abstract/S0896-6273(16)30201-X.

And also related to 3, PNs can respond to many odours or be more specific, but responses are graded and dependent on concentration, which is not standardised. So datasets are not easily comparable.

DoOR (http://neuro.uni-konstanz.de/DoOR/default.html) aggregates response data and is more recent that NDB. There are already links in the DAO at the ORN level. But again, data will be using different concentrations for the most part.

**Comment by Clare72** [comment]
https://www.cell.com/neuron/abstract/S0896-6273(16)30201-X is FBrf0232828

**Comment by Clare72** [comment]
>For olfactory secondary neurons - can add to all PNs that innervate a glomerulus innervated by an ORN shown to respond to olfactory signal. This reasoning should be recorded in a comment.

The ORNs are quite well annotated in the ontology.

I could add has_synaptic_terminals_of relationships to 'antennal lobe glomerulus' subclasses to reflect existing has_synaptic_terminal_in assertions for ORNs (would this be possible to automate with Robot? - there are 74 such ORNs to go through). I would need to ensure that these glomeruli do not have part_of or is_a children. 

Then I could classify these glomeruli as part_of 'olfactory system' and PNs with terminals in them as olfactory PNs using GCIs.

**Comment by hattrill** [comment]
Adding to this ticket as directly related to functional systems:

There is no "visual system" in FBbt:

Current structure under sensory system:

|__sensory system
           |__chemosensory system
               |__gustatory system
               |__olfactory system
           |__hygrosensory system
           |__mechanosensory system
               |__auditory system
           |__thermosensory system

It would be good to have this grouping wrt aligning ourselves with the Alliance and for our own phenotype/expression summary ribbons.

**Comment by dosumis** [comment]
This finds olfactory PNs:

MATCH (c:Class { label: 'antennal lobe glomerulus'})<-[:SUBCLASSOF*..]-(glom:Class)<-[:has_presynaptic_terminals_in]-(n:Sensory_neuron)-[:capable_of]->(:Class { label: 'detection of chemical stimulus involved in sensory perception of smell'}) with glom MATCH (glom)<-[:has_postsynaptic_terminals_in]-(x:Class) RETURN glom.label, x.label

Maybe extend to visual system with query over  synaptic  connectivity from photoreceptors?
