### ISSUE TITLE
Need to harmonise FB feature URIs between ontology and individuals [sf#59]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#59]
@dosumis 
**Reported by djs93 on 2015-06-03 13:06 UTC**
For FlyBase feature, FBbt currently uses URIs like this:

http://purl.obolibrary.org/obo/FlyBase_FBgn0010433

Whereas the VFB owl individuals files use a resolvable URI from FLyBase:

http://flybase.org/reports/FBti0143532

These need to be harmonised.  It would be nice to use the resolvable FlyBase URI in all cases, but it is hard to see how this can work with OBO and the assumptions built into oort, used for release.

Changing the URIs used for individuals is likely to have additional problems for the VFB site, which uses them for rolling links to FlyBase.

One possible solution is to switch to using an import type system, storing the master for FlyBase features in OWL.  This could follow the pattern used for the GO editor's file.

**Comment by dosumis** [comment]
Would be good to get this fixed, as it affects entity reconciliation in VFB neo4J.  

@cmungall: (How) can we get around oort's baked in assumption of obolibrary purl base URI for entities referenced in OBO file master?

**Comment by cmungall** [comment]
I have been generally replacing oort with individual robot/owltools 
calls (and larger makefiles). Not progressed as far as I'd hoped, and 
the mapping between operations is not always obvious

**Comment by dosumis** [comment]
Simplest solution is probably to move offending axioms to [vfb_ext.owl](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/fbbt/src/trunk/ontologies/fbbt-ext.owl), where they can be specified with the correct URIs.  This can be done most easily in Protege 5, loading both fbbt-ext.owl and  fbbt-edit.obo as imports.  Axioms can be moved using right-click and choosing 'Move axiom(s) to ontology' option.

**Comment by cmungall** [comment]
What URIs have you decided on for genes?

we currently have a difference between monarch and go

https://github.com/prefixcommons/biocontext/blob/master/registry/go_context.jsonld#L116
identifiers.org

https://github.com/prefixcommons/biocontext/blob/master/registry/monarch_context.jsonld#L50
flybase.org/repports

Is the default OBO assumption still an issue for you? Me too. Perhaps this needs to be fixed at the level of the OWLAPI OBO Parser to make it respect the idspace tags

**Comment by dosumis** [comment]
We're following Monarch IRI patterns for VFB and this needs to align.  

This issue came up again because I'm working on switching FlyBase ontologies over to the ontology starter kit.   I'll need some separate scripting in order to cope with importing classes for FlyBase genes.  I could use some Python code from VFB that directly queries public CHADO.  I already have that in place for other purposes and need to hook up to dipper anyway.

**Comment by dosumis** [comment]
> Is the default OBO assumption still an issue for you?

Somewhat. To maintain non OBO-style IDs we need to use full iris for reference in OBO (which is still master format for FBbt). e.g. 

intersection_of: expresses http://flybase.org/reports/FBgn0004652

I think we can put up with the full IRI in OBO stanzas in these cases.

> Perhaps this needs to be fixed at the level of the OWLAPI OBO Parser to make it respect the idspace tags

Perhaps treating all OBO IDs as curies with OBO default but making it easy to declare an override. Is there a translation for RDF prefix to OBO?  With that we could have an OBO representation of FlyBase:FBgn0004652 with a prefix declaration that expands it.

**Comment by cmungall** [comment]
https://github.com/owlcs/owlapi/issues/753
