### ISSUE TITLE
Few issues with autodefinitions

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#590]
The new autodefinitions generally look great - in some ways better than the old ones.

There seem to be a few issues:

 - Xrefs are being lost on autogenerated definitions.
We were also previously adding 'FBC:auto_generated_definition' as an xref, but I don't think this is really necessary (it was not previously done in dpo), so maybe don't do this.

 - We also need full stops "." at the end.

 - There seems to be an issue with labels that have special characters( "/", "-", "'" (apostrophe), "&") in them where the special character becomes a " " (space) and the term ID is not added (see first example).

 - ID for fruitless is being incorrectly added where fruitless is in the name of a neuron (see second example). BTW - great to now have expression in the autodefinitions!

 - Some terms are not getting autodefinitions (see third example).

e.g. FBbt:00002089 (prothoracic vesC neuron)
OLD: "Any vesC neuron (FBbt:00002043) that has postsynaptic terminals in some prothoracic **Keilin's** organ **(FBbt:00111639)** and that fasciculates with some prothoracic segmental nerve (FBbt:00002085)." [FBC:auto_generated_definition, FlyBase:FBrf0045359]
NEW: "Any vesC neuron (FBbt:00002043) that fasciculates with some prothoracic segmental nerve (FBbt:00002085) and has postsynaptic terminal in some prothoracic **Keilin s** organ" []

e.g. FBbt:00110557 (adult fruitless pIP4 neuron)
OLD: "Any neuron (FBbt:00005106) that is part of some adult fruitless pIP4 lineage clone **(FBbt:00110556).**" [FBC:auto_generated_definition, FlyBase:FBrf0128543, FlyBase:FBrf0211884]
NEW: "Any neuron (FBbt:00005106) that is part of some adult fruitless **(FBgn0004652)** pIP4 lineage clone and expresses fruitless (FBgn0004652)." []

e.g. FBbt:00005918 (thermosensory neuron)
OLD: "Any neuron (FBbt:00005106) that capable of some detection of temperature stimulus involved in thermoception (GO:0050960)." [FBC:auto_generated_definition, FlyBase:FBrf0159248]
NEW: "." [FlyBase:FBrf0159248]

**Comment by matentzn** [comment]
- [ ] Xrefs are being lost on autogenerated definitions.
- [X] We also need full stops "." at the end.
- [X] There seems to be an issue with labels that have special characters( "/", "-", "'" (apostrophe), "&") in them where the special character becomes a " " (space) and the term ID is not added (see first example).
- [ ] ID for fruitless is being incorrectly added where fruitless is in the name of a neuron (see second example). 
- [X] Some terms are not getting autodefinitions (see third example).

Examples NOT covered:
- [ ] e.g. FBbt:00110557 (adult fruitless pIP4 neuron)
OLD: "Any neuron (FBbt:00005106) that is part of some adult fruitless pIP4 lineage clone (FBbt:00110556)." [FBC:auto_generated_definition, FlyBase:FBrf0128543, FlyBase:FBrf0211884]
NEW: "Any neuron (FBbt:00005106) that is part of some adult fruitless (FBgn0004652) pIP4 lineage clone and expresses fruitless (FBgn0004652)." []

**Comment by matentzn** [comment]
I think it is all fixed now. Please check and close this issue if you are happy!
