### ISSUE TITLE
Hard coded overlaps-part of chain should be moved to RO

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-anatomy-developmental-ontology#591]
Currently in fbbt-edit.obo:

```
[Typedef]
id: overlaps
name: overlaps
xref: RO:0002131
transitive_over: part_of ! part_of
```

**Comment by dosumis** [comment]
Thought we'd cleaned up all Typedef axioms in FBbt apart from id, name, xref.

**Comment by matentzn** [comment]
We removed it, but then many inferences got lost; Its easy to remove, but dont you want to be sure that it comes in from RO first before we get rid of it? :P I dont mind either way.

**Comment by dosumis** [comment]
Sorry - had forgotten that.  It absolutely needs to be in RO.  Quite shocking it's not.

**Comment by matentzn** [comment]
Does the obo syntax correspond to `overlaps o part of subroleof: overlaps`?

**Comment by matentzn** [comment]
(OBO syntax question sorry :P should know these things; just wanna be sure.

**Comment by matentzn** [comment]
Moved https://github.com/oborel/obo-relations/issues/330

**Comment by matentzn** [comment]
We need to remember to remove this once RO has had a new release
