### ISSUE TITLE
Enteroendocrine cell subclasses

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#594]
Make subclasses for enteroendocrine cells based on peptide expression maps
Look up Veenstra papers for larva (and FBrf0211737 for DH31)
Park + Kwon for adult

**Comment by gouttegd** [comment]
Plan of action for this issue:

### For the adult gut
Based on the consensus that EE cells fall into two major classes: class I cells expressing Allatostatin C and class II cells expressing Tachykinin, with other hormones being expressed dependent on the localization within the midgut (FBrf0226048, FBrf0232200, FBrf0244352).

- Define a `adult class I enteroendocrine cell` as equivalent to `adult enteroendocrine cell` that expresses `AstC`;
- Rename `Tachykinin cell of the adult midgut` (FBbt:00110036; that term is not used anywhere) into `adult class II enteroendocrine cell` for consistency and define it as equivalent to `adult enteroendocrine cell` that expresses `Tachykinin`.
- For each class, define three sublasses, one for each major region of the midgut (anterior, middle, posterior).

We ultimately end up with the following hierarchy:

- `adult enteroendocrine cell`
  - `adult class I enteroendocrine cell`
    - `adult anterior midgut class I enteroendocrine cell` (:= `adult class I enteroendocrine cell`, part of `adult anterior midgut`, and expressing `Orcokinin`);
    - `adult middle midgut class I enteroendocrine cell` (:= `adult class I enteroendocrine cell`, part of `adult midgut region R3`, and expressing `Orcokinin`);
    - `adult posterior midgut class I enteroendocrine cell` (:= `adult class I enteroendocrine cell`, part of `adult posterior midgut`, and expressing `Mip` and `AstA`);
  - `adult class II enteroendocrine cell`
    - `adult anterior midgut class II enteroendocrine cell` (:= `adult class II enteroendocrine cell`, part of `adult anterior midgut`, and expressing `NPF` and `Dh31`);
    - `adult middle midgut class II enteroendocrine cell` (:= `adult class II enteroendocrine cell`, part of `adult midgut region R3`, and expressing `NPF` and `Mip`);
    - `adult posterior midgut class II enteroendocrine cell` (:= `adult class II enteroendocrine cell`, part of `adult posterior midgut`, and expressing `NPF` and `Dh31`).

### For the larval gut
Remains to be determined, but we may not be able to define precise subtypes of `larval enteroendocrine cell` as proposed above for the adult gut, based on the available data.

**Comment by Clare72** [comment]
looks good, best to keep the logical definitions (EquivalentTo) minimal, so for "adult anterior midgut class II enteroendocrine cell" you will have:
EquivalentTo:
'adult class II enteroendocrine cell' and 'part of' some 'adult anterior midgut'
SubClassOf:
expresses some NPF
expresses some Dh31
