### ISSUE TITLE
Activate Travis for all ontologies

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-anatomy-developmental-ontology#596]
I do not have sufficient rights:

- [ ] https://travis-ci.org/FlyBase/drosophila-phenotype-ontology
- [ ] https://travis-ci.org/FlyBase/drosophila-developmental-ontology
- [ ] https://travis-ci.org/FlyBase/flybase-controlled-vocabulary
- [X] https://travis-ci.org/FlyBase/drosophila-anatomy-developmental-ontology

I think you just click Activate and its done.

**Comment by Clare72** [comment]
They are active on https://travis-ci.com/FlyBase/... (and all failing!)
Looks like we are supposed to be using .com now:
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

I have an option to switch on 'Legacy Services Integration' on .org which is on for fbbt, but not the others, but we should probably use .com

**Comment by matentzn** [comment]
Ah cool! Thanks! :)
