### ISSUE TITLE
Sex-specific neuron types term equivalent Class defs too broad

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#599]
'female specific neuron' EquivalentTo: 'neuron that part_of some "female organism"' classifies any individual neuron that happens to be part of a female, e.g. 

![image](https://user-images.githubusercontent.com/112839/62828461-edbc6400-bc21-11e9-97cc-471fff55b03a.png)

A fully necessary and sufficient definition would be:

'female specific neuron' EquivalentTo: 'neuron that (part_of some "female organism") and (part_of only  "female organism" )

But we can't use this as it is outside of EL.  I suggest that we make a PATO quality: 'female specific'  and use this in the ontology to indicate female specificity and drive auto-classification.

We can then make GCIs:

bearer_of some 'female specific' SubClassOf: part_of some "female organism"'  ***Annotated as EL***  We need this in FBbt - either direct or via import from PATO.  If via import then we axioms to bridge FBbt female organism -> Uberon Female organism  - so probably best just to add this to FBbt_ext.owl for now.

bearer_of some 'female specific' EquivalentTo: part_of some "female organism") and (part_of only  "female organism" )  ***Annotated as DL***

**Comment by Clare72** [comment]
'female anatomical structure' already exists in [UBERON](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0014404) and [AEO](https://www.ebi.ac.uk/ols/ontologies/aeo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FAEO_0000176)
Can we use this?

**Comment by dosumis** [comment]
We urgently need to stop classifying all individual neurons from female brains as female-specific. This misclassification turns up on  v.large numbers of FlyCircuit neurons and so is a very obvious and common error recognisable by most neurobiologists browsing this data on VFB. (It was a bit embarassing to have this showing up in demos to FlyCircuit this week).  The challenge then is to classify female specific neurons properly - ideally without manually specifying multi-inheritance classification. It makes sense to do this with a common pattern for all sex-specific anatomical structures and in co-ordination with PATO.

Please could you make a pull request on PATO with

sex-specific:  A quality that inheres in an anatomical entity by virtue of it only being found in organisms of one sex.
    female-specific: A quality that inheres in an anatomical entity by virtue of it only being found in female organisms. 
    male-specific:...

I think this can go directly under 'physical object property' (we may need a parallel heirarchy for sex-specific processes, given upper ontology structure).  It don't think it should  go under 'biological sex' as this appears to apply only to qhole organisms: "An organismal quality inhering in a bearer by virtue of the bearer's ability to undergo sexual reproduction in order to differentiate the individuals or types involved".

Please put in a request to  Uberon to define 'sex-specific anatomical structure ' using the new PATO term. 

You can  then  use 'female-specific' to define in FBbt

female-specific anatomical structure:
    EquivalentTO: 'anatomical structure' that bearer_of some female-specific
    subClassOf: part_of some 'female organism'  # Hidden GCI will ensure all female specific structures get part_of relationship to female organism

female-specific neuron:
    EquivalentTO: neuron that bearer_of some female-specific

All female-specific structures in FBbt  should then get the clause: 
SubClassOf bearer_of some 'female-specific'

I think it's worth making a second ticket about what GCIs etc should go in to PATO for completeness (see first comment).
