### ISSUE TITLE
make neuroblast and neuron disjoint

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#61]
Many other simple disjoints could be added between cell types.  Having this one in place would have flagged mistaken dual classification of some individual neurons as neuron AND neuroblast in http://purl.obolibrary.org/obo/fbbt/2015-03-11/fbbt-non-classified.owl  (e.g. see VFB_00013163 ; VGlut-F-200386)

**Comment by mmc46** [comment]
The disjoint has been added between neuron and neuroblast.
