### ISSUE TITLE
Obsolete embryonic garland cell

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#62]
FBbt:00005704 embryonic garland cell is redundant.
FBbt:00005462 garland cell primordium is part_of late extended germ band embryo and dorsal closure embryo, and had develops_from relationship with FBbt:00001693 embryonic/larval garland cell 
embryonic garland cell is not in that developmental hierarchy, nor does it have an is_a relationship with FBbt:00005059 garland cell
I suspect it would best be merged with embryonic/larval garland cell.

**Comment by mmc46** [comment]
I have put embryonic garland cell in its right place in the hierarchy, and added the develops_from relationship that was missing.
I don't think it needs obsoleting, just needed classifying.
