### ISSUE TITLE
Loss of inferred relationships in fbbt-simple.obo

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#628]
Please checkout 'sex-inference-testing' branch to see an example.
On this branch I have removed all assertions of part_of some 'male organism' in the edit file, reasoning fbbt-edit.obo with ELK in Protege infers 256 (excluding 'owl:Nothing') subclasses of part_of some 'male organism' due to the 'bearer of' some male-specific SubClassOf 'part of' some 'male organism' axiom in fbbt_ext.owl.
When a release is run, this classification does not make it into fbbt-simple.obo, so running the same query on fbbt-simple.obo in Protege only finds 'owl:Nothing'.

**Comment by matentzn** [comment]
Yes! This is to be expected. The `'bearer of' some male-specific SubClassOf 'part of' some 'male organism' axiom` is not there anymore in simple; and the only links that are added by reason (by default) are the subclass links.. Do you want to avoid having to assert these manually? Or why did you do this experiment? If so, I think we could go via two routes:

1. We define a class called `male specific anatomical entity` and define it has `'bearer of' some male-specific`. We also add the subclass axiom: `male specific anatomical entity subclass of 'part of' some 'male organism'`. Now, all classes will first be classified under that class, and inherit the `part of some male organism` relation.
2. We use a different reasoner. ROBOT has some kind of reasoner that materialises `R some X` statements. This would require some changes in the makefile though; not sure how much of a fan of this idea I am.

What do you need this for?

**Comment by Clare72** [comment]
We switched over to using 'bearer of' some male-specific instead of 'part of' some 'male organism' (same for female) due to some mis-classifaction of individuals. I initially just replaced the 'part of' some 'male organism' with 'bearer of' some male-specific, as I thought the part_ofs were now redundant and it all classified properly in Protege (I then had to put them back).

I was under the impression that classification on FBbt terms using FBbt terms (i.e. FBbt:... subClassOf relationship some FBbt:...) seen in Protege should be retained in all the artefacts even if the inference uses external files. Is this not the case?

**Comment by matentzn** [comment]
The classification absolutely should! Maybe I misunderstood. The partomic relations are not necessarily preserved; So what you are saying is you have missing subclassof links between named casses?

**Comment by Clare72** [comment]
>The partomic relations are not necessarily preserved

I was expecting that if an FBbt class was inferred to be subClassOf 'part of' some 'male organism' (where 'male organism is an FBbt class), then this should be retained. I guess this is not the case?

**Comment by matentzn** [comment]
So to be clear:

FBBT1: sub FBBT2 is necessarily preserved

FBBT1: sub part of FBBT is usually preserved, but only if there is at least a single assertion somewhere. You case is special, as you want to infer this link from a GCI; this will not work. There must be at least a single instance of FBBT1: sub R some FBBT2 somewhere for this to work.. Lets put this on the agenda of the next phenotype call; I think @dosumis might not have been aware of this (neither have I!); its a real limitation of the current process.

**Comment by matentzn** [comment]
Or maybe I am confused from the Greek sun. :P 

Either way, we will get to the bottom of this. How important/urgent is this?

**Comment by Clare72** [comment]
Not at all, I added back the asserted 'part of's and the release is done

**Comment by matentzn** [comment]
This is bugging me now.. Grrr. 

So lets get down to formalising the problem:

```
ax1: R some B subclass of S some X ('bearer of' some male-specific SubClassOf 'part of' some 'male organism')
ax2: A sub R some B (FBBTX sub 'bearer of' some male-specific)
```

Intended inference:
```
A sub S some X
```

Is this problem description correct @Clare72 ?

**Comment by Clare72** [comment]
Yes, that looks correct. Like you said before, I could add the 'male specific anatomical entity' class to fix this, but it is surprising that the GCI doesn't work for making fbbt-simple when it works in the edit file using ELK in Protege.

**Comment by matentzn** [comment]
The reason I believe lies within ROBOT filter.

1. The inference chain is this: A -> S some X -> R some B.
2. Our ROBOT filter selects only named parents (non in the example) and anonymous parents (S some X). So the selector will ignore R some B.
3. The inference then is not preserved: The GCI (ax1 in example) is filtered out because it contains a non-FBBT axiom; the A sub R some B axioms as well. All lost.

Thats at least what I think is going on; I suggest to try and go with the named class as I suggested if this is fine by you; this should solve the problem.

**Comment by Clare72** [comment]
Ok, thanks for investigating, I will do that.
