### ISSUE TITLE
circulatory system development, has orphans

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#63]
FBbt:00001665  dorsal vessel primodium has part_of children FBbt:00005682 aorta primordium,     FBbt:00007321 embryonic cardioblast, FBbt:00005684 heart primordium.  None of the latter three terms has develops_from children, despite having definitions that suggest strongly that they should, and there existing such terms. 
FBbt:00001675 embryonic/larval heart develops_from FBbt:00007322 embryonic heart cardioblast, which is a develops_from orphan.
Most terms that map onto the developing central circulatory system seem to dead-end.  I think they all need some attention to pull them into a proper hierarchy, through adding relationships (is_a and part_of, as well as develops_from), and considering merges of some terms.

**Comment by mmc46** [comment]
Could you please clarify the issue?

1) The primordium terms are the earliest we record so the three children of FBbt:00001665 dorsal vessel primordium don't have a develops_from relationship. But they have terms that are related to them by one.

For FBbt:00005682 aorta primordium, definition says "gives rise to the embryonic/larval aorta". 
embryonic/larval aorta has a develops_from relationship to aorta primordium

For FBbt:00007321 embryonic cardioblast, definition says "Precursor of cardial cells".
embryonic/larval cardial cell has a develops_from relationship to embryonic cardioblast

For FBbt:00005684 heart primordium the definition says "gives rise to the embryonic/larval heart."
embryonic/larval heart has a develops_from relationship to heart primordium

2) FBbt:00001675 embryonic/larval heart doesn't have a develops_from FBbt:00007322 embryonic heart cardioblast
FBbt:00007322 embryonic heart cardioblast is a precursor cell, part of FBbt:00001665 dorsal vessel primordium. 
FBbt:00007320 embryonic/larval cardial cell has a develops_from relationship to the parent term of FBbt:00007322 embryonic heart cardioblast, which is FBbt:00007321 embryonic cardioblast

**Comment by SianGramates** [comment]
Revisiting this ticket...I think I see where I went astray, which was expecting Vocabularies to display the develops_from children of terms that have such children, but don't have develops_from parents (for at least develops_from, the children of a parent-most parent do not display if one is looking at the parent-most term). So the problem isn't actually ontological, and I think we can safely close this ticket.

**Comment by temjones** [comment]
Okay, thanks for letting me know!
