### ISSUE TITLE
Muscle incorrectly  classified as neurons

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#632]
'ISN innervated muscle of A1-7'  subClassOf neuron

![image](https://user-images.githubusercontent.com/112839/66294588-3f5f3300-e8e1-11e9-9c3b-2528de5baa2a.png)

As well as removing this  classification, please make neuron DisjointWith muscle  (might be worth adding a  few more disjoints between cell types).

**Comment by Clare72** [comment]
Looks like this is coming from RO - RO:0000300 'in neural circuit with' has domain CL:0000540 'neuron'

FBbt neuron is already disjoint from 'mucle cell'

**Comment by dosumis** [comment]
https://github.com/oborel/obo-relations/issues/286

**Comment by dosumis** [comment]
Could  you  have  a  go at  doing an edit & pull request  on  RO?  I've invited you to be an editor.

**Comment by Clare72** [comment]
The RO release (2019-09-25) with Chris's fix - https://github.com/oborel/obo-relations/pull/304 was after the latest FBbt release (2019-09-05). This issue should be fixed by doing an FBbt release.

**Comment by Clare72** [comment]
This was not fixed by doing a release, so I had a look at the fix and it seems the wrong relationship was moved out (electrically_synapsed_to). Also synapsed_by and synapsed_to seem to be under the wrong <upstream/downstream>_in_neural_circuit_with.

**Comment by Clare72** [comment]
fixed by obsoletion of neural circuit relationships - https://github.com/oborel/obo-relations/pull/339
