### ISSUE TITLE
Possible merge: larval & adult Leucokinin LK anterior neuron with larval & adult ipc-1 neuron

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#633]
FBrf0238083 says: "In the larval CNS, Lk-GAL4 drives the expression in five pairs of neurons in the brain...However, four out of the five pairs in the brain do not display any LK-immunoreactivity, but in fact react with an antiserum to ion transport peptide (ITP). These lateral neurosecretory cells are found both in larval and adult brains and are known as ipc-1 neurons."

The terms 'larval Leucokinin LK anterior neuron' FBbt:00110052  and 'adult Leucokinin LK anterior neuron' FBbt:00110059 have comments respectively "These neurons are not labelled by a leucokinin antibody, suggesting they correspond to faint leucokinergic cells appearing during the second and third instar (de Haro et al., 2010)." and  "These neurons are not labelled by a Leucokinin antibody (de Haro et al., 2010)."

I'm wondering if these terms should be merged with 'larval ipc-1 neuron' FBbt:00047844 and 
'adult ipc-1 neuron' FBbt:00047843 , as FBrf0238083 rather makes them sound like the same things.

**Comment by Clare72** [comment]
I think you are right
It is probably best to keep the ipc terms, as the LK expression is weak/non-existent, but LK synonyms will be added
