### ISSUE TITLE
embryonic fat body not an embryonic/larval fat body?

### ISSUE THREAD

**Issue by mhalfon** [FlyBase/drosophila-anatomy-developmental-ontology#64]
"embryonic fat body" (FBbt:0005710) is_a "fat body" (FBbt:00005066) at the same level that "embryonic/larval fat body" (FBbt:00005711) is_a "fat body". This seems wrong, as there is no connection from "embryonic/larval fat body" to "embryonic fat body". So if I search for example for "embryonic/larval fat body AND ancestors" I don't get "embryonic fat body". It seems to me that "embryonic fat body" is_a ""embryonic/larval fat body". Maybe I don't have that quite right, but there ought to be a path linking embryonic fat body and embryonic/larval fat body. (In general, I think there are still a lot of issues in places with the whole 'embryonic' vs. 'embryonic/larval' thing.

**Comment by Clare72** [comment]
This issue is resolved by #1141
