### ISSUE TITLE
New relation and pattern needed for defining eo neurons

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#651]
This use of 'has postsynaptic terminal in' here doesn't really make sense  as there are no synapses involved:

`'eo neuron' EquivalentTo neuron and ('has postsynaptic terminal in' some 'eo-type sensillum')`

I think we need a new relation to define this: has_sensory_dendrite_in or has_sensory_terminal_in.  It should be modelled on the 'has postsynaptic terminal in' relationship (subclass of overlap etc).

**Comment by Clare72** [comment]
Yeah, I used this as it seemed close enough to be useful, if not biologically perfect.
The relationship should be made in RO, rather than FBbt, though, right?

**Comment by Clare72** [comment]
see: https://github.com/oborel/obo-relations/issues/377

**Comment by Clare72** [comment]
fixed in #1038
