### ISSUE TITLE
License and  attribution file lost!

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#659]
We used to have license and attribution in an imported OWL file: fbbt_auth_attrib_licence.owl  - see https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/77

This seems to have been lost with the move to ODK.  It should be resurrected ASAP as an  import (merged in during releases)

For compliance with OBO foundry standards,  the new version should have the license under  AP: dc:license, rather than dc:rights.  It should also have  dc11:description & dc11:title.

**Comment by dosumis** [comment]
Example of ontology metadata currently passing on foundry dashboard:

```xml
 <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/doid.owl">
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/doid/releases/2019-11-20/doid.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/doid/obo/ext.owl"/>
        <dc:description>The Disease Ontology has been developed as a standardized ontology for human disease with the purpose of providing the biomedical community with consistent, reusable and sustainable descriptions of human disease terms, phenotype characteristics and related medical vocabulary disease concepts.</dc:description>
        <dc:title>Human Disease Ontology</dc:title>
        <terms:license rdf:resource="https://creativecommons.org/publicdomain/zero/1.0/"/>
        <oboInOwl:date rdf:datatype="http://www.w3.org/2001/XMLSchema#string">20:11:2019 15:54</oboInOwl:date>
        <oboInOwl:default-namespace>disease_ontology</oboInOwl:default-namespace>
        <oboInOwl:hasOBOFormatVersion rdf:datatype="http://www.w3.org/2001/XMLSchema#string">1.2</oboInOwl:hasOBOFormatVersion>
        <oboInOwl:saved-by rdf:datatype="http://www.w3.org/2001/XMLSchema#string">lschriml</oboInOwl:saved-by>
        <rdfs:comment>The Disease Ontology content is available via the Creative Commons Public Domain Dedication CC0 1.0 Universal license (https://creativecommons.org/publicdomain/zero/1.0/).</rdfs:comment>
    </owl:Ontology>

**Comment by matentzn** [comment]
I made this to account for all kinds of syntaxes:

https://github.com/INCATools/ontology-development-kit/blob/master/docs/License.md

**Comment by dosumis** [comment]
@matentzn - Would it be better to just move these to the -edit file as property_value lines in the header?  IIRC, there are issues with getting the merges right to ensure ontology annotations end up in the release file?

**Comment by matentzn** [comment]
Yeah, this is what @Clare72 and I are doing right now!
