### ISSUE TITLE
CCAP/bursicon neurons

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#66]
A subset of larval/pupal CNS neurons express the neuropeptides CCAP and/or bursicon; these neurons are crucial to eclosion/post-eclosion events.  I can't find an FBbt term that maps onto them (could be missing it, but haven't yet found a search string in Vocabularies that gets a likely hit.
References:  FBrf0179185  (larval-centric), FBrf0218345 (pupal-centric), FBrf0220703. I'm not sure which neuropeptide should be referenced in the term; maybe both, maybe one with the other as a synonym (or both CCAP neuron and bursicon neuron as synonyms to the existing neuron I've failed to find in the anatomy ontology).  I'm not finding anything obvious in the children of "neurosecretory neuron" FBbt:00005130 nor "endocrine neuron" FBbt:00007436.  It's definitely not "EH neurosecretory neuron" FBbt:00006028.

**Comment by mmc46** [comment]
The CCAP/burs and CCAP neurons have been added. Larval and adult (FBrf0218345  looked at pharate adults).
