### ISSUE TITLE
New neuropil: round body

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#660]
For new term requests, please provide the following information:

## Preferred term label

round body

## Synonyms

RB

## Textual definition

???

## Suggested parent term

synaptic neuropil  subdomain

## Attribution

FBrf0221742

## Notes:

This term was defined by FlyCircuit.  To date,  we haven't included the FlyCircuit synaptic neuropils in VFB as we favour Ito's BrainName nomenclature instead.   However, we need to make an  exception in this case as the term is being used by FlyEM.   I'm not entirely sure what brain region to make this part of.  Possibly LAL  ?  Tanya Wolff should be able to help.

**Comment by Clare72** [comment]
Fig S1C says IDFP (containing round body) is aka VBO or LAL, so I will make it part of LAL
