### ISSUE TITLE
Add general class for descending neuron

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#663]
We have no general class for descending neurons, but lots of specific ones:

'descending neuron of the anterior dorsal brain'
'descending neuron of the anterior ventral brain'
'descending neuron of the gnathal ganglion'
'descending neuron of the outside anterior cluster'
'descending neuron of the pars intercerebralis'
'descending neuron of the posterior brain'
'descending neuron outside of the brain'

## Preferred term label

descending neuron

## Synonyms

?

## Textual definition

A with synaptic inputs predominantly in the brain and outputs predominantly in  the VNC, that descends through (fasciculates with) the  cervical connective.

Notes: 
1. This  one might be an outlier:
'descending neuron outside of the brain'
  <-is_a 'descending neuron outside of the brain DNx01'
- as it look like it has no synapses in the brain - and may actually be a sensory neuron.  TBD: broaden definition to say inputs in the head?
2. This definition would cover at giant fiber neurons - slightly broader  than Namiki

## Suggested parent term

interneuron? (of not including sensory), otherwise just neuron

**Comment by Clare72** [comment]
See FBbt:00047511 'adult descending neuron'
Is this what you need? It is a little different to what you describe (based on definition given in Namiki 2018).

**Comment by dosumis** [comment]
Looks good. Not sure how I missed it.
