### ISSUE TITLE
General class needed: 'mechanosensory neuron of chaeta'

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#667]
A mechanosensory neuron whose sensory dendrite is located in a cheata (bristle).

**Comment by dosumis** [comment]
'mechanosensory neuron' and overlaps some 'mechanosensory chaeta'

=> 26 subclasses  (Note - using just neuron => more as some 'mechanosensory chaeta' are also chemosensory - so both types of neurons get returned.

**Comment by Clare72** [comment]
'mechanosensory neuron' and overlaps some chaeta => 35 subclasses.
I think we want all of these even if the bristle is not annotated as mechanosensory (could be a superclass of mechanosensory and non-mechanosensory bristles).
