### ISSUE TITLE
Missing links between larval neurons, embryonic/larval neuroblasts and nervous system regions

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#67]
Many larval neurons are not linked to regions of the nervous system as they should be.

e.g. 
query: 'interneuron that part_of some larva'
=> 129 classes including many that should be linked to some region of the larval nervous system
'1-1I of abdomen'
'1-1I of thorax'
'2-2I of abdomen'
'2-2I of thorax'
'2-4I of abdomen'
'larval mushroom body anterior paired lateral cell'
'apterous-expressing neuron of the lateral cluster of the thorax Ap1'

But these queries => few or no results:
interneuron that part_of some 'larval thorax'
interneuron that part_of some 'larval abdomen'
interneuron that part_of some 'ventral nerve cord'
'sensory neuron' that part_of some head

Ditto for these queries using overlaps

As these neurons typically project across segments, and potentially across tagma, their location (in nervous system + tagma/segment) is best recorded using has_soma_location (a subproperty of overlaps)

Quick and dirty way to do this is to link to both segment and nervous system term.  A cleaner way is to link to the larval larval neuromere terms. But these need some work to link up to the CNS terms (VNC and brain).  To be consistent you'd need to comb through and make sure all these links went via the relavant neuromere term.

BTW - you might find these reports to be useful:
https://github.com/VirtualFlyBrain/larval_data/new/master/query_result_tables

CC @fewtrem

**Comment by dosumis** [comment]
Also need part relationships for procephalic neuroblasts up to embryo & larva.  This involves fudging part relationships, but I think that's the best we can do for now. 

protocerebrum primordium part_of 'embryonic protocerebal neuromere'

These should be "part_of 'protocerebrum primordium'" Also 
'posterior protocerebral neuroblast'
'central posterior neurobalst'
'anterior protocerebral neuroblast'

These should be "part_of 'central brain primordium'":

'dorsal deutocerebral neuroblast'
'ventral deutocerebral neuroblast'
'dorsal tritocerebral neuroblast'
'ventral tritocerebral neuroblast'


(BTW - these are not neuromeres (which are segmental subdivisions of the CNS) - but probably refer to regions of neuromeres:

'anterior protocerebral neuromere'
'central protocerebral neuromere'
'posterior protocerebral neuromere'

Maybe obsolete these, or make rename/reclassify them as primordia that are part of the 'central brain primordium'.)

**Comment by dosumis** [comment]
Also to investigate: Are we completely missing terms for neuroblasts of the gnathal neuromere?  I can't find any terms.

**Comment by mmc46** [comment]
I've done the changes noted on the second comment.
As for gnathal neuromere, no neuroblasts were described in the latest adult papers. I don't know as much about larval.

**Comment by mmc46** [comment]
I've done the changes noted on the first comment. Please let me know if I've missed any, or other that need correcting
