### ISSUE TITLE
New tracheal cell type?: stalk cell

### ISSUE THREAD

**Issue by sjm41** [FlyBase/drosophila-anatomy-developmental-ontology#68]
FBrf0228496/PMID:25977367 talks a lot about a Y-shaped 'stalk cell' in the larval tracheal system that connects the two tip cells to the dorsal trunk.  (See intro and fig 1A/B).
Another paper is referenced: FBrf0087684/PMID:8625828

I can't find this 'stalk cell' in FBbt.

**Comment by mmc46** [comment]
The term tracheal stalk cell has been added.
