### ISSUE TITLE
New Term Request: mechanosensory eo neuron

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#682]
For new term requests, please provide the following information:

## Preferred term label

mechanosensory eo neuron

## Synonyms

mechanosensory neuron of external sensory organ

## Textual definition

{ Auto from EquivalentClass def)

## Suggested EC def

'mechanosensory neuron' that overlaps some 'eo-type sensillum'

- or use more specific relations is one is now avaiable.

**Comment by dosumis** [comment]
Maybe also:

mechanosensory neuron' and overlaps some chaeta

**Comment by Clare72** [comment]
adding 'mechanosensory eo neuron' in #891 
<'mechanosensory neuron' and overlaps some chaeta> is FBbt:00048508 'mechanosensory neuron of chaeta'
