### ISSUE TITLE
add EXACT synonym to abdominal dorsal bipolar neuron dbp

### ISSUE THREAD

**Issue by gm119** [FlyBase/drosophila-anatomy-developmental-ontology#69]
Hi,

FBrf0229617 == Peng et al., 2015, Int. J. dev. Neurosci. 46: 100--107
PMID: 26306777

uses 'dbd' for the term 'abdominal dorsal bipolar neuron dbp' (FBbt:00002442) so it could be added as an EXACT synonym if you think thats appropriate
ta

**Comment by mmc46** [comment]
The synonym has been added.
