### ISSUE TITLE
new terms in the visual system (FBrf0224242)

### ISSUE THREAD

**Issue by nstaudt** [FlyBase/drosophila-anatomy-developmental-ontology#70]
Is it worth adding these new terms from FBrf0224242 to the ontology?

- Medulla columnar 61 neurons (MC61); this seems to be a diverse group of neurons defined by their function
- lobular tangential neuron LT13

Thanks,
Nicole

**Comment by dosumis** [comment]
Looks like it.  May want to request some more GO terms for functions.

**Comment by mmc46** [comment]
I've added MC61, but not LT13, as no information is given for that neuron, apart from the name, and being labelled in a figure panel.
