### ISSUE TITLE
subsets: remove MGI subset and add expression ribbon subset

### ISSUE THREAD

**Issue by hattrill** [FlyBase/drosophila-anatomy-developmental-ontology#716]
Remove/retire MGI ribbon terms subset labels, as no longer relevant
subsetdef: fbbtsubset_mgiribbons "MGI ribbon terms"

and add subset labels for current FlyBase anatomy expression ribbons under label:
subset: expressionslim_flybase_ribbon "FlyBase ribbon terms"

terms for subset:	
egg	FBbt:00000034
oocyte	FBbt:00004886
stem cell	FBbt:00007014
imaginal tissue	FBbt:00047552
anlage	FBbt:00005426
primordium	FBbt:00005495
sensory system	FBbt:00007692
embryonic sensory system	FBbt:00005827
nervous system	FBbt:00005093
presumptive embryonic/larval nervous system	FBbt:00001055
circulatory system	FBbt:00005057
presumptive embryonic/larval circulatory system	FBbt:00005676
tracheal system	FBbt:00005024
presumptive embryonic/larval tracheal system	FBbt:00005569
digestive system	FBbt:00005055
presumptive embryonic/larval digestive system	FBbt:00000438
adipose system	FBbt:00005065
presumptive embryonic/larval adipose system	FBbt:00005708
endocrine system	FBbt:00005068
presumptive embryonic/larval endocrine system	FBbt:00005712
excretory system	FBbt:00005056
reproductive system	FBbt:00004857
integumentary system	FBbt:00004969
presumptive embryonic/larval integumentary system	FBbt:00005392
muscle system	FBbt:00005069
presumptive embryonic/larval muscle system	FBbt:00005647

**Comment by Clare72** [comment]
how sure are you that no-one is using fbbtsubset_mgiribbons?

**Comment by hattrill** [comment]
97% - Marta added them as a starting set for expression/pheno ribbon work. But the set above is the final ribbon set.
