### ISSUE TITLE
Add underscores to default-namespace

### ISSUE THREAD

**Issue by cmungall** [FlyBase/drosophila-anatomy-developmental-ontology#72]
the header has

```
default-namespace: FlyBase development CV
```

this can roundtrip via the OWLAPI. However, if it is expanded and added as namespaces to individual stanzas, this will break the OWLAPI parser

**Comment by mmc46** [comment]
So 
```default-namespace: FlyBase_development_CV
```
would be fine?
I'll check with devs for any dependencies before making the change.

**Comment by mmc46** [comment]
Changed and new FBdv release in commit c40086c41161ad652c8bdd0b8bd0468657315841
