### ISSUE TITLE
cells overlapping cells

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#727]
Try the query `cell that overlaps some cell` on FBbt in Protege

=>

![image](https://user-images.githubusercontent.com/112839/74164082-337ed700-4c1b-11ea-974b-c20dd36e1571.png)

Here's an explanation:

![image](https://user-images.githubusercontent.com/112839/74164058-2bbf3280-4c1b-11ea-8c2a-4bb2d8ceb15a.png)

Seems to be due to mis-use of has_presynaptic_terminal_in when should be synapsed_to.

We could control for this in future by adding the GCI:

`cell disjointWith overlaps some cell`

**Comment by Clare72** [comment]
'tracheolar cell' overlaps itself due to complementary 'has part' and 'part of' relationships to 'tracheole' I could remove one of these to 'fix' it, but I don't think this is really wrong, so I have left it and didn't add the disjoint.
