### ISSUE TITLE
Add AMMC projection neuron class

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#73]
EquivalentTo: 'projection neuron' that has_presynaptic_terminal in some AMMC

We already have these by zone.

It would also be useful to have a general classes to query for phenotypes, expression

Also add AAMC extrinsic neuron class?

**Comment by mmc46** [comment]
I think you mean 
has_postsynaptic_terminal

Added AMMC PN.

I'm not sure what you mean by AMMC extrinsic neuron class.

**Comment by dosumis** [comment]
We have a few classes like this.

intrinsic neuron  of X  (local neuron of X): interneuron whose synapses are all in X
extrinsic neuron of X: interneuron that has synapses in X and other neuropils  (e.g. see MB extrinsic)

Perhaps terminology is a bit old fashioned now?

**Comment by mmc46** [comment]
I think intrinsic still makes sense, but extrinsic is hard to define.
