### ISSUE TITLE
We appear to not have the term "notum" in the anatomy ontology

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#74]
notum, which commonly refers to the upper aspect of the thorax, does not exist in the anatomy ontology. It's a BROAD synonym of mesothoracic tergum (FBbt:00004580), which includes a note reading:  	Commonly referred to as the notum. Strictly, notum refers to the whole upper part of a thorax segment (ISBN:978-3110148985), so there are actually 3 nota - pro-, meso- and meta-notum.
Though this image http://flybase.org/reports/FBim0000792.html makes it look like what I've thought of as "notum" may map onto "scutum" (FBbt:00004583). It's been a while since I've had reason to think about this body part; "notum" may include 'scutellum' ( 	FBbt:00004587).

**Comment by mmc46** [comment]
Most authors mean either mesothoracic tergum or scutum when using 'notum', most commonly the former though. I can add a synonym to scutum.

**Comment by SianGramates** [comment]
I'm a bit uncomfortable with the idea of a body part that has a name used by the vast majority of the fly community that is not a body part term in the FBbt.

**Comment by mmc46** [comment]
The majority of the community uses the term notum to mean different things, as mentioned above. Anatomists would follow the classification we have. The issue of authors using different words to mean the same thing is a frequent one, but that is why we have synonyms.
