### ISSUE TITLE
Superfluous neuroblasts

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#746]
We have a bunch of terms for neuroblasts in the larval ventral nerve cord with names like 'abdominal 1 neuroblast g' and 'thoracic neuroblast l'

None of these have any FlyBase records associated with them and these terms don't seem to be used in the literature any more (all using the 'NB1-1' and 'lineage 0' style terms).
Many of these do not even have definitions or references, so not really possible for anyone to use them.

The ones that do have a reference cite:
FBrf0047815
Truman, J.W., Bate, M. (1988). Spatial and temporal patterns of neurogenesis in the central nervous system of Drosophila melanogaster.  Dev. Biol. 125(1): 145--157.

Which is the only place I could find these terms used (for Drosophila).

Since there is now a mapping between the names of neuroblasts in the larva and the embryo (FBrf0231327), it is probably not necessary to have separate sets of terms and the 'embryonic' terms ('NB1-1' style) should be used to represent the same cell during embryonic and larval/pupal stages.

The unused 'abdominal 1 neuroblast g' and 'thoracic neuroblast l' terms should be obsoleted.

**Comment by SianGramates** [comment]
I approve this plan, with the caveat that if there's a term these are synonymous for, that synonym ought be made.
