### ISSUE TITLE
New terms: stellate and bar-shaped cells

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#747]
These cells should have an is_a relationship to Malpighian tubule Type II cell. The Type II cells have a different shape and molecular profile depending on whether they're in the intial/transitional segment of the Malpighian tubule (bar-shaped) or in the main segment (stellate). (this impinges on ticket #745; the Malpighian tubule lower domain has neither bar-shaped nor stellate Type II cells). I'll note I also need these terms for the next Freq Used GAL4 table update. 

## Preferred term label
stellate cell
adult stellate cell
embryonic/larval stellate cell
embryonic stellate cell

## Synonyms
stellate Malpighian tubule Type II cell
(NOTE: I'm ok with reversing preferred term and synonym, e.g., making 'stellate cell' the synonym)

## Textual definition
Malpighian tubule Type II cell localized to the main segment of Malpighian tubule. These cells have a stellate shape.

## Suggested parent term
is_a Malpighian tubule Type II cell FBbt:00005797
adult Malpighian tubule Type II cell FBbt:00005736
embryonic/larval Malpighian tubule Type II cell FBbt:00001907
embryonic Malpighian tubule Type II cell FBbt:00005645

## Attribution
FBrf0093736, FBrf0098338

## Preferred term label
bar-shaped cell
adult bar-shaped cell
embryonic/larval bar-shaped cell
embryonic bar-shaped cell

## Synonyms
bar-shaped Malpighian tubule Type II cell
(NOTE: I'm ok with reversing preferred term and synonym, e.g., making 'bar-shaped cell' the synonym)

## Textual definition
Malpighian tubule Type II cell localized to the initial and transitional segments of Malpighian tubule. These cells are bar-shaped.

## Suggested parent term
is_a Malpighian tubule Type II cell FBbt:00005797
adult Malpighian tubule Type II cell FBbt:00005736
embryonic/larval Malpighian tubule Type II cell FBbt:00001907
embryonic Malpighian tubule Type II cell FBbt:00005645

## Attribution
FBrf0093736, FBrf0098338

**Comment by Clare72** [comment]
Looks like the different type II cell morphologies only appear during pupal development - see FBrf0220823 (and there is a comment about this in the ontology already), so only making adult versions of these terms.

**Comment by SianGramates** [comment]
That sounds fine, thanks. If they're only in adults, I'm inclined to think that 'adult' doesn't need to be part of the term name.

**Comment by Clare72** [comment]
I kept it anyway for consistency with other terms
