### ISSUE TITLE
iPN seems to include both mALT and mlALT PNs but should only include mALT

### ISSUE THREAD

**Issue by jefferis** [FlyBase/drosophila-anatomy-developmental-ontology#76]
Class def says they fasciculate with mALT, but also says:

> but some are GABAergic (Wilson and Laurent, 2005; Jefferis et al., 2007).

when these neurons are the ventral cell body class sometimes referred to as [vPN](http://www.virtualflybrain.org/site/stacks/index.htm?id=FBbt_00067351).

**Comment by mmc46** [comment]
It's been corrected.
