### ISSUE TITLE
Fix issues caught by Foundry  dashboard checks

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#760]
Dashboard here: http://obo-dashboard-test.ontodev.com/fbbt/dashboard.html

Report:
http://obo-dashboard-test.ontodev.com/fbbt/robot_report.html

1. Duplicate definitions are flagged as errors.  Many of these are genuine errors, probably caused  by copy and paste editing. e.g. 

25 | ERROR | duplicate_definition | prothoracic tarsal segment [FBbt:00004668] | IAO_0000115 [IAO:0000115] | Tarsal segment of the adult prothoracic leg. |  
-- | -- | -- | -- | -- | -- | --
26 | ERROR | duplicate_definition | mesothoracic tarsal segment [FBbt:00004690] | IAO_0000115 [IAO:0000115] | Tarsal segment of the adult prothoracic leg.

Some are '.' definitions (an old place-holder convention for no def) - considered by the tests to be a more serious error than lacking a def.   Maybe change these to empty string for now?

However, some are likely to be unavoidable.  For example, closely related neuron types may be clearly distinguishable by morphology but be difficult to distinguish textually.  We can support these in VFB  by having exemplar (reference) images for morphology.  

The  demand for (distinct) textual definitions is going to hit us badly with provisional neuron types  from data.  We should bring this up with OBO-Foundry

2. Only  other Error is this weird missing label report.

487 | ERROR | missing_label | FBbt:RO.owl | label [rdfs:label]
-- | -- | -- | -- | --

**Comment by dosumis** [comment]
CC @matentzn

**Comment by matentzn** [comment]
IMO this thing with the unique definitions is just cosmetics - I had some discussions with other groups and this is simply not going to happen everywhere - for the reason your mention. Just let it be yellow on the dashboard. The problem is simply the distinction between description and definition. I definition must have all necessary and sufficient conditions; a description can get away with a list of necessary ones I guess.. I have advocated easing that requirement as well on the dashboard thread.

I will check this other ERROR with @Clare72 in our next meeting.

**Comment by matentzn** [comment]
(ideally of course we would simply use dc:desciption for incomplete definitions to avoid the confusion)

**Comment by dosumis** [comment]
> Just let it be yellow on the dashboard. 

We should push to turn this from an error to a warning on the dashboard.

**Comment by matentzn** [comment]
Ok, lets keep this here issue open, and push for this kind of change once the dashboard is published.. I dont think it is a good idea to block the deployment of it right now just because of this, or do you think its too important?

**Comment by matentzn** [comment]
Made a comment here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/956

**Comment by Clare72** [comment]
see also #597 for duplicate definitions

**Comment by Clare72** [comment]
closing this as there is already a ticket to deal with the duplicate definitions
