### ISSUE TITLE
Some neurons incorrectly have reference to  Ito et al., 2014, Neuron 81(4): 755--765 (FBrf0224194)

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#781]
Please  remove

has_reference CCP-VMP-PB 2 neuronNeuron
has_reference CCP-VMP-PB 3 neuronNeuron
has_reference CCP-VMP-PB 4 neuronNeuron
has_reference CCP-VMP-PB 5 neuronNeuron
has_reference CCP-VMP-PB 7 neuronNeuron
has_reference CCP-VMP-PB 8 neuronNeuron
has_reference CCP-VMP-PB neuronNeuron
has_reference CVLP-IDFP-VMP-PB neuronNeuron
has_reference PB 1 glomerulus-EB core-IDFP DSB neuronNeuron
has_reference PB 1 glomerulus-EB posterior-IDFP DSB neuronNeuron
has_reference PB slice 1-EB core-IDFP DSB neuronNeuron
has_reference PB slice 1-EB posterior-IDFP DSB neuronNeuron
has_reference PB slice 4-EB core-IDFP DSB neuronNeuron
has_reference PB slice 5-EB core-IDFP DSB neuronNeuron
has_reference PB slice 6-EB core-IDFP DSB neuronNeuron
has_reference PB slice 7-EB core-IDFP DSB neuronNeuron
has_reference PB slice 8-EB core-IDFP DSB neuronNeuron
has_reference PB slice 8-EB posterior-IDFP DSB neuron

**Comment by Clare72** [comment]
Looks like these reference Ito et al. (2014) for mapping the neuropils in the names to the neuropils in the ontology (using Brain Name nomenclature). This is in the comments on the terms.

Is this causing a problem?

**Comment by dosumis** [comment]
Noticed these while working on pub reports on VFB.  Have been assuming that references on the definition mean that the paper is in some  way about the entity being defined.   Perhaps this is not such a safe assumption, but I worry that, in this case, users will  click through to the  reference expecting to find something about the neuron.

**Comment by Clare72** [comment]
I could add a "(Lin et al., 2013)" citation to the definition text to clarify which ref is useful (I try to do this anyway when I work on a term).
