### ISSUE TITLE
new term: tract ensheathing glial cell

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#787]
For new term requests, please provide the following information:

## Preferred term label

tract ensheathing glial cell

## Textual definition
Not completely sure here; Comment for 'adult ensheathing neuropil associated glial cell' FBbt:00100504 states:
"Edwards and Meinertzhagen (2010) state that the ensheathing neuropil glia does not include glia that ensheath tracts that project between neuropils. This is because, although they are morphologically similar, those glia do not have their cell bodies within the neuropil nor do they associate with synapses."
Marker for these cells is Scer\GAL4[GMR75H03] (FBrf0243169)

## Suggested parent term
is_a ensheathing glial cell FBbt:00047836

## Attribution
FBrf0210316 PMID:20109517 (Edwards and Meinertzhagen 2010) see section 1.1.4 : that references PMID: 9232819

**Comment by Clare72** [comment]
This was fixed as part of #366 

Definition of FBbt:00100504 - 'Glial cell of the adult central nervous system that elaborates along the outer surface of its associated neuropil. Glia of this class may also surround neuropil bundles such as commissures or tracts.' clearly includes tract neuropil glia, so I removed that confusing comment.

I also made subclasses for 'adult synaptic neuropil ensheathing glial cell' ('EGN') and 'adult tract neuropil ensheathing glial cell' ('EGT') based on FBrf0234767.
