### ISSUE TITLE
misnamed term: presumptive metathorax structures from prothoracic leg disc

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#79]
The term "presumptive metathorax structures from prothoracic leg disc" (FBbt:00110781) should be "presumptive metathorax structures from metathoracic leg disc". The term is part_of metathoracic leg disc (FBbt:00001783), and the corresponding parts of the other two leg discs are named correctly.

**Comment by mmc46** [comment]
It's been fixed. Thanks.
