### ISSUE TITLE
possible new term request: distal cell neuron of lobula complex

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#81]
FBrf0180181 extensively discusses a larval optic lobe cell type, which is referred to as a "distal cell neuron" in the paper. Digging through the paper, these neurons are in the larval lobula complex (at that stage, lobula anlage (FBbt:00001944), and lie adjacent to the lamina anlage glial cells (FBbt:00005720). I can't tell if this cell type lacking an FBbt term, or if it needs to be a synonym of an existing term.

**Comment by mmc46** [comment]
FBrf0180181 characterise these neurons solely on their position. No information is given morphology, function development, so I won't add a term for them.
What they are describing are neurons in the 'inner proliferation zone' FBbt:00001954. I've added the synonym "distal cell neuron" to this term.
