### ISSUE TITLE
GCI axioms showing up strangely in obo release files

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#819]
We found some lines like this in obo files in the latest (and maybe earlier) release(s):

relationship: part_of FBbt:00001911 {gci_filler="FBbt:00001727", gci_relation="overlaps"} ! embryonic/larval nervous system

These are not interpreted properly by some obo parsers (ignoring everything in curly braces).

I made some edits in #815 which will prevent the four lines we found from appearing in future, but it is a workaround rather than a proper fix.

**Comment by matentzn** [comment]
@dosumis should also be aware of this.

You could simply hack the GCIs out of the flybase.obo file the way to other things, by using `sed` in conjunction with `gci_filler`?

**Comment by Clare72** [comment]
Yeah, but it is not just FlyBase, we were made aware of the issue because someone at the Alliance was having trouble with fbbt.obo

**Comment by dosumis** [comment]
Perhaps filter  curly braces & their contents from relationships lines from all released OBO files?

I wonder what parser the alliance is using?!  @cmungall  any idea? The OWL-API parser should work - it's producing them after all.   The curly brace syntax was designed years ago and has been in standard spec since before OBO 1.4 IIRC, even if not used that much.   Might be better to push alliance to use a better parser as this is highly likely to hit them from other sources too.

**Comment by dosumis** [comment]
The Alliance should really be consuming OWL versions anyway.  It's nuts to build in OBO dependence at this point.

**Comment by Clare72** [comment]
He was using ontobio:

>"I found a strange feature of the new FBBT ontology version that is causing problems with the gene description software. I'm using ontobio (a python library to manage ontologies and annotations developed by GO) to get the list of root nodes of the ontology and I recursively follow IS_A and PART_OF links to calculate the depth and information content of all nodes. Apparently the new FBBT has no root nodes! FBbt:10000000 (which should be the root) has two parents (FBbt:00048490 and FBbt:00048491) and these have a parent, which is FBbt:10000000. This loop is an issue for the gene description software. Is this a feature that has been added for some reason or a bug in the ontology file? Thanks"

Caused by incorrect interpretation of these lines on 'anatomical entity' (FBbt:10000000):
is_a: FBbt:00048490 {gci_filler="FBbt:00048490", gci_relation="part_of"} ! male-specific anatomical entity
('anatomical entitiy' p_o 'male-specific anatomical entity =='male-specific anatomical entity')
is_a: FBbt:00048491 {gci_filler="FBbt:00048491", gci_relation="part_of"} ! female-specific anatomical entity

A similar issue was found in FlyBase.

**Comment by dosumis** [comment]
Looks like a a bug in JSON serialization  - perhaps in ontobio code.   Should be reported on:

https://github.com/biolink/ontobio  

(Odd that he's reporting OBO lines as the problem. AFAIK it all gets serialised through OWL. )

> A similar issue was found in FlyBase.

FlyBase is dependent on a truly ancient parser (possibly 2 truly ancient parsers as I think there maybe a custom one at IU). For as long as this is the case, we'll need custom filters to produce the flybase obo version.

**Comment by Clare72** [comment]
Ok, I assumed that those lines were the problem, because that is the problem for FlyBase. Perhaps something else coincidentally caused the problem in ontobio!

**Comment by dosumis** [comment]
> Ok, I assumed that those lines were the problem, because that is the problem for FlyBase. Perhaps something else coincidentally caused the problem in ontobio!

I think they are the problem, was just surprised to see them in OBO, but this makes sense if you were the one who identified the lines.  Important to get issue on to ontobio and get more general discussion of fixes.

**Comment by Clare72** [comment]
FlyBase file fixed
Alliance issue was caused by a custom obo parser not recognising gci axioms
