### ISSUE TITLE
Make robot pipeline to generate FlyBase gene import OWL file

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#821]
You can re-use VFB_neo4j code:

```py
from  uk.ac.ebi.vfb.neo4j.flybase2neo.feature_tools import FeatureMover
#   FeatureMover connects to the open FlyBase database and queries it. 
#   It also connects to a VFB neo4j DB to write content, but we're only using it for FB queries here.
fm = FeatureMover('http://pdb.virtualflybrain.org', 'neo4j', 'neo4j')   # This just expects some neo connection, not used with this method call in the next line. I should probably refactor
fm.name_synonym_lookup(['FBgn0004652']) 
```

Output is a dict of Node objects, keyed on FBgn:

```py
{'FBgn0004652': 
    Node(short_form='FBgn0004652', label='fru', iri='http://flybase.org/reports/FBgn0004652', 
   synonyms={'CG7688', 'CG14307', 'fruC', 'ms(3)06411', 'BTB-VI', 'CG7690', 'Fruitless',
 'FRU-PI', 'Fru', 'BTB-protein-VI', 'FRU', 'CG7689', 'fru-satori', 'satori', 'BtbVI', 'CT22773', 
 'cg7689', 'sat', 'fty', 'fruity', 'cg7688', 'Dmfru', 'fry', 'fruitless', 'fru'}, 
  xrefs=[])}
```

 extracting some content from a node object

```py
n = list(fm.name_synonym_lookup(['FBgn0004652']).values())[0]
print(n.label)
```

**Comment by Clare72** [comment]
Please can you clarify what you want:
What is this file for?
What genes should be in the file?
What data (label, synonyms, iri, xrefs) should be in the file?
Where should the file live?

**Comment by dosumis** [comment]
IIRC, classes referring to FlyBase genes are currently managed inside FBbt - with labels added by hand.  It would be much better if these came in as a generated import file.  That way names will stay up-to-date and we can include synonyms for easier search. 

This new import file can be generated programatically via queries of the FlyBase database (these are wrapped by the VFB_neo4j Python lib,  as illustrated above), which can be used to generate a Robot template.

A Python script for generating the Robot Template will need a list of FBgn IDs as input.  We should be able to pull these from declarations in FBbt, allowing you to add new FlyBase genes as bare IRIs in Protege - just as you do for any other new imported term.

If you can get Robot template generation working (from some fixed test list of FBgns) & generation of OWL from Robot looks good I can help plumb this into the Makefile.

Hope this makes sense.

**Comment by Clare72** [comment]
I already improved the process a little bit (for adding several new genes for FCA work):
https://github.com/FlyBase/flybase-ontology-scripts/tree/master/flybase_import_generator

I get up to date names from batch download, then regenerate flybase_import.obo with the notebook each time a term is added.

It would be nice to further automate this and get synonyms. Probably best to move back to FBbt repo if FBgns can be found from the edit file.

Template generation shouldn't be a problem, not too many fields.

**Comment by Clare72** [comment]
Nodes don't have an attribute for the 'Name' (long name as in FlyBase), just 'Symbol' (='label'). We have always previously used the 'Name' in flybase-import.obo (or 'symbol' if no 'Name'). Probably not an issue to switch to 'Symbol', just flagging the change.

**Comment by Clare72** [comment]
can make an owl file, but this won't convert to obo:
>Optional.get() cannot be called on an absent value

not sure if this indicates a problem (was going to compare to old file)

Also added SO:0000704 (gene) as superclass to all genes as in old file

**Comment by dosumis** [comment]
> Nodes don't have an attribute for the 'Name' (long name as in FlyBase), just 'Symbol' (='label'). We have always previously used the 'Name' in flybase-import.obo (or 'symbol' if no 'Name'). Probably not an issue to switch to 'Symbol', just flagging the change.

Yeh - I smushed these all together for  loading to VFB.   Full name  is  in synonyms.  Happy to switch to FBbt label to symbols as this => uniform representation in VFB  DB.

**Comment by dosumis** [comment]
Want  to share OWL file?  I  can  try to debug why not converting.  (Although - does it need to be OBO for import?)

**Comment by Clare72** [comment]
See linked PR for files (#822)
No, we would not need an obo file, I just wanted to compare it with the old file

**Comment by Clare72** [comment]
How do we put this into the makefile? - I can run FlyBase_import.py from the command line, but only with ~/git/VFB_neo4j/src in my PYTHONPATH, so not sure how to run in fbbt.Makefile.
Would it be something similar to how the perl scripts are run?
