### ISSUE TITLE
wing vein precursor

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#83]
Or wing vein primordium, or presumptive wing vein.  Part_of wing disc FBbt:00001778

There are currently 9 genes, 3 insertions, 1 construct with the curated expression pattern "wing vein | precursor", so it's a clearly identifiable structure.  Would be good to have a term for it! Probably for individual wing veins as well.

**Comment by temjones** [comment]
New terms added:

FBbt:00046009 presumptive wing vein L1
FBbt:00046030 presumptive wing vein L2
FBbt:00046031 presumptive wing vein L3
FBbt:00046032 presumptive wing vein L4
FBbt:00046033 presumptive wing vein L5
FBbt:00046035 presumptive wing vein
FBbt:00046034 presumptive wing margin

part_of FBbt:00006029 ! wing pouch

Other individual wing veins did not have enough evidence available for me to feel confident adding a precursor term.

Hope this sounds okay!

**Comment by SianGramates** [comment]
Yes, that sounds exactly right.

Thanks!

**Comment by mmc46** [comment]
I've added references to synonyms.
