### ISSUE TITLE
New FB Serotonergic neurons

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#830]
https://elifesciences.org/articles/26519

**Comment by Clare72** [comment]
Looks like our nomenclature for serotonergic neurons is outdated.
Terminology from this paper is shown in FBrf0239252 Fig 2b, similar to diagram using our names in FBrf0213697 Fig 2b (will make mapping easy).
Probably best to rename, since newer papers are using the new nomenclature.

**Comment by Clare72** [comment]
The neurons identified in the paper express the 5HT2b receptor - I don't think they produce serotonin. They overlap (and might all be?) ExFl2 neurons.

We may want a superclass for 'adult dFB neuron' - 'Adult neuron with terminals in the dorsal fan-shaped body', would need addition of 'dorsal fan-shaped body' - FBrf0239742 defines this as layers 6-9
