### ISSUE TITLE
part_of leg disc

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#84]
There are terms for the fate-mapped parts_of each individual leg disc (prothoracic, metathoracic, mesothoracic), but not for "ventral thoracic disc". So, for example, presumptive prothoracic coxa, presumptive mesothoracic coxa, and presumptive metathoracic coxa exit, but "presumptive coxa" does not. Thus, a curator needs to write 3 statements for, say, a gene expressed in presumptive coxa of all leg discs.  Could we have parent terms for these segment-specific terms?

**Comment by temjones** [comment]
Hi Sian, I'm looking at this one now. 

First, could you check that my summary here matches what you're asking for?: 
you would like a "presumptive coxa" term
- that is a part_of the "ventral thoracic disc" (FBbt:00001780); 
- has is_a children terms "presumptive prothoracic coxa" (FBbt:00110727), "presumptive mesothoracic coxa" (FBbt:00110754), and "presumptive metathoracic coxa" (FBbt:00110783);
- has develops_from child term "coxa" (FBbt:00004641)

Secondly, could you please provide the relevant references you are looking at? Thanks!

**Comment by SianGramates** [comment]
Here's the reference FBrf0219028

**Comment by SianGramates** [comment]
Terms NOT shared by all three leg discs (these will not need a parent term):

For prothoracic disc:
  presumptive prothoracic coxal bristle on hairy island
  presumptive prothoracic coxal sensillum trichodeum St3
  presumptive prothoracic tibial apical bristle
  presumptive prothoracic trochanter edge bristle

For mesothoracic disc
  presumptive proximal joint of mesothoracic coxa
  presumptive mesothoracic coxal bristle on hairy island
  presumptive mesothoracic tibial apical bristle
  presumptive mesothoracic tibial spur bristle
  presumptive mesothoracic trochanter
  presumptive mesothoracic trochanter edge bristle

For metathoracic disc:
  presumptive proximal joint of metathoracic coxa
  presumptive metathoracic femoral yellow bristles
  presumptive metathoracic tarsal bristle transverse row
  presumptive metathoracic tibial transverse bristle row

**Comment by SianGramates** [comment]
part_of terms present in "dorsal thoracic disc" that need children in individual leg discs (suggested new terms indented; should have is_a relationship to parent)

anterior-posterior compartment boundary of the ventral thoracic disc FBbt:00111522
	anterior-posterior compartment boundary of the prothoracic leg disc
	anterior-posterior compartment boundary of the mesothoracic leg disc
	anterior-posterior compartment boundary of themetathoracic leg disc

dorsal-ventral compartment boundary of the ventral thoracic disc FBbt:00111523
	dorsal-ventral compartment boundary of the prothoracic leg disc
	dorsal-ventral compartment boundary of the mesothoracic leg disc
	dorsal-ventral compartment boundary of themetathoracic leg disc

**Comment by SianGramates** [comment]
part_of terms that exist in each of the three leg discs, but not in the is_a parent "ventral thoracic disc". The suggested is_a parent for each set of disc-specific terms the term NOT bulleted.

presumptive coxa
- 	presumptive prothoracic coxa
- 	presumptive mesothoracic coxa
- 	presumptive metathoracic coxa

presumptive coxa-trochanter joint
- 	presumptive prothoracic coxa-trochanter joint
- 	presumptive mesothoracic coxa-trochanter joint
- 	presumptive metathoracic coxa-trochanter joint

presumptive coxal sensillum trichodeum St4
- 	presumptive prothoracic coxal sensillum trichodeum St4
- 	presumptive mesothoracic coxal sensillum trichodeum St4
- 	presumptive metathoracic coxal sensillum trichodeum St4

presumptive coxal sensillum trichodeum St8
- 	presumptive prothoracic coxal sensillum trichodeum St8
- 	presumptive mesothoracic coxal sensillum trichodeum St8
- 	presumptive metathoracic coxal sensillum trichodeum St8

presumptive femoral sensillum campaniformium Sc1
- 	presumptive prothoracic femoral sensillum campaniformium Sc1
- 	presumptive mesothoracic femoral sensillum campaniformium Sc1
- 	presumptive metathoracic femoral sensillum campaniformium Sc1

presumptive femoral sensillum campaniformium Sc11
- 	presumptive prothoracic femoral sensillum campaniformium Sc11
- 	presumptive mesothoracic femoral sensillum campaniformium Sc11
- 	presumptive metathoracic femoral sensillum campaniformium Sc11

presumptive femur
- 	presumptive prothoracic femur
- 	presumptive mesothoracic femur
- 	presumptive metathoracic femur

presumptive metatarsus
- 	presumptive prothoracic metatarsus
- 	presumptive mesothoracic metatarsus
- 	presumptive metathoracic metatarsus

presumptive thoracic structures from leg disc
- 	presumptive prothoracic structures from prothoracic leg disc
- 	presumptive mesothoracic structures from mesothoracic leg disc
- 	presumptive metathorax structures from prothoracic leg disc

presumptive tarsal segment 2
- 	presumptive prothoracic tarsal segment 2
- 	presumptive mesothoracic tarsal segment 2
- 	presumptive metathoracic tarsal segment 2

presumptive tarsal segment 3
- 	presumptive prothoracic tarsal segment 3
- 	presumptive mesothoracic tarsal segment 3
- 	presumptive metathoracic tarsal segment 3

presumptive tarsal segment 4
- 	presumptive prothoracic tarsal segment 4
- 	presumptive mesothoracic tarsal segment 4
- 	presumptive metathoracic tarsal segment 4

presumptive tarsal segment 5
- 	presumptive prothoracic tarsal segment 5
- 	presumptive mesothoracic tarsal segment 5
- 	presumptive metathoracic tarsal segment 5

presumptive tibia
- 	presumptive prothoracic tibia
- 	presumptive mesothoracic tibia
- 	presumptive metathoracic tibia

presumptive tibial preapical bristle
- 	presumptive prothoracic tibial preapical bristle
- 	presumptive mesothoracic tibial preapical bristle
- 	presumptive metathoracic tibial preapical bristle

presumptive trochanter
- 	presumptive prothoracic trochanter
- 	presumptive mesothoracic trochanter
- 	presumptive metathoracic trochanter

presumptive trochanter sensillum campaniformium Sc+5
- 	presumptive prothoracic trochanter sensillum campaniformium Sc+5
- 	presumptive mesothoracic trochanter sensillum campaniformium Sc+5
- 	presumptive metathoracic trochanter sensillum campaniformium Sc+5

presumptive trochanter sensillum campaniformium Sc-8
- 	presumptive prothoracic trochanter sensillum campaniformium Sc-8
- 	presumptive mesothoracic trochanter sensillum campaniformium Sc-8
- 	presumptive metathoracic trochanter sensillum campaniformium Sc-8

presumptive trochanter sensillum campaniformium Sc3
- 	presumptive prothoracic trochanter sensillum campaniformium Sc3
- 	presumptive mesothoracic trochanter sensillum campaniformium Sc3
- 	presumptive metathoracic trochanter sensillum campaniformium Sc3

presumptive trochanter sensillum trichodeum 2GSt
- 	presumptive prothoracic trochanter sensillum trichodeum 2GSt
- 	presumptive mesothoracic trochanter sensillum trichodeum 2GSt
- 	presumptive metathoracic trochanter sensillum trichodeum 2GSt

presumptive trochanter sensillum trichodeum St1
- 	presumptive prothoracic trochanter sensillum trichodeum St1
- 	presumptive mesothoracic trochanter sensillum trichodeum St1
- 	presumptive metathoracic trochanter sensillum trichodeum St1

presumptive trochanter sensillum trichodeum St5
- 	presumptive prothoracic trochanter sensillum trichodeum St5
- 	presumptive mesothoracic trochanter sensillum trichodeum St5
- 	presumptive metathoracic trochanter sensillum trichodeum St5

presumptive unguis
- 	presumptive prothoracic unguis
- 	presumptive mesothoracic unguis
- 	presumptive metathoracic unguis

**Comment by temjones** [comment]
I have created the following new terms:

FBbt:00046002 anterior-posterior compartment boundary of the prothoracic leg disc
FBbt:00046003 anterior-posterior compartment boundary of the mesothoracic leg disc
FBbt:00046001 anterior-posterior compartment boundary of the metathoracic leg disc
FBbt:00046005 dorsal-ventral compartment boundary of the prothoracic leg disc
FBbt:00046006 dorsal-ventral compartment boundary of the mesothoracic leg disc
FBbt:00046004 dorsal-ventral compartment boundary of the metathoracic leg disc
FBbt:00046007 presumptive coxa
FBbt:00046008 presumptive coxa-trochanter joint
FBbt:00046010 presumptive coxal sensillum trichodeum St4
FBbt:00046011 presumptive coxal sensillum trichodeum St8
FBbt:00046012 presumptive femoral sensillum campaniformium Sc1
FBbt:00046013 presumptive femoral sensillum campaniformium Sc11
FBbt:00046014 presumptive femur
FBbt:00046015 presumptive metatarsus
FBbt:00046016 presumptive tarsal segment 2
FBbt:00046017 presumptive tarsal segment 3
FBbt:00046018 presumptive tarsal segment 4
FBbt:00046019 presumptive tarsal segment 5
FBbt:00046020 presumptive tibia
FBbt:00046021 presumptive tibial preapical bristle
FBbt:00046022 presumptive trochanter
FBbt:00046023 presumptive trochanter sensillum campaniformium Sc+5
FBbt:00046024 presumptive trochanter sensillum campaniformium Sc-8
FBbt:00046025 presumptive trochanter sensillum campaniformium Sc3
FBbt:00046026 presumptive trochanter sensillum trichodeum 2GSt
FBbt:00046027 presumptive trochanter sensillum trichodeum St1
FBbt:00046028 presumptive trochanter sensillum trichodeum St5
FBbt:00046029 presumptive unguis

I did not create a "presumptive thoracic structures from leg disc" term, since the segment specific  terms refer to anlagen that each give rise to different structures of the thorax, so it did not seem appropriate to me to have a general term in this case.

**Comment by SianGramates** [comment]
I was on the fence about "presumptive thoracic structures from leg disc", so that term set works for me.

Thanks!
