### ISSUE TITLE
Edits to class IV dendritic arborizing neuron + NTR

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#85]
### New class:

label: nocioceptive neuron
EquivalentTo: neuron that capable_of some 'sensory perception of pain'
(GO:0019233)  # Note - may be worth considering asking go for a less
loaded, general term to use here: sensory perception of nocioceptive stimulus.

###  Edits to "class IV dendritic arborizing neuron" FBbt:00007275"

**Add EXACT synonyms From ref Ohyama et al., 2016 (DOI:10.1038/nature14297):**
MD IV
larval nociceptive multidendritic class IV neuron
larval multidendritic class IV neuron # <- consider using this as name of class + equivalent for siblings 

**Add axiom:**
SubClassOf: capable_of some sensory perception of pain

**Comment by dosumis** [comment]
I see that the Basin neurons have this:

![image](https://cloud.githubusercontent.com/assets/112839/24510835/338f3728-1562-11e7-964d-fc2d7ed6beeb.png)

Seems odd that the sensory neuron they are responding to does not.

Also, would be good to have something on the sensory function in the textual defs.  Nothing about this currently::

rdfs:label "larval Basin-4 neuron"^^xsd:string
definition "Neuron of the larval abdominal neuromere that is part of lineage 9. Its soma is located in the lateral intermediate cell body rind region. Its dendrites span a ventrolateral and ventromedial domains of the ventral nerve cord. These domains overlap with the axon terminals of the eight abdominal chordotonal neurons (lch1, lch5, vch1, vch2) and the class IV dendritic arborizing neuron, respectively, from which it receives input. The primary neurite fasciculates with the intersegmental nerve, with no ventral branch extending from it. Its axon is ventral to the axons of Basin-3 and -4, and extends anteriorly and posteriorly to or across the midline. It synapses onto the A00c-a5 and A00c-a4 neurons."

**Comment by Clare72** [comment]
>label: nociceptive neuron
EquivalentTo: neuron that capable_of some 'sensory perception of pain'

I don't think any one cell is 'capable of' any kind of sensory perception. Perhaps we could use 'capable of part of', but then should it be 'larval nociceptive system neuron'? There isn't currently a collective term for 'detection of X stimulus involved in sensory perception of pain'.

For MD IV
>Add axiom:
SubClassOf: capable_of some sensory perception of pain

I found a couple of papers showing their activity is required for behavioural responses to heat and mechanical nociceptive stimuli - [FBrf0223267](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0078704) and [FBrf0200914](https://www.sciencedirect.com/science/article/pii/S0960982207022683). Considered alongside their morphology, this is probably good enough to add 'capable of part of' some 'sensory perception of pain'. Probably best not to add 'capable of' some 'detection of mechanical stimulus involved in sensory perception of pain' and 'capable of' some 'detection of heat stimulus involved in sensory perception of pain' as these functions could be performed by different subclasses.

**Comment by dosumis** [comment]
> I don't think any one cell is 'capable of' any kind of sensory perception
Agreed

> Perhaps we could use 'capable of part of', but then should it be 'larval nociceptive system neuron'? 

We should do that for now.  I would also add 

SubClassOf: 'capable of' some 'detection of stimulus involved in sensory perception' (if this isn't redundant with a more speciific axiom).  => classification as sensory neuron.

This => the option of making nocioceptive neuron EquivalentTo: sensory neuron that capable_of_part_of some sensory perception of pain.

I think it would be worth asking GO for 'detection of stimulus involved in sensory perception of pain' - without the modality.  This would allow are more standard pattern here.

**Comment by Clare72** [comment]
Looking at Fig 6 of the [Ohyama paper](https://www.nature.com/articles/nature14297), the 'mechanosensory ch' neurons contribute to the sensory perception of pain, and they are sensory neurons, but they are not nociceptive neurons. I think it is better to wait for 'detection of stimulus involved in sensory perception of pain' for this. Ticket here: https://github.com/geneontology/go-ontology/issues/17789

**Comment by dosumis** [comment]
> the 'mechanosensory ch' neurons contribute to the sensory perception of pain

My understanding is that they are detecting sound and if they do so at the same time as the MD neurons detect pain, they potentiate the downstream signal from the MD neurons.  Not convinced that means they are involved in perception of pain.  If we go that route - there's a danger that any convergence and interaction of sensory signals means mixed modalitities.

**Comment by Clare72** [comment]
Yeah, it depends on your interpretation of what it means to be involved in the perception of pain, if the are increasing the response, is the larva feeling more pain? I don't think we want to put them as 'nociceptive system neuron', but it is ambiguous enough that I would rather make the 'nociceptive neuron' term the usual way by using the detection GO term.
