### ISSUE TITLE
dorsal appendage forming follicle cell; split polar follicle cell?

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#86]
I have absolutely no attachment to the exact name of this proposed term. Should have is_a relationship to follicle cell (FBbt:00004904). I note that several other specific follicle cells terms specifically mention chorionic specialization (FBbt:00007248) children that they are involved in the formation of, so follicle cells involved in the formation of the dorsal appendages (FBbt:00000046) ought be similar (for example, the definition of polar follicle cell (FBbt:00004907) mentions the role of the posterior follicle cells in the formation of the posterior aeropyle (FBbt:00000047). DIGRESSION: I'm wondering if polar follicle cell should have as children "anterior polar follicle cell" (with develops_from child "border follicle cell" (FBbt:00004905) and "posterior follicle cell" (that digression comes from looking at the definition of "polar follicle cell")

Described in FBrf0167514 and much more extensively in FBrf0174518. From the former "During (dorsal appendage) formation, the somatic layer consists of two major populations with distinctive morphologies, the stretch cells and columnar cells. At the anterior, ∼50 squamous stretch cells cover the nurse cells. These cells provide signals that pattern the anterior eggshell-forming cells and ensure proper nurse-cell cytoplasmic dumping. The columnar cells overlie the oocyte at the posterior and secrete the layers and specialized structures of the eggshell (reviewed by Waring, 2000). The anterior-most columnar cells (the centripetal cells) migrate inwards, closing off the anterior end of the oocyte while synthesizing the operculum and micropyle. In addition, two subpopulations of ∼65 dorsoanterior follicle cells form the two dorsal appendages through a complex reshaping and reorganization of a flat epithelium into three-dimensional tubes (Dorman et al., 2004)."

**Comment by temjones** [comment]
I have created the new term:
id: FBbt:00046036
name: dorsal appendage forming follicle cell

I think you have a good point regarding the polar follicle cells, but I'm not going to have time to look closely at that for the February FBbt update.

**Comment by mmc46** [comment]
@temjones The name and definition of this term should incorporate new findings - the populations of cells have been named and defined.
Eg.
http://www.sciencedirect.com/science/article/pii/S1534580713000658
http://www.sciencedirect.com/science/article/pii/S0012160610009498

**Comment by temjones** [comment]
@mmc46 Thanks. Would you suggest that I also create child terms for these subpopulations, mention the subpopulations in the definition of 'dorsal appendage forming follicle cell', or both?

**Comment by mmc46** [comment]
I didn't read the papers in detail. It would depend if the term you've created corresponds to the roof or floor populations, or both. And how those 2 populations differ. But it would be good mention them in the definition(s).

**Comment by temjones** [comment]
@mmc46 Okay, thanks. The term I created corresponds to both. Based on what I have read so far I think it would make sense to create two child terms of 'dorsal appendage forming follicle cell' for each of the roof and floor cells. I'll take a closer look at these papers and finalize tomorrow morning.

**Comment by temjones** [comment]
I have added terms for the two subtypes of dorsal appendage forming follicle cells:

id: FBbt:00046037
name: floor cell

id: FBbt:00046038
name: roof cell

**Comment by Clare72** [comment]
Looks like this issue is now resolved - closing
