### ISSUE TITLE
Synonyms for part_of children of male accessory gland FBbt:00004959

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#87]
male accessory gland main cell FBbt:00004960 please add exact synomyn "main secretory cell"
male accessory gland secondary cell FBbt:00004961 please add exact synomyn "secondary secretory cell"

Reference: FBrf0152376 Table 2 and Figure 5

**Comment by temjones** [comment]
This is done

**Comment by mmc46** [comment]
I've added the reference to the synonym.
