### ISSUE TITLE
Kenyon cells should be defined as having synaptic terminals in the MB Calyx!

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#872]
Currently 

![image](https://user-images.githubusercontent.com/112839/83888419-b3d4c500-a741-11ea-94ec-bffdfde4229e.png)

We should add ASAP.

Related issue:  we also have a problem with stages. Query for neurons with synaptic terminals in adult MB calyx finds no Kenyon cells, but we have plenty of subtypes of Kenyon cell with record of pre-synaptic terminals in MB calyx (stage neutral).  Not totally sure how to fix stage issue, but it's certainly counter-intuitive for users.

**Comment by Clare72** [comment]
>The dendrites of different Kenyon cells form the main calyx and the accessory calyx (Tanaka et al., 2008).

Currently our accessory calyces (dorsal (=ACA in Brain Name), lateral, ventral) are not part_of the 'mushroom body calyx' (following model of Brain Name paper), so not all KCs have terminals in the MB calyx (but some subclasses do, as you noted).

I could add a superclass, e.g. 'mushroom body calyx complex' to incorporate all the calycal regions(?) Then add relationship to this onto 'Kenyon cell'

Regarding stage, I think the only way to 'fix' is to dig through refs and make adult and larval subclasses where appropriate or rename and assert a part_of if classes really only exist in one or the other. I remember discussing this with @ah963 at some point and on balance he preferred to keep non-specific (I think maybe he was annotating developing adult structures during larval/early pupal stages).

**Comment by Clare72** [comment]
Also, from Marin et al. (2020):
>we recovered KCa’/b’ from sampling, three of which exclusively received input from the lACA

Further evidence that not all KCs have terminals in the (main) calyx

**Comment by Clare72** [comment]
New [hemibrain MB](https://www.biorxiv.org/content/10.1101/2020.08.29.273276v1.full) paper explicitly considers calyx to include accessory calyces:

>The MB can be divided into three distinct parts: the calyx, the pedunculus and the lobes (Figure 2; Video 1). The calyx is the input region for sensory information; KCs have their dendrites in the calyx where they receive inputs from projection neurons. The calyx has subregions: the main calyx (CA) and three accessory calyces.

So we should probably update to follow this model and make a new term for 'main calyx', then all KCs will have dendrites in the calyx (but not all in the main calyx).
