### ISSUE TITLE
Missing refs on larval feed across neurons and subclasses

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#881]
http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_0001789&i=VFB_0001789,VFB_0001789,FBbt_00049006

https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00049006

http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00049045&i=VFB_00017894

**Comment by Clare72** [comment]
Ref displays on ontobee:
http://www.ontobee.org/ontology/FBbt?iri=http://purl.obolibrary.org/obo/FBbt_00049006

Something to do with handling of dois on VFB and OLS?

**Comment by dosumis** [comment]
Think that must be it.    I'll add a ticket to extend the pipeline to support this.  I think all we can do  for now is roll a node with DOI &  hyperlink.
