### ISSUE TITLE
new term request for larval "retinal basal glia"

### ISSUE THREAD

**Issue by arzuozturk** [FlyBase/drosophila-anatomy-developmental-ontology#882]
I couldn't find the appropriate term for the larval "retinal basal glia" cells referred in FBrf0242008. Could you please look into that issue? The followings are mere suggestions, please feel free to use any other term label or synonym that might be more appropriate.

## Preferred term label
larval subretinal glial cell

## Synonyms
larval retinal basal glial cell

Thanks.

**Comment by Clare72** [comment]
After digging into this some more, RBGs seem to be any glial cells that migrate to the basal eye disc from the optic stalk - I have made this class now.

This paper (unlike others) seems to count carpet glia as being distinct from RBGs, but is not explicit about this, so I have gone with what seemed like the majority, and made 'carpet glial cell' an RBG subclass.

What they refer to as 'migratory RBGs' seems to refer to the subset of the optic stalk surface glia that migrate to the eye disc (at least some of which become wrapping glia). I have made a new class for these - 'embryonic/larval migratory optic stalk surface glial cell'.

You will find these terms in the next FBbt release (in a couple of months).
