### ISSUE TITLE
new term request: neuroepithelial cell

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#89]
I've been doing expression pattern curation on a set of papers involving neuroepithelial cells (example: FBrf0212909), which is a term the FBbt decidedly does not have.  I've been finessing around it using compound statements such as "epithelial cell &&of larval inner optic anlage", then clarifiying "neuroepithelial cell" in free text general expression statement.  Given that there's a sizable body of literature, not to mention a dedicated GO term "neuroepithelial cell differentiation " (GO:0060563), it seems obvious that this is a missing term,

Term is likely larval-specific.

**Comment by dosumis** [comment]
Hi Sian, Please could you provide an example paper?  Presumably referring to an intermediate, rather than terminal state.

**Comment by SianGramates** [comment]
There's a lot here http://www.sdbonline.org/sites/fly/aimorph/opticlobe.htm#Neuroepithelial

This, maybe FBrf0225842

**Comment by SianGramates** [comment]
It occurs to me that it might be, rather than a new term, a synonym to an existing term.

**Comment by mmc46** [comment]
The inner and outer proliferation centers (IPC and OPC) that make up the larval optic anlage are initially made up of dividing neuroepithelial cells. These then develop into neuroblasts (NB) (temporally and spatially regulated process). 
The IPC and OPC terms mention neuroepithelial cells, but we don't have a specific term for them, as we do for the NB, so I'll add one and make the necessary adjustments to the related terms.
https://neuraldevelopment.biomedcentral.com/articles/10.1186/1749-8104-2-1

**Comment by SianGramates** [comment]
Thanks Marta!

**Comment by mmc46** [comment]
New
id: FBbt:00111738
name: neuroepithelial cell

**Comment by dosumis** [comment]
Presumably this will be a general term - one that could apply outside this context?

**Comment by mmc46** [comment]
For now we only have the example in this context. If needed later on, I can create a parent term.

**Comment by dosumis** [comment]
I'd make the term 'neuroepithelial cell' general and make a more specific term for this context (e.g. neuroepithelial cell of optic anlage).

(Is this analogous to the neurectoderm in the embryo - from which neuroblasts delaminate leaving epithelial cells?)

**Comment by mmc46** [comment]
Not quite. Here neuroepithelial cells give rise to neuroblasts.

**Comment by Clare72** [comment]
Looks like this is solved now, so closing.
See also #118
