### ISSUE TITLE
Clean up partonomy for TAG [sf#9]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#9]
@dosumis 
**Reported by djs93 on 2013-08-02 10:37 UTC**
Clean up partonomy for TAG: There is lots of redundancy right now.

**Comment by mmc46** [comment]
This is awaiting publication of a paper on TAG nomenclature.

**Comment by Clare72** [comment]
TAG (VNS) terms have been reviewed recently for mapping to painted domains.

Further nomenclature revisions may occur when Court et al. (2020) paper is published as a final version - this will have its own ticket.

Closing this issue for now.
