### ISSUE TITLE
compartment & compartment boundary terms for genital discs

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#90]
The terms:
genital disc  	FBbt:00001784
male genital disc FBbt:00001785
female genital disc FBbt:00001787

lack compartment/coordinate terms (anterior compartment, posterior compartment, dorsal compartment, ventral compartment, anterior-posterior compartment boundary, dorsal-ventral compartment boundary) that were assigned to the other imaginal discs. Those terms were all obsoleted as spatial qualifiers, and need to be added as FBbt terms  in the same manner as for the other imaginal discs (for example, "anterior-posterior compartment boundary of the wing disc" and "wing disc dorsal compartment").

**Comment by dosumis** [comment]
IIRC, compartments work a little differently in the genital discs.  Worth checking classical/primary lit carefully before adding (some info in blue book + a good chapter in Ashburner and Wright series).

**Comment by temjones** [comment]
@dosumis Thanks for the heads up!
@SianGramates I am not going to be able to address this for the Feb FBbt update, but will aim to look at it for the May update. I hope this is going to be okay for your work.

**Comment by temjones** [comment]
I have added terms for the anterior compartments, posterior compartments, and the anterior-posterior compartment boundary, for the genital disc, female genital disc, and male genital disc. Dorsal/ventral compartments and boundaries are not applicable to the genital discs, as far as I can tell.

FBbt:00046043 anterior-posterior compartment boundary of the genital disc
FBbt:00046044 genital disc anterior compartment
FBbt:00046045 genital disc posterior compartment
FBbt:00046046 anterior-posterior compartment boundary of the female genital disc
FBbt:00046047 anterior-posterior compartment boundary of the male genital disc
FBbt:00046048 female genital disc anterior compartment
FBbt:00046049 female genital disc posterior compartment
FBbt:00046050 male genital disc anterior compartment
FBbt:00046051 male genital disc posterior compartment
