### ISSUE TITLE
New Definitions Request: Adult MB lobe compartments

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#900]
## term labels

adult mushroom body gamma-lobe
adult mushroom body beta'-lobe
adult mushroom body beta-lobe
adult mushroom body alpha'-lobe
adult mushroom body alpha-lobe

## definitions

From here for simple definition? https://www.cell.com/cms/10.1016/j.neuron.2013.12.017/attachment/7c76a244-54fc-4320-bb88-0f3eb1ccc79f/mmc1.pdf

**Comment by Clare72** [comment]
Ref is Ito et al. (2014) Brain Name paper FBrf0224194
