### ISSUE TITLE
VNC tract edits

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#906]
Related to https://github.com/VirtualFlyBrain/Management/issues/242

Changes requested by @Robbie1977 
Needs some clarification/references please

Symbol | is_a IRI | is_a label | Notes | Clare notes
--|--|--|--|--
DLT | http://purl.obolibrary.org/obo/FBbt_00047533 | dorsal lateral tract of the dorsal cervical fascicle | Add Synonym 'dorsal lateral tract' as being used | adding as broad synonym - also adding to 'dorsal lateral tract of the ventral cervical fascicle'
DMT | median tract of the dorsal cervical fascicle (FBbt_00047535) | dorsal medial tract | New Adult Term to replace FBbt_00047535? | FBbt_00047535 is an adult term, referred to as MTD in Power and Namiki papers - where does DMT come from?
MDT | FBbt_00047544 | median dorsal abdominal tract | Checked OK | where does MDT synonym come from (MDA in Power and Namiki)?
ITD HC/cHIN | FBbt_00047529 | haltere chiasma | Checked OK | where does cHIN synonym come from?
ITD HT | FBbt_00004094 | dorsal metathoracic nerve | should probably have Haltere Tract (HT) as synonyms? | thought tracts were meant to be within CNS? Is there a reference for 'haltere tract'?

**Comment by Robbie1977** [comment]
DMT & MDT is used in the Paper under review and the previous preprint versions so will have to wait until published (https://www.biorxiv.org/content/10.1101/122952v2)

I'll look up refs for cHIN and HT (it's the bit inside the CNS transitioning to the HN so maybe a separate term?)

**Comment by Robbie1977** [comment]
```id: FBbt:00125008
name: haltere chiasma
def: "A commissure formed by the lateral tracts of the intermediate tract of the dorsal cervical fasciculus, as they cross the midline between the meso- and metathoracic neuromeres and extend to the dorsal metathoracic (haltere) nerve of the contralateral side. The haltere commissure is posterior to the chiasma of fine fibers." [FlyBase:FBrf0007196, FlyBase:FBrf0210897]
comment: “lineage 8?”
subset: cur
synonym: "HC" EXACT [FlyBase:FBrf0007196]
synonym: "cHIN" EXACT [FlyBase:FBrf0056602]
```

**Comment by Robbie1977** [comment]
Dorsal Metathoracic Nerve (Haltere Nerve) and is the tract referred to as the Haltere Tract in Merritt and Murphey (1992).
FBrf0056602

**Comment by Robbie1977** [comment]
FYI https://www.biorxiv.org/content/10.1101/122952v1.full.pdf+html has all my original refs and definitions showing all the classical refs for synonyms etc. (a lot was stripped out in v2 for simplicity)

**Comment by Clare72** [comment]
I have added 'haltere tract' as a new term based on your preprint.
Also added other requested published synonyms.

Probably best to wait for final (published) version before doing other renames/synonyms from your paper (and that should be its own ticket).

You should try to get that extra v1 synonym info published as a supplementary file - it is useful!
