### ISSUE TITLE
Extend release pipeline to generate an obographs JSON version of fbbt.

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#91]
[obographs](https://github.com/geneontology/obographs) is a handy new JSON format for OBO-ish OWL ontologies such as FBbt.  It would be if we could get FBbt (and other FB ontologies) released in this format.

My main motivation for requesting this is that I'd like to use this in the VFB pipeline, but having this file in the releases makes  the ontology content *much* more accessible to coders to re-use.

This file type can be generated straightforwardly using owltools (which I believe is installed on the server running releases):

`owltools foo.owl -o -f json foo.json`

I'd suggest using the fbbt-relaxed.owl as the source OWL file.  

This can be an additional step in the Jenkins build job here:
https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/fbbt/src/trunk/tools/fbbt_Jenkins.sh

The new file will need to be whitelisted here:
https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/fbbt/src/trunk/tools/fbbt_release_file_whitelist

**Comment by dosumis** [comment]
Edited Jenkins build job.  Pull request here: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/pull/92

**Comment by dosumis** [comment]
Edited whitelist.  Pull request here: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/pull/93

**Comment by temjones** [comment]
This has been implemented, I checked the successful generation of this file in my own branch build in Jenkins. Looks fine AFAICT. @dosumis You've suggested using fbbt-relaxed.owl as the source file but your pull request for the change to the build job used fbbt.owl. Is this what you intended?
