### ISSUE TITLE
Incorrect classification for 'antennal lobe projection neuron'

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#913]
'antennal lobe projection neuron' (FBbt:00007422) is currently a subclass of 'antennal grooming brain interneuron 2' (FBbt:00111646).

This is incorrect: it should be a subclass of 'projection neuron' (FBbt:00007392).
It's propagating some erroneous relationships down the tree such as 
````
'has synaptic terminal in' some 'antennal mechanosensory and motor center zone C'
'has synaptic terminal in' some 'antennal mechanosensory and motor center zone E'
````

**Comment by Clare72** [comment]
I am not seeing this in Protege or on OLS [FBbt:00111646](https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00111646) [FBbt:00007422](https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00007422)

Where are you seeing this classification?

**Comment by mmc46** [comment]
In the latest fbbt-simple.owl, `fbbtdv/fbbt/releases/fbbt-simple.owl`

**Comment by Clare72** [comment]
2020-06-11 file is here:
http://purl.obolibrary.org/obo/fbbt/releases/2020-06-11/fbbt-simple.owl
Currently the same as latest file, which is here:
http://purl.obolibrary.org/obo/fbbt/fbbt-simple.owl

**Comment by Clare72** [comment]
closing - issue resolved after `git pull`
