### ISSUE TITLE
Review somatic muscles

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#915]
'somatic muscle' does not feature highly in OLS search for 'skeletal muscle', despite (related) synonym being present. Based on quick Google searches, 'skeletal' doesn't seem to be strongly favoured over 'somatic', but perhaps synonym could be made exact? Need to find definitions of each.

'adult somatic muscle', 'embryonic somatic muscle', 'embryonic/larval somatic muscle', 'embryonic/larval hypodermal muscle' don't have 'skeletal' synonyms.

We might also want some 'striated' synonyms.

Some muscles also seem like they might be in the wrong place - should 'gut suspension muscle' and 'cardiac outflow muscle' really be 'hypodermal' (larval body wall)? Are all pharyngeal muscles really 'hypodermal'? Need to check some refs.

**Comment by gouttegd** [comment]
Most of the concerns have been addressed by #1087. Further concerns about the place of 'hypodermal' warrant a dedicated issue (#1088). Closing here.
