### ISSUE TITLE
Intervein precursor/primodium

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#94]
This ticket relates to issue #83.

Along with the wing vein precursors, the wing disc has regions identifiable as presumptive interveins; there are commonly used markers that identify the intervein regions. 

I don't think there should be a precursor term for every wing cell; I don't know if those are even individually identifiable in the wing disc. Relatedly, I think the term should include "intervein", and not "wing cell", specifically because it looks like the wing cells are not clearly identifiable until pupal stages when  when the wing disc is everting.

Relationships: part_of relationship to wing disc FBbt:00001778 and wing pouch FBbt:00006029

wing cell FBbt:00004769 should have develops_from relationship to the new term

Suggested potential term, in order of personal preference"
intervein primordium, presumptive intervein, intervein precursor.

Possibly a very restricted group of is_a children (I'm not at all attached to the exact names here, and am not proposing develops_from children)
intervein primordium between presumptive wing veins L1 and L2
intervein primordium between presumptive wing veins L2 and L3
intervein primordium between presumptive wing veins L3 and L4
intervein primordium between presumptive wing veins L4 and L5

References:FBrf0174576, FBrf0104917

**Comment by temjones** [comment]
I have added a term "presumptive intervein". I don't feel entirely confident about adding the group of is_a children you suggested as I haven't had the time to fully investigate these. However, if you find that you require these more specific terms at a later date, I am happy to revisit it. I hope this is satisfactory!

> [Term]
> id: FBbt:00046042
> name: presumptive intervein
> def: "Region of the wing pouch that will develop into an intervein (wing cell)." [FlyBase:FBrf0102828, FlyBase:FBrf0090017]
> is_a: FBbt:00005426 ! anlage
> relationship: part_of FBbt:00006029 ! wing pouch

Added 

> develops_from FBbt:00046042 ! presumptive intervein

 to wing cell (FBbt:00004769)

Also changed wing cell definition to be in the singular instead of plural.
