### ISSUE TITLE
Lineage bundle

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#949]
Proposed definition:   A primary neurite tract or primary axon tract consisting of neurites of all of the neurons in a single lineage or hemilineage. 

See https://www.cell.com/cms/10.1016/j.neuron.2020.08.005/attachment/f7602644-8c73-45ad-a36d-b2d36af4e758/mmc1.pdf for examples.

Problem case:  there is bundle in the VNC that has two lineages.  Bodge this for now?

Note - for PNTs in the brain, which are of a single hemilineag but don't have all the cells,  we can make part_of relationships to lineage/hemilineage clone terms.

**Comment by Clare72** [comment]
see also #783 #779 
Looking back over the (Hartenstein) brain papers, I think it seems reasonable to define this as consisting of a single lineage/hemilineage - this seems to be how they are defined for the brain (PATs and SATs), even if two are found together. We may also want a term for a 'multi-lineage bundle' where a small number of lineage bundles form a larger bundle e.g. DPLp1/2 of brain or 20/22 of VNC.
