### ISSUE TITLE
New term request: MT neurons

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#957]
For new term requests, please provide the following information:

## Preferred term label

MT neuron

## Textual definition

Only definition given as far as I can see:

'Photoactivation in this part of the AOTU revealed projections from the medulla (ME), which we refer to in this paper as MT neurons'

**Comment by Clare72** [comment]
could they mean medullary tangential neurons - FBbt:00003836?
what is the reference?

**Comment by admclachlan** [comment]
Oops, FBrf0236205

**Comment by Clare72** [comment]
These neurons express VT002072 and connect the medulla to the AOTU.

FBrf0233032 supplementary table 1 assigns this driver to MC61, which fits these morphological criteria. In addition, MC61 already has synonyms 'medullo-tubercular neuron' and 'MeTu neuron'.

-> adding 'MT neuron' as synonym for 'medulla columnar neuron MC61' - FBbt:00111641
