### ISSUE TITLE
precursors to eye photoreceptor cells

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#96]
I'm not completely convinced these terms don't exist, but I'm consistently unable to find them! If so, develops_from relationships need adding.  If not, we we need precursor terms for:
eye photoreceptor cell FBbt:00004227
photoreceptor cell R1 FBbt:00004213
photoreceptor cell R2 FBbt:00004215
photoreceptor cell R3 FBbt:00004217
photoreceptor cell R4 FBbt:00004219
photoreceptor cell R5 FBbt:00004221 
photoreceptor cell R6 FBbt:00004223
photoreceptor cell R7 FBbt:00004225
photoreceptor cell R8 FBbt:00004227

These precursor terms will also need part_of relationships to the appropriate is_a children of ommatidial precursor cluster FBbt:00001770 (the definitions of the of those child terms already specify which individual photoreceptor precursor cells should have a part_of relationship).

**Comment by dosumis** [comment]
We have a term for the cluster or precursors, but not for each individual precursor: http://www.virtualflybrain.org/site/stacks/index.htm?id=FBbt_00001770

**Comment by SianGramates** [comment]
Yes, that is exactly my point.  We don't have the individual terms.
