### ISSUE TITLE
correction to definition: presumptive anepimeron

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#98]
The definition of presumptive anepimeron (FBbt:00084593) states that it will develop into the anepisternum (FBbt:00004597). The definition of  presumptive anepisternum (FBbt:00084597) also states that it will develop into the anepisternum (develops_from relationship exists between these two terms.

anepimeron (FBbt:00004593) has a develops_from relationship to   presumptive anepimeron, so it looks like only the definition needs fixing.

**Comment by temjones** [comment]
Edited to fix the anepisternum -> anepimeron part of the definition for presumptive anepimeron (FBbt:00084593). 

As an aside, I think it could be potentially confusing to refer to this structure as "Region of the wing disc **ventral** to the wing pouch" - this description is currently used in the definition of presumptive anepimeron (FBbt:00084593), presumptive anepisternum (FBbt:00084597) and dorsal mesothoracic pleura primordium (FBbt:00006034). I think it would be more accurate to say "Region of the wing disc **distal** to the wing pouch", but there seems to be quite a bit of variation on how axes in the wing disc are referred to in the literature (eg, that end of the wing disc is referred to as "distal" in Bryant 1975 FBrf0027793, labelled "posterior" in the Bryant chapter of Ashburner and Wright, and referred to as "ventral" in Hartl & Scott 2014 FBrf0225274). If anyone has thoughts on this I'd welcome additional input.

**Old stanza:**
[Term]
id: FBbt:00084593
name: presumptive anepimeron
def: "The region of the wing disc, ventral to the wing pouch, that will develop into the anepisternum (mesopleura)." [FlyBase:FBrf0027793, FlyBase:FBrf0031004]
is_a: FBbt:00005426 ! anlage
is_a: FBbt:00007027 ! cuboidal/columnar epithelium
relationship: part_of FBbt:00006034 ! dorsal mesothoracic pleura primordium

**New stanza:**
[Term]
id: FBbt:00084593
name: presumptive anepimeron
def: "The region of the wing disc, ventral to the wing pouch, that will develop into the anepimeron (pteropleura)." [FlyBase:FBrf0027793, FlyBase:FBrf0031004]
is_a: FBbt:00005426 ! anlage
is_a: FBbt:00007027 ! cuboidal/columnar epithelium
relationship: part_of FBbt:00006034 ! dorsal mesothoracic pleura primordium
