### ISSUE TITLE
correction: yellow ommatidium part_of relationship

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#99]
Mysteriously, yellow ommatidium (FBbt:02000001) has a part_of relationship to embryonic ventral epidermis (FBbt:00005747). That can't possibly be correct! It has an is_a relationship to ommatidium (FBbt:00004510), which is part_of retina (FBbt:00004200)

**Comment by temjones** [comment]
Edited to fix.

**Previous stanza:**
[Term]
id: FBbt:02000001
name: yellow ommatidium
def: "Ommatidial subtype with stochastic distribution throughout the retina making up about 70% of all ommatidia. This ommatidial subtype is specialised to detect longer wavelengths (far UV + green)." [FlyBase:FBrf0180690]
comment: The yellow ommatidium expresses the far ultraviolet-specific opsin Rh4 (FBgn0003250) in photoreceptor R7 cells and the green-sensitive Rh6 (FBgn0019940) in photoreceptor R8 cells (Wernet and Desplan, 2004).
subset: cur
xref: VFB:FBbt_02000001
is_a: FBbt:00004510 ! ommatidium
relationship: part_of FBbt:00005747 ! embryonic ventral epidermis


**New stanza:**
[Term]
id: FBbt:02000001
name: yellow ommatidium
def: "Ommatidial subtype with stochastic distribution throughout the retina making up about 70% of all ommatidia. This ommatidial subtype is specialised to detect longer wavelengths (far UV + green)." [FlyBase:FBrf0180690]
comment: The yellow ommatidium expresses the far ultraviolet-specific opsin Rh4 (FBgn0003250) in photoreceptor R7 cells and the green-sensitive Rh6 (FBgn0019940) in photoreceptor R8 cells (Wernet and Desplan, 2004).
subset: cur
xref: VFB:FBbt_02000001
is_a: FBbt:00004510 ! ommatidium
