### ISSUE TITLE
merge antennal lobe VL1 ilPN and mPN2

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#991]
FBbt:00047712 - 'medial antennal lobe tract projection neuron 2' (mPN2) is a class for uniglomerular antennal lobe projection neurons with their somas in the lateral SEZ and projections that follow the mALT.

This was originally thought by Tanaka et al. (2012) - FBrf0219809 to include the bilateral VP3 PN described by Stocker et al. (1990) - FBrf0051437, but this VP3 neuron was found by Marin et al. (2020) - FBrf0246456 to be biglomerular (also innervating VP1l).

The only true mPN2 neuron identified in Bates et al. (2020) - FBrf0246460 comprehensive EM analysis is the VL1 ilPN (FBbt:00049772), so these terms should be merged, keeping the more specific(VL1 ilPN) term.

**Comment by SianGramates** [comment]
Are you maintaining the other terms as synonyms?

**Comment by Clare72** [comment]
Yes, label and synonyms from mPN2 will be added as synonyms to VL1 ilPN

**Comment by SianGramates** [comment]
Great! I strongly approve this merge.
